### ISSUE TITLE
it seemed to not work for this rule

### ISSUE THREAD

**Issue by rezad1393** [einaregilsson/Redirector#100]
Redirect:
https://addons.mozilla.org/(.*)(/.?)src=(.*)

to:
https://addons.mozilla.org/$1

Example:
https://addons.mozilla.org/en-US/firefox/addon/http-request-logger/?src=search → https://addons.mozilla.org/en-US/firefox/addon/http-request-logger

Applies to:
Main window (address bar)

**Comment by Gitoffthelawn** [comment]
Unfortunately, at this time it won't.

See

- https://github.com/einaregilsson/Redirector/issues/90

and

- https://bugzilla.mozilla.org/show_bug.cgi?id=1310082

I encourage you to also post here:

 - https://github.com/mozilla/addons-server/issues/5505

**Comment by anewuser** [comment]
To make all extensions work with addons.mozilla.org, go to `about:config?filter=privacy.resistFingerprinting.block_mozAddonManager` and set it to true.

If this preference (`privacy.resistFingerprinting.block_mozAddonManager`) doesn't exist yet, create it as a boolean.

**Comment by einaregilsson** [comment]
Not a thing that can be fixed in Redirector itself, so am closing it.

**Comment by anewuser** [comment]
You need to erase the value of `about:config?filter=extensions.webextensions.restrictedDomains` too now.

**Comment by Gitoffthelawn** [comment]
@anewuser What are the implications (security, etc.) of setting/erasing those two preferences?

**Comment by anewuser** [comment]
@Gitoffthelawn the result is what the user expects: all extensions will work on Mozilla domains and be able to do whatever they can do on other domains.

**Comment by Gitoffthelawn** [comment]
@anewuser Right, but I'm sure Mozilla doesn't have things set up by default as they are just to be annoying.  They must have found a significant security, privacy, or other risk.

**Comment by grahamperrin** [comment]
@anewuser for this preference, I love you.
