### ISSUE TITLE
Main-frame redirection is not working on Firefox 55b2

### ISSUE THREAD

**Issue by byzod** [einaregilsson/Redirector#102]
## Environment
Key | Value
-- | --
System Platform | AMD64, Windows-10-10.0.14393
Browser | Firefox Developer Edition (55.0 Beta 2, 64 bit)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0
Build Config | https://hg.mozilla.org/releases/mozilla-beta/rev/9e20e9175de1bbcea33b9b67be64d3734156bae4
Redirector | 3.1.0

## Step to Reproduce
1. Import rule below

```JSON
{
    "createdBy": "Redirector v3.1.0",
    "createdAt": "2017-06-17T13:55:23.544Z",
    "redirects": [
        {
            "description": "test",
            "exampleUrl": "https://www.reddit.com/",
            "exampleResult": "www.google.com",
            "error": null,
            "includePattern": "https?://www\\.reddit\\.com/",
            "excludePattern": "",
            "redirectUrl": "www.google.com",
            "patternType": "R",
            "processMatches": "noProcessing",
            "disabled": false,
            "appliesTo": [
                "main_frame"
            ]
        }
    ]
}
```
2. Open https://www.reddit.com/

## Expected Result
www.google.com is opened instead of reddit.

## Actual Result
https://www.reddit.com is opened, not redirected to google.
Browser console said:
```
"REDIRECTOR: Checking: main_frame: https://www.reddit.com/"  background.js:6:3
"REDIRECTOR: Redirecting https://www.reddit.com/ ===> www.google.com, type: main_frame, pattern: https?://www\.reddit\.com/"  background.js:6:3
[Exception... "Component returned failure code: 0x804b000a (NS_ERROR_MALFORMED_URI) [nsIIOService2.newURI]"  nsresult: "0x804b000a (NS_ERROR_MALFORMED_URI)"  location: "JS frame :: resource://gre/modules/WebRequest.jsm :: applyChanges :: line 960"  data: no]
```

**Comment by Gitoffthelawn** [comment]
That is a professional bug report! :)

What tool did you use to generate it?

**Comment by byzod** [comment]
@Gitoffthelawn Hand™

**Comment by einaregilsson** [comment]
@byzod The problem is that your redirect url is not a real url. The result must start with http:// or https:// , your's is just www.google.com . Granted, the extension should probably have a warning or error when the example results obviously wouldn't work, but in this case if you just change the redirectUrl to https://www.google.com then everything should work.
