### ISSUE TITLE
The rule editing popup is not good for long urls (base64 etc)

### ISSUE THREAD

**Issue by byzod** [einaregilsson/Redirector#103]
## Problem
When editing a rule, if `Include pattern` or/and `Redirect to` urls are to long, the popup can't display the buttons below, thus there's no way to edit advanced options or even save/cancel.

## Demo
![a 1](https://user-images.githubusercontent.com/848607/27257936-2c404e5e-541d-11e7-8d03-6a170ee3c701.gif)

**Comment by einaregilsson** [comment]
Ok, didn't really think people would redirect to data urls :) . Fair enough, I'll try to make it work for arbitrary lengths of urls.

**Comment by einaregilsson** [comment]
This is fixed in 3.5.2, we scroll the window.
