### ISSUE TITLE
Request: Comment field?

### ISSUE THREAD

**Issue by Copyrites** [einaregilsson/Redirector#104]
I could really use a free-form comment field for each redirect.  I've got some complicated regexps that need documentation because I won't be able to easily understand 6 months from now.

Is there any chance of a multi-line textbox for comments getting added to the edit form?

Thanks

**Comment by einaregilsson** [comment]
I'm not really adding new features to the addon anymore, it's basically just in maintenance mode. If someone wants to implement it and send a pull request I'd accept it though :)
