### ISSUE TITLE
[info] Redirector can be useful for Open Access of scientific research!

### ISSUE THREAD

**Issue by jibe-b** [einaregilsson/Redirector#106]
Thanks a lot for having developped and maintain Redirector!

I would just like to highlight a possible use of this addon, which consists in redirecting DOI resolvers to a DOI resolver which 

Let's take for example doi.org and oadoi.org (one can use other DOI resolvers), the rule is:

> doi.org -> OADOI.org
Redirect: http*://doi.org/*
to: https://oadoi.org/$2
Example: https://doi.org/ → https://oadoi.org/
Applies to: Main window (address bar), XMLHttpRequests (Ajax)

and one can access more quickly OpenAccess scientific publications, without having to first study 8 years and get hired in a research institution.

The discussion started here: Impactstory/unpaywall/issues/16 if that interest some of you.

**Comment by einaregilsson** [comment]
Sure, I'm glad people can use it. I don't actually use it myself, but I try to keep it up to date so it can be used with new Firefox versions (and Chrome now as well).

**Comment by einaregilsson** [comment]
This is not really a feature request, so am closing it.
