### ISSUE TITLE
Privacy Policy

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [einaregilsson/Redirector#107]
Hey @einaregilsson 

One thing I am in the process of doing with the ghacks user.js [wiki page for extensions](https://github.com/ghacksuserjs/ghacks-user.js/wiki/Appendix-B:-Extensions) is to add **Privacy Policy** links (like below). If an extension has one that respects privacy, awesome, if not, no such "badge" (and if it has one one that stinks, it will not be recommended). 

Would you consider creating a simple AMO Privacy Policy (or GitHub wiki page, or root md file)? Cheers. If not, then just close this issue, thanks :)

* [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) <sup>✔ [Privacy](https://github.com/gorhill/uBlock/wiki/Privacy-policy)</sup> | [GitHub](https://github.com/gorhill/uBlock) << GitHub example
* [Decentraleyes](https://addons.mozilla.org/firefox/addon/decentraleyes/) <sup>✔ [Privacy](https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/)</sup> | [GitHub](https://github.com/Synzvato/decentraleyes)  << AMO example

**Comment by einaregilsson** [comment]
Just added a privacy.md file at https://github.com/einaregilsson/Redirector/blob/master/privacy.md  

It's very simple, since Redirector doesn't collect any data at all :)
