### ISSUE TITLE
Feature Request: Redirect on load / Redirect on Timer

### ISSUE THREAD

**Issue by zetopowef** [einaregilsson/Redirector#109]
- Please add checkbox Redirect on load . Example

1. we are on site.com
2. it redirect to site.com/ready
3. we got redirect mutch
4. wait till it load fully and then redirect rule

- Please add next step rule , that working after load - same, but+timer redirect will work after 1-9 seconds pause

**Comment by einaregilsson** [comment]
Sorry, I have no plans to add more features to Redirector, it's strictly in maintenance mode now.
