### ISSUE TITLE
Youtube redirect to unpredicted "&pbjreload=10"

### ISSUE THREAD

**Issue by fabionar** [einaregilsson/Redirector#111]
https://www.youtube.com/watch?v=123 → www.website.com/123
https://www.youtube.com/watch?v=123&pbjreload=10 → www.website.com/123

How can I set both cases? I tried to create a second rule but isn't working  www.website.com/123&pbjreload=10 → www.website.com/123

**Comment by einaregilsson** [comment]
Something like 

include: https://www.youtube.com/watch?v=(\w)

Pattern type: regex

**Comment by fabionar** [comment]
@einaregilsson now links like: `https://www.youtube.com/watch?v=**2-**rFnI9MrJk`
become www.website.com/2

**Comment by einaregilsson** [comment]
Well, try this include pattern then:

https://www.youtube.com/watch\?v=([^&]+)
