### ISSUE TITLE
Does not work on middle-click

### ISSUE THREAD

**Issue by alexolog** [einaregilsson/Redirector#112]
Using middle-click (to open in a new tab) goes to the non-redirected URL.

**Comment by einaregilsson** [comment]
Sounds weird. I'll look into it for the next release, although I just use a redirection API provided by Firefox, if that doesn't handle this case then there probably won't be much I can do about it.

**Comment by Qwash** [comment]
Works fine here 

FF57-64

**Comment by anewuser** [comment]
@alexolog If you're still having problems, please provide the problematic redirection with a specific example URL. Otherwise, please close this issue.

**Comment by alexolog** [comment]
Seems to be working.
