### ISSUE TITLE
Unable to use as alias rewriter

### ISSUE THREAD

**Issue by szpak** [einaregilsson/Redirector#113]
As [URL Alias](https://addons.mozilla.org/en-US/firefox/addon/url-alias-8703/) is no compatible with Firefox Quantum I was happy to find Redirector as a potential replacement. Unfortunately, I'm not able to use it with non url redirects such as:

```
Diki
Redirect: d *
to: https://www.diki.pl/slownik-angielskiego?q=$1
Example: d small business → https://www.diki.pl/slownik-angielskiego?q=small business
Applies to: Main window (address bar)
```

The aforementioned instead of opening a dictionary with a given term results (for `d space something`) in a default search engine triggered for "d small business".

Can Redirector be use for that kind of tasks?

**Comment by einaregilsson** [comment]
You can't redirect stuff like that, no. The API I use only gets notified of actual http requests, the alias resolution happens way before that. You would need some kind of addon that actually worked directly with the address bar UI to do that I think.

**Comment by szpak** [comment]
Thanks for your explanation. I took a look at the Redirector source code and I see that you use `chrome.webRequest.onBeforeRequest`. I tried to find something similar to the URL bar in general in [Firefox documentation](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API), but with no luck. Do you, by any chance, know what could be used instead?

**Comment by einaregilsson** [comment]
I would guess the https://developer.chrome.com/extensions/webNavigation webNavigation API is what you're looking for, something like onBeforeNavigate or something like that.

**Comment by szpak** [comment]
Thanks @einaregilsson . As in fact I have just one place to use aliasing I switched to the custom "[open search](http://www.opensearch.org/)" engine with a keyword attached.
