### ISSUE TITLE
Responsive images are not redirected in Firefox

### ISSUE THREAD

**Issue by tiborbaksa** [einaregilsson/Redirector#115]
Consider the following Redirector settings:
```json
{
    "createdBy": "Redirector v3.1.1",
    "createdAt": "2018-01-08T16:23:03.299Z",
    "redirects": [
        {
            "description": "Example",
            "exampleUrl": "http://example.com/example.png",
            "exampleResult": "http://example-proxy.com/example.png",
            "error": null,
            "includePattern": "http://example.com/*",
            "excludePattern": "",
            "redirectUrl": "http://example-proxy.com/$1",
            "patternType": "W",
            "processMatches": "noProcessing",
            "disabled": false,
            "appliesTo": [
                "main_frame",
                "image",
                "other"
            ]
        }
    ]
}
```

Also, consider the following HTML:
```html
<img
  src="http://example.com/example.png"
  srcset="http://example.com/example-small.png 480w, http://example.com/example-medium.png 1024w, http://example.com/example-large.png 1920w"
  sizes="(max-width: 480px) 480px, (max-width: 1024px) 1024px, 1920px"
/>
```

If you open a page with this HTML, Firefox 57 won't redirect the request to `http://example-proxy.com` but will try to load one of the images in the `srcset` attribute from `http://example.com`. On the Network tab, the cause of the request will be `imageset`.

The same configuration works as expected in Chrome.

**Comment by einaregilsson** [comment]
Ok, looks like they have made a new request type for the srcset. Will look into it for the next release. Not sure when that will be though.

**Comment by gkrishnaks** [comment]
Hi,
With this commit, https://github.com/gkrishnaks/Redirector/commit/7490d7adee1d7f938ee92f743c8d17f87e554848 , it works in Firefox - but stopped working in chrome :(

'imageset' is not a valid request type supported by Chrome.
Error in response to storage.get: Error: Invalid value for argument 1. Property 'types.1': Value must be one of: [main_frame, sub_frame, stylesheet, script, image, font, object, xmlhttprequest, ping, csp_report, media, websocket, other].

Let me check again for this issue and then send Pull request.

**Comment by gkrishnaks** [comment]
Added to Pull Request. 

Added a condition to check supported types. 
Fix works in both chrome and firefox now - I tested on this response web image demo site with the below settings.json 

1. demo url https://responsiveimages.org/demos/basic-implementation/index.html
2. Resize screen till you reach mobile size - image should be replaced with Yacht image from the same site

Settings:

{
    "createdBy": "Redirector v3.1.1",
    "createdAt": "2018-05-18T17:56:53.529Z",
    "redirects": [
        {
            "description": "Example",
            "exampleUrl": "https://responsiveimages.org/demos/basic-implementation/test_landscape_1@1x.jpg",
            "exampleResult": "https://responsiveimages.org/demos/on-a-grid/img/yacht_race@mobile.jpg",
            "error": null,
            "includePattern": "https://responsiveimages.org/demos/basic-implementation/test_landscape_1@1x.jpg",
            "excludePattern": "",
            "redirectUrl": "https://responsiveimages.org/demos/on-a-grid/img/yacht_race@mobile.jpg",
            "patternType": "W",
            "processMatches": "noProcessing",
            "disabled": false,
            "appliesTo": [
                "main_frame",
                "image",
                "imageset",
                "other"
            ]
        }
    ]
}
