### ISSUE TITLE
How to open the log?

### ISSUE THREAD

**Issue by laman132** [einaregilsson/Redirector#116]
I've looked all over the documentation, and even skimmed the comments here and on the mozilla site, but can't figure out how to open the log? I can enable logging well enough, but don't know how to actually access the log.

**Comment by einaregilsson** [comment]
Are you on Firefox or Chrome? Chrome: Go to extensions and click the link that says "inspect views: background page" and then look in the developer console. Firefox: Open the Browser console, should show up there.

**Comment by laman132** [comment]
Thanks!
