### ISSUE TITLE
Unresponsive Script on reddit

### ISSUE THREAD

**Issue by laman132** [einaregilsson/Redirector#118]
I've managed to reproduce the error. I'm on Firefox 59.0.1 (64-bit); it doesn't have to do with any of my redirects (I tried it with all of them disabled).

Results of the log

    "REDIRECTOR: Checking: main_frame: https://www.reddit.com/user/rashbalash/m/raspberrypi/?count=25&after=t3_86fhfm"                 background.js:6
    Error: Script terminated by timeout at:                                                                                            redirect.js:235:17
    _includeMatch@moz-extension://a2348c3d-3788-42f2-834d-32829c5f558b/js/redirect.js:235:17
    getMatch@moz-extension://a2348c3d-3788-42f2-834d-32829c5f558b/js/redirect.js:94:16
    checkRedirects@moz-extension://a2348c3d-3788-42f2-834d-32829c5f558b/js/background.js:72:16

Go to any multireddit (NOT your own). For example `https://www.reddit.com/user/rashbalash/m/raspberrypi/`. Scroll to the bottom, click 'Next'. Page hangs. Firefox says a script has become unresponsive.

**Comment by einaregilsson** [comment]
Are you sure they're all disabled? Because the stacktrace indicates that it's trying to match a particular redirect.

**Comment by laman132** [comment]
They were all disabled. I double checked. I deleted all the redirects and then it worked fine, so I guess the problem is solved? Possibly disabling the redirects don't work? In any case, thanks.
