### ISSUE TITLE
Can't 'copy as curl' from network inspector

### ISSUE THREAD

**Issue by mlda065** [einaregilsson/Redirector#122]
# Steps to reproduce:

* Firefox Menu > Web Developer > Network
* load a page
* find a request which was redirected by this extension
* right click, copy > copy as cURL

![copy-as-curl](https://user-images.githubusercontent.com/7035647/40336273-0ce7db78-5dac-11e8-99e3-0f336c7276d3.png)

# Expected Behaviour

Clipboard now contains something like:

    "https://www.redditmedia.com/gtm?id=GTM-5XVNS82&cb=null" -H "Host: www.redditmedia.com" -H "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8" -H "Accept-Language: en-US,en;q=0.5" --compressed -H "Connection: keep-alive" -H "Upgrade-Insecure-Requests: 1" -H "DNT: 1"

# Actual Behaviour

* Nothing was copied to the clipboard
* clipboard contains whatever was on there before
* "Copy URL" still works as expected

# My setup

Firefox 64 bit, 60.0.1

I wanted to try in Chrome as well, but I can't get my redirects to work properly on Chrome.

**Comment by einaregilsson** [comment]
Hmmm, have never thought about that one :) I use a redirection API provided by the browser, I don't think the API that extensions can use have any way to affect how that works. The WebExtensions API is much more limited than the old extension API in Firefox, so there are a lot of things you just can't do.

**Comment by einaregilsson** [comment]
Not something we can affect, since we just tell the browser to redirect, closing this.
