### ISSUE TITLE
Logging does not work

### ISSUE THREAD

**Issue by dub4u** [einaregilsson/Redirector#124]
This is on 64bit Firefox Quantum v60.0.1, with logging enabled I see no logging in the developer console (F12).

**Comment by einaregilsson** [comment]
Ok, thanks for reporting. Will look into it before the next release.

**Comment by gkrishnaks** [comment]
@dub4u In Firefox - can you check in 'Browser console' once? 
Menu -> Developer -> Browser Console.. 
"Browser console" in Firefox Quantum is similar to Chrome's F12 console with 'Preserve log' enabled.

**Comment by dub4u** [comment]
@gkrishnaks that's it. I see the log statements in Browser Console, but not in Web Console. Thanks! Closing the issue.
