### ISSUE TITLE
Redirect the page based on its content

### ISSUE THREAD

**Issue by akai1831** [einaregilsson/Redirector#125]
Hi,

Would it be possible to feature this kind of request, redirect the page based on its content. Let's say on image below, if it shown it will redirect to other url. The thing is it doesn't change the URL even if it is in error page that is why we're requesting this sort of feature.
![ise](https://user-images.githubusercontent.com/20372600/43831811-033e24de-9b0e-11e8-97b3-5d7a6a816e3a.JPG)

**Comment by einaregilsson** [comment]
Sorry, no plans for that feature. The redirects are only based on the url, and I don't want to complicate the extension any more for a feature that not many people would use.
