### ISSUE TITLE
Storage sync not working in Firefox after PR 120

### ISSUE THREAD

**Issue by gkrishnaks** [einaregilsson/Redirector#127]
Storage sync not working in Firefox as getBytesInUse is not yet supported by Firefox Extension API.
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea/getBytesInUse - Also, firefox returns NaN for storage size checks too so storage never gets moved to Sync Area.. :/    

I missed it in my PR .. https://github.com/einaregilsson/Redirector/pull/120  

(however, rules stored in Local are not lost and disabling sync and refreshing page shows old rules in Local all fine.. as I did put conditions to copy and delete values only if successfully moved!) 

I will look into this and submit a PR soon for Firefox.

('Sync' storageArea works fine in Chrome and Opera)

**Comment by einaregilsson** [comment]
Ok. This is why I specifically asked whether it worked in Chrome and Firefox!

**Comment by gkrishnaks** [comment]
Yes, I missed it.. :(   I did check every other thing in that PR across Chrome and Firefox. Please review the PR I just raised.

**Comment by einaregilsson** [comment]
Ok, we all make mistakes :) I've published the fix to the Firefox version.
