### ISSUE TITLE
Simply not redirecting on firefox dev edition 64.0b6

### ISSUE THREAD

**Issue by hkrware** [einaregilsson/Redirector#130]
I get the notifcation, but I am not being redirected.
**Rule:** PHP en
**Redirect:** php.net/manual/bg/(.*)$
**to:** php.net/manual/en/$1
**Example:** php.net/manual/bg/xxx.php → php.net/manual/en/xxx.php
**Applies to:** Main window (address bar), IFrames, Stylesheets, Scripts, Images, Responsive Images in Firefox, Objects (e.g. Flash videos, Java applets), XMLHttpRequests (Ajax), Other

![image](https://user-images.githubusercontent.com/4815620/47954652-28a7b200-df95-11e8-9ba7-7ff110fb521c.png)

**Comment by einaregilsson** [comment]
Do the redirects work on other sites? Did this redirect work before?

**Comment by hkrware** [comment]
It's a fresh install and first rule. I found the problem, though. It doesn't work if you don't specify the protocol scheme i.e. **http://** in the beginning of the **Redirect to** field.

**Comment by einaregilsson** [comment]
Yes, you must specify a full url for the redirect :)
