### ISSUE TITLE
Not redirecting on initial page load

### ISSUE THREAD

**Issue by alanbaumgartner** [einaregilsson/Redirector#132]
When clicking on a link from google that should be redirected to another webpage, it doesn't redirect until I refresh/reload the page.

Include Pattern
http://oldschoolrunescape.wikia.com/wiki/*

Redirect to
https://oldschool.runescape.wiki/w/$1

Test with
https://oldschool.runescape.wiki/w/Chambers_of_Xeric/Strategies

However any oldschool.runescape.wikia links should work (as in not work).

**Comment by einaregilsson** [comment]
Which browser, Chrome or Firefox?

**Comment by alanbaumgartner** [comment]
I am using Opera.

**Comment by einaregilsson** [comment]
Ok, not sure what's going on there. I'll try to look into this before the next release, but I honestly have no idea when that will be.

**Comment by alanbaumgartner** [comment]
Problem must have been related to opera as the issue has resolved itself!
