### ISSUE TITLE
Change repository description

### ISSUE THREAD

**Issue by qqgg231** [einaregilsson/Redirector#134]
Please change "Firefox extension to redirect urls ..."
To something like "multi browser" or "Firefox, Chrome, Opera, Vivaldi, Edge"

**Comment by einaregilsson** [comment]
Done :) Does it work in Edge though?

**Comment by qqgg231** [comment]
I didn't try, but it is possible: 
https://www.google.com/search?q=edge+chrome+extension

:-)

**Comment by KrasnayaPloshchad** [comment]
MS Edge is now Chromium based browser, it’s now accept installing extensions from Chrome Web Store.

**Comment by einaregilsson** [comment]
Done. I tested it in Edge and it does work, although I'm not sure how to get to the logs and stuff, but the redirecting does work.
