### ISSUE TITLE
Facebook New Activity (aka RECENT_ACTIVITY) to New Posts (CHRONOLOGICAL)

### ISSUE THREAD

**Issue by i486** [einaregilsson/Redirector#137]
Hello

I am trying to redirect Facebook group's sorting setting from New Activity to New Posts when clicking on New Activity button.

Here is a screenshot of the sort setting i am talking about.

![Image of Random Facebook Group](https://i.imgur.com/mcSFWux.png)

**Description of what each button do when clicked on it**

- Clicking on New Activity will change the URL to following
- https://www.facebook.com/groups/606857332842653/?sorting_setting=RECENT_ACTIVITY
- Clicking on TOP POSTS will change the URL to following
- https://www.facebook.com/groups/606857332842653/?sorting_setting=TOP_POSTS
- Clicking on RECENT POSTS will change the URL to following
- https://www.facebook.com/groups/606857332842653/?sorting_setting=CHRONOLOGICAL

Sadly Facebook hidden RECENT POSTS button on most groups which is why i am trying to redirect RECENT_ACTIVITY to RECENT POSTS.

My Rule

- Description: Facebook Recent to Chronological
- Example: https://www.facebook.com/groups/606857332842653/?sorting_setting=RECENT_ACTIVITY
- Include Pattern: https://www.facebook.com/groups/*/?sorting_setting=RECENT_ACTIVITY
- Redirect to: https://www.facebook.com/groups/$1/?sorting_setting=CHRONOLOGICAL
- Pattern type: Wildcard

I also tried checking every buttons (iFrames, Scripts, etc) on "Apply to"  section and it still doesn't work when clicking on New Activity button.

It works when I press refresh though. 

What am i doing wrong?

**Comment by einaregilsson** [comment]
You're not doing anything wrong. What's probably happening is Facebook is not actually switching to the new page normally when you press the button, they are getting the data with some API call, and then just updating the url in the addressbar without actually loading that page. Redirector unfortunately can't handle that.

**Comment by i486** [comment]
> 
> 
> You're not doing anything wrong. What's probably happening is Facebook is not actually switching to the new page normally when you press the button, they are getting the data with some API call, and then just updating the url in the addressbar without actually loading that page. Redirector unfortunately can't handle that.

You're most likely right. This is what happened when i clicked on one of the button. Probably the API call you're talking about, right?

![Image of Yaktocat](https://i.imgur.com/Xu8lTwN.png)

So, I understand that it's not possible to change the API stuff with Redirector.

But what if Redirector could monitor the firefox URL bar (I assume it does that already, but only when page loads, refreshes, etc) and if it sees any changes then do his normal redirection job by using the rules? 

Do you think you can add this functionality? 

Sorry about my english

**Comment by i486** [comment]
Understandable, I have a few questions though.

1. How hard it will be to add that (monitor firefox urlbar and redirect) function I've described above to Redirector? What kind of coder should i hire if i decide to hire one? I mean, you know, which programing language coder must be experienced and stuff like that.

2. Do you know any other add-on or something to automatically change that parameter I've showed on Fiddler screenshot?

Thank you

**Comment by einaregilsson** [comment]
Should not be hard at all. Just find a javascript developer and make an extension that does exactly this. Here's an extension that does something similar: https://chrome.google.com/webstore/detail/enforce-facebook-sort-ord/fipecflmmkffgmdmgmlngcmafianngka?hl=en

**Comment by einaregilsson** [comment]
Page transitions within Facebook, YouTube, Twitter and other big sites that use the history api and pushstate can't be redirected with Redirector, and we have not plans to support them, so closing this issue.

**Comment by i486** [comment]
I got an firefox notification that one of my add-ons needs a new permission. I checked it and found that it's Redirector that needs to update with a new permission. I was like "Did the Redirector add-on got hacked or something? I remember the author telling me that Redirector is in maintenance mode and won't be updated for new features, etc.

So i looked at changelog and found this at the bottom
> New type of redirect, "HistoryState", that lets you _delete_ **(btw typo?)** pages on Facebook, Twitter and others that modify the page with javascript and then push a new url to the address bar with the History api.

It sounds like something that could solve my facebook redirection issue posted above.

I updated the add-on and enabled my old non-working redirect (I still have it disabled) and checked "HistoryState" only.  

And HELLL YEAH!!!!!!!!!!!!!!! IT'S WORKING GREAT!

Thank you Mr. @einaregilsson

**Comment by einaregilsson** [comment]
Haha, glad it helped. I do say that it's in maintenance mode and I have no plans to add new features, but the reality is that this addon was first released in 2007, a lifetime ago, and I basically once every 2-3 years clean up some stuff, modernize it and release a new version. But "I might do that feature in 3 years" isn't really a reply that people are happy with!
