### ISSUE TITLE
What to do with moz-extension://*?

### ISSUE THREAD

**Issue by brenoritvrezorkre** [einaregilsson/Redirector#138]
Your code states that here you come across a firebug.

But still, is it possible to fix it?

**Comment by einaregilsson** [comment]
I don't understand, come across a firebug?  The extension can only redirect http:// and https://, it can't redirect moz-extension://

**Comment by brenoritvrezorkre** [comment]
Fundamentally impossible to redirect? If so, then it's a pity.

**Comment by einaregilsson** [comment]
Might be possible to do it in some way, but not using the webRequest API that I'm using in Redirector.

**Comment by brenoritvrezorkre** [comment]
This would be useful as a centralized eliminating the negative effects of some needed addons.

**Comment by einaregilsson** [comment]
Closing this, don't want to mess with moz-extensions:// urls.
