### ISSUE TITLE
Sometimes drag and drop for redirect rules stops working

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#14]
I've noticed that sometimes drag and drop to reorder redirect rules stops working.  I done some testing, but haven't yet determined the cause.

The workaround is to close the Redirector interface and then reopen it.

**Comment by einaregilsson** [comment]
Thanks. Like with all other issues, I'll merge if someone decided to fix, but don't have the time to work much on this myself.

**Comment by Gitoffthelawn** [comment]
I probably won't have time to fix that one either, so if someone else out there can fix it, go for it!

**Comment by einaregilsson** [comment]
There's no drag and drop after https://github.com/einaregilsson/Redirector/issues/30 , so this will no longer be an issue
