### ISSUE TITLE
In Chrome's new Dark Mode the icon is nearly invisible

### ISSUE THREAD

**Issue by maxwelljordanwhite** [einaregilsson/Redirector#145]
Here is an example on the latest Chrome release for macOS Mojave. 

<img width="262" alt="Image 2019-04-27 at 7 23 13 PM" src="https://user-images.githubusercontent.com/7244793/56856135-1134fa80-6922-11e9-82c3-122b31d3645f.png">

**Comment by einaregilsson** [comment]
I'll try to fix this on both Chrome and Firefox in the next release.

**Comment by sebast889** [comment]
+1
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#Syntax

`theme_icons` can be used to set both a dark and light icon
