### ISSUE TITLE
Feature Request: Import rules from online source

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [einaregilsson/Redirector#147]
With this feature everyone would easily to share their rules online for your extension, and directly import into settings page. [Gooreplacer](https://github.com/jiacai2050/gooreplacer) and [URLRedirector](https://github.com/fengyc/URLRedirector) were already implemented this functionality.

**Comment by einaregilsson** [comment]
Interesting, but I'm not sure how much general interest there is for that.

**Comment by qqgg231** [comment]
It would work similar to uBlock rules, 

pretty useful I think

**Comment by ttuygun** [comment]
I think it will be useful because the storage limit api has some limitation about size. For this reason, it will be causes to data loss if you exceed the limit (https://github.com/einaregilsson/Redirector/issues/155)

**Comment by einaregilsson** [comment]
How do the other extensions implement this? You go to a page that has redirects and you get some kind of notification?

**Comment by KrasnayaPloshchad** [comment]
OK, so let me tell you how does this works. First, you need install and configure the extension.
* gooreplacer
After installation, click the button to open the setting page.
After the setting page opened, click Online-rules label, then add [this list](https://raw.githubusercontent.com/jiacai2050/gooreplacer/master/gooreplacer.gson) into Rule List URL input box, finally click Update Now button.
* URLRedirector
After installation, click the button to open the popup, enable Redirect checkbox, then click Options button.
After opening URLRedirector Options, add [this list](https://raw.githubusercontent.com/fengyc/URLRedirector/master/tools/rules.json) into Online Rules URL, click Save button. Finally click Download button to get the list.

After you installed one of them, configured the list, you will see the Google Font resource will be redirect to a mirror server. For example, if you open https://www.amirifont.org/ you will see the font is loaded from proxy.ustclug.org instead of googleapis.com, and you can see the notification at the bottom of page while the page is loading.

**Comment by einaregilsson** [comment]
Closing this. Not interested in adding it as a feature. People can post their exported rules as json files if they want, and other people can download them and import into the extension.

**Comment by minus7** [comment]
Copying/Pasting individual rules to/from the clipboard may be an easy way to add rules from e.g. somewhere on the web, someone who wants to share their Nitter instance or just between your computers if you don't want the same rules everywhere. Dealing with the import/export feature isn't really a good fit for those use cases
