### ISSUE TITLE
It seemed to not work in some pages from special URL

### ISSUE THREAD

**Issue by mlgexyz** [einaregilsson/Redirector#148]
![图片](https://user-images.githubusercontent.com/21287731/59008814-08f3a780-885e-11e9-9d20-2dd01a47e54c.png)
![图片](https://user-images.githubusercontent.com/21287731/59008879-3e989080-885e-11e9-993d-728a3cc79384.png)
There are some imgs in the pages from “moz-extension://”. But the redirecting rule is not work like the pages from "http(s)://".

**Comment by einaregilsson** [comment]
Yes, the addon only works on http:// and https:// , the redirection API we use only supports that.
