### ISSUE TITLE
url rewrite and redirection to localhost

### ISSUE THREAD

**Issue by trappedinspacetime** [einaregilsson/Redirector#149]
First of all thank you for developing this addon.
I made a localhost wikipedia server via `Zimserver`
When I search something in google I get the search url something like

      https://en.wikipedia.org/wiki/Asia

I want to redirect it to

      http://localhost:7891/A/Asia.html

notice the `.html` suffix and `/wiki/` to `/A/` transition.

When I click the url in the google search result it must be opened in the redirected `localhost:7891` server as I stated above.

I don't know how to concoct `regex` to achieve what I want.

**Comment by einaregilsson** [comment]
You want this on every page on Wikipedia? And for every page there is a /<firstletter>/ ?. Hmmmm.

Something like:
![Screenshot 2019-06-21 at 10 32 32](https://user-images.githubusercontent.com/557149/59916878-e93cb180-940f-11e9-9038-f7c69a4f9f20.png)

**Comment by trappedinspacetime** [comment]
Thank you for responding.
`You want this on every page on Wikipedia? And for every page there is a /A/ where A is the first letter of the subject ?.`
Yes, it's  exactly the case.
I managed to make this rule which works like a charm:

![redirector](https://user-images.githubusercontent.com/1314821/59925056-e5288800-943f-11e9-8f71-e7e9cf27a869.png)
It's an awesome extension. 
Thank you!

**Comment by einaregilsson** [comment]
Ok, great that it worked. But your redirect has /A/ in all redirected urls, is that supposed to be like that? Is it not like /B/Beatles.html , /C/clash.html etc?

**Comment by trappedinspacetime** [comment]
@einaregilsson No, it's luckily only  `/A/` prefix for all links. But I am sure your extension will deal with more complicated redirections.
Thank you again, I am grateful to you.
