### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by Puro00** [einaregilsson/Redirector#151]
Hello

Can you please give Dark theme option for the addon?

**Comment by einaregilsson** [comment]
I'll try to add that in the next version. Not sure when that will be though.

**Comment by AndydeCleyre** [comment]
The instructions to fix this in the README have no effect, and should be removed.

![image](https://user-images.githubusercontent.com/1787385/64645242-6e69ae00-d3e2-11e9-93cd-e29e7cfde61e.png)

I notice that the Tree Style Tab button directly to the left of Redirector's uses an svg which gets colored the same as Firefox's non-extension buttons, which is ideal. I wish all extension toolbar icons had to be monochrome, for easy theme application.

**Comment by einaregilsson** [comment]
This is implemented in version 3.5 which is pending review and should be out in a couple of days.
