### ISSUE TITLE
Firefox v69: Browser not Following Address Bar Redirects

### ISSUE THREAD

**Issue by akgunter** [einaregilsson/Redirector#158]
Ever since I updated Firefox to version 69, it hasn't respected Redirector's window redirects. I can see that Redirector is correctly applying the rules and throws a notification up when I tell it to, but the browser doesn't actually go to the new location.

I feel like the core issue is a Firefox setting I'm missing, but I can't for the life of me find the right button.

**Comment by einaregilsson** [comment]
Seems to work for me. Is it one specific redirect that doesn't work, or do no redirects work?

**Comment by akgunter** [comment]
No redirects work, and this persisted between a reinstall of Firefox too.

**Comment by einaregilsson** [comment]
Ok, can you try turning the logging on and see what shows up in the browser console?

**Comment by akgunter** [comment]
Ah! I managed to figure it out!

Apparently I didn't test nearly thoroughly enough last week and was wrong about the symptoms. Most redirects were working fine. Firefox was ignoring redirects to strings that it didn't recognize as valid URLs, even if that string works if you type it in manually. In my case, I was trying to redirect a YARN UI link to a local port because of firewall stuff. Previously, using a target of `localhost:1234$1` worked; but now it has to be `http://localhost:1234$1`.

Just in case they're useful to you, here is the plugin's log output for the rule in question, with identifying IDs obfuscated of course.
```
REDIRECTOR: Checking: main_frame: http://ip-123-123-123-123.ec2.internal:20888/proxy/application_1234567890123_1234/
REDIRECTOR: Redirecting http://ip-123-123-123-123.ec2.internal:20888/proxy/application_1234567890123_1234/ ===> localhost:20890/proxy/application_1234567890123_1234/, type: main_frame, pattern: http://ip-123-123-123-123.ec2.internal:20888(.*) which is in Rule : Test Rule
REDIRECTOR: Showing redirect success notification
```

And the same, but after correcting the target:
```
REDIRECTOR: Checking: main_frame: http://ip-123-123-123-123.ec2.internal:20888/proxy/application_1234567890123_1234/
REDIRECTOR: Redirecting http://ip-123-123-123-123.ec2.internal:20888/proxy/application_1234567890123_1234/ ===> http://localhost:20890/proxy/application_1234567890123_1234/, type: main_frame, pattern: http://ip-123-123-123-123.ec2.internal:20888(.*) which is in Rule : Test Rule
REDIRECTOR: Showing redirect success notification
REDIRECTOR: Checking: main_frame: http://localhost:20890/proxy/application_1234567890123_1234/
REDIRECTOR: Ignoring http://localhost:20890/proxy/application_1234567890123_1234/, was just redirected 200ms ago
```

**Comment by einaregilsson** [comment]
Ah ok. Thanks for letting me know :)
