### ISSUE TITLE
Tiny request: Turn on visible AMO stats

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#16]
Einar, there is a simple way to turn on visible stats in AMO extension pages.

Here's a random example: http://i.imgur.com/FoRkEfL.png

Visible stats are currently off for both your extensions.  Do you mind turning them on?

Note that I assume that toggling this setting does not change anything (does not add data collection), but just allows everyone to see the data.  If my assumption is wrong, and toggling it actually adds data collection for every user, by all means ignore this request!

**Comment by einaregilsson** [comment]
Should be public now :)

**Comment by Gitoffthelawn** [comment]
It is!  Thank you Einar!
