### ISSUE TITLE
Tag release on GitHub

### ISSUE THREAD

**Issue by FranklinYu** [einaregilsson/Redirector#161]
Seems like it's already 3.2.0 on Chrome Web Store and 3.2.1 on Firefox add-on store. Latest GitHub tag is 3.1.0 in contrast.

**Comment by einaregilsson** [comment]
Yeah, should have done that. Have just pushed tags for 3.2.0 and 3.2.1 . Only difference between the two is that 3.2.1 hides some sync options for Firefox.
