### ISSUE TITLE
Can't redirect to a different Pandora page

### ISSUE THREAD

**Issue by Zoooook** [einaregilsson/Redirector#164]
I'm trying to redirect from https://www.pandora.com/collection to https://www.pandora.com/collection/stations and I can't make it work. I've also tried redirecting from https://www.pandora.com/my-music, which what the "My Collection" button points to, and that doesn't work either.

**Comment by einaregilsson** [comment]
Might be because they use some ajax magic to load their pages or something. I can't really test it since Pandora is blocked here in Iceland...

**Comment by Zoooook** [comment]
Ah that sucks :( I guess you could VPN around it

**Comment by einaregilsson** [comment]
Yeah, that's really more effort than I'm prepared to put in right now, sorry.

**Comment by einaregilsson** [comment]
Version 3.5 which is pending review adds a new type of Redirect, "HistoryState" which should work on this problem.
