### ISSUE TITLE
Restore old icon

### ISSUE THREAD

**Issue by Vulgaris-Viridis** [einaregilsson/Redirector#171]
Hi @einaregilsson, I appreciate the effort you've put into designing the new icon,  and while the new icon looks cool, i prefer the way the old one was blending in with the dark Firefox theme. Is there an option to restore the old icon, and if not, would it be something you'll consider adding as an option with the next release?

**Comment by Gitoffthelawn** [comment]
@Vulgaris-Viridis What do you think of the idea of the "On" icon being the large dark 'R', and the off icon being the same with a red 'Off' overlay?  I think that would make the icon blend for you when Redirector is on, but stand out when it's off.

**Comment by Vulgaris-Viridis** [comment]
Hi @Gitoffthelawn That sounds great, it would indeed blend very well. As for only the 'off' icon standing out, that's something I'd like to see with all extensions. I don't think users need to be notified or reminded that the extension is 'on'. If you've installed an extension - that's what you expect from it. Users should only be 'notified' in case of an error or malfunction and hopefully more devs adopt this approach.

**Comment by einaregilsson** [comment]
Sorry, I don't want to have multiple variations of how the icon works. I think the most natural thing to do is make it visible in both the light and dark themes, like it is now.
