### ISSUE TITLE
Need old 3.2.1 version of Redirector! Where can I download?

### ISSUE THREAD

**Issue by seefeel** [einaregilsson/Redirector#173]
I am using Chrome 49.0. New Redirector 3.5.2 not working correctly. It is not possible to add and edit items. Where can I download version 3.2.1? (On my Vista I cannot update browsers)

screenshot: https://i.imgur.com/xvEP33R.jpg

**Comment by einaregilsson** [comment]
Hi. What happens when you click on "Create Redirect"? Nothing? You can't download 3.2.1 anymore  , but you can get the source code here if you want to build it yourself.

**Comment by seefeel** [comment]
Hi! When click on "Create Redirect" nothing happens. 
How can I get the source code of 3.2.1?

**Comment by seefeel** [comment]
UPD: I found, thanks.

**Comment by seefeel** [comment]
UPD: Everything works again with 3.2.1 version.

screenshot: https://i.imgur.com/BqOOoC8.jpg

**Comment by einaregilsson** [comment]
Ok, glad you managed to get it working. Closing this issue :)
