### ISSUE TITLE
Unable to open Redirector-enabled links in new tab.

### ISSUE THREAD

**Issue by shortenjukebox** [einaregilsson/Redirector#181]
## Specifications
* Redirector 3.5.2
* Firefox 72.0.1 (64-bit)
* macOS

## Steps to replicate

1. Open a page (Page A) that has a link to another page (Page B)
2. Create a new redirect, based on Page B’s URL
3. Open Page A’s link to Page B in a new tab, either via the right-click menu or by left-clicking while pressing a modifyer key (e.g. Command, Ctrl)

## Observed behavior

The new tab will open in the background, but it immediately closes within a second.

## Notes

The specific redirect I use is:

* Example URL: `https://www.ebay.com/itm/This-Is-An-Example/123456789010?epid=1234567890&hash=itemg1bb3r1sh:g:Ev3nM0r3G1bb3rsh`
* Include pattern: `https://*ebay.com/itm/*/*?*`
* Redirect to: `https://www.ebay.com/itm/$3`
* Pattern type: `Wildcard`
* Example result: `https://www.ebay.com/itm/123456789010`
* Exclude pattern: *blank*
* Process matches: `No Processing`
* Apply to: `Main window`

While it’s important to note that I also use the [Temporary Containers](/stoically/temporary-containers) extension, since it’s known to interfere with many extensions, the issue persists with that extension disabled.

If you must know the other extensions I use, I can privately message that information.

**Comment by shortenjukebox** [comment]
My mistake! Tried to replicate the issue on a clean Firefox installation, and the issue was completely unrelated to Redirector. Looks like another extension was causing the issue…

Thank you for maintaining the extension through all these years, @einaregilsson. <3

**Comment by einaregilsson** [comment]
@shortenjukebox Ok, thanks for letting me know :)

**Comment by rakleed** [comment]
@shortenjukebox do you remember what extension was causing this problem?
