### ISSUE TITLE
Mobile friendly responsive web design

### ISSUE THREAD

**Issue by in4u** [einaregilsson/Redirector#193]
**Problem**

Currently, the option pages are not mobile friendly at all.

**Solution**

Simply adding the following line in the `<head>` section of all HTML pages should make them responsive:

```html
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
```

**Comment by Gitoffthelawn** [comment]
What browser did you test on?

I just tested it using Responsive Design Mode in Firefox (desktop), and it looked good, albeit tiny.

Also, the meta params your recommended all look good to me, except one that I don't quite understand.  What's the necessity and function of `content="ID=edge"`?

Thanks!

**Comment by in4u** [comment]
I tested on Firefox for Android. And you're right, the first line isn't really required since it's more applicable for IE compatibility. Will edit the post accordingly.

**Comment by Gitoffthelawn** [comment]
@in4u wrote:
> "I tested on Firefox for Android and it seems to work well for me."

Do you mean you tested your `meta` addition, or you tested the current release?

When I wrote that I just tested "it", I meant the current release.  It would have been better communication if I had been more specific, and I'll edit my post for clarity right now.

**Comment by einaregilsson** [comment]
Don't really have time to work on this right now, but will get back to it when I can. But I do accept pull requests :)

**Comment by Gitoffthelawn** [comment]
@einaregilsson Once I hear back from @in4u, I can create a pull for this.  Easy enough.

**Comment by in4u** [comment]
@Gitoffthelawn I saved `redirector.html` from the addon's option page in Firefox desktop (so that all my rules were included to check how their layout appears on mobile). The remaining HTML pages were taken as is from this repo. Then just added the `meta` tag to them and tested the pages on Firefox desktop (with and without responsive design mode) and a mobile device.

**Comment by Gitoffthelawn** [comment]
@in4u That's a clever and easy way of doing it!  Thanks for the details.
