### ISSUE TITLE
Write rules to disable a page's own loading

### ISSUE THREAD

**Issue by doronbehar** [einaregilsson/Redirector#194]
Somewhat related to #178 and #174 . I'd like not to _redirect_ a url to somewhere, but rather just stop all loading of that page. Here's my use-case:

These URLS:

```
(https://technion.zoom.us/j/[0-9]+)\?.*
```

Are automatically redirected by the website (zoom) to:

```
https://technion.zoom.us/download
```

But I'd like to copy the original URL to a native application - i.e stop the website's redirect.

I tried to redirect it to a non existing URL such as:

```
about:_$1
```

Ideally, I'd like redirector to just "press <esc> for me" - stop the page from reloading.

But that is still somewhat not super-easy to copy-paste as the original URL and it requires https://github.com/einaregilsson/Redirector/issues/178 and/or #174 .

Do you think @einaregilsson it'd be possible to implement this feature without too-big changes to the codebase?

Thanks for creating this addon.

**Comment by einaregilsson** [comment]
I guess you could just put `https://technion.zoom.us/download` as the include pattern and redirect to a non existent url on localhost, e.g. http://localhost/notexist . Would that work for you?

**Comment by doronbehar** [comment]
That's not what I was thinking of @einaregilsson . I want the website to _stop_ redirecting me from a `https://technion.zoom.us/` to `https://technion.zoom.us/download`, while **keeping the original** `https://technion.zoom.us/j/` **URL on the address bar**.

**Comment by Gitoffthelawn** [comment]
If I'm not mistaken, what you *really* want is for the page to redirect to a local JavaScript function that automatically copies the captured URL to the clipboard (or a small internal page that displays the captured URL above a "Copy to Clipboard" button).  That way, you could easily load the captured URL into an external app.

Is that correct?

**Comment by doronbehar** [comment]
@Gitoffthelawn that would be super awesome, but I'm not aiming that far, I'm just wondering whether Redirector could be leveraged for a simple 'stop-reloading' kind of feature.

**Comment by einaregilsson** [comment]
Sorry, don't really think it can be used for stopping a redirect. This sounds more like something that could be solved with a 10 line custom extension. I just think it's too much of a niche thing to add as a general feature to Redirector. But what about this:

![Screenshot 2020-03-24 at 23 28 04](https://user-images.githubusercontent.com/557149/77486255-231b6800-6e27-11ea-98b5-0ba46d052d62.png)

Redirects to a nice little service that just prints out the url. Would that work for you?

**Comment by Gitoffthelawn** [comment]
@einaregilsson That's an interesting little service you found!  I don't see any privacy policy for it though.

I wonder if it would be relatively simple to add a simple `redirector://` psuedo-protocol that would accept a couple commands like `echo` (or `print` or whatever you want to call it) and `link` (to create a link).

Then users could redirect to `redirector://echo("Here is where you want to go: ")link($1)` :smiley:

**Comment by doronbehar** [comment]
> That's an interesting little service you found! I don't see any privacy policy for it though.

Here's the service's "about" page: https://github.com/izuzak/urlecho :).

> I just think it's too much of a niche thing to add as a general feature to Redirector.

Considering the creativeness of urlecho's idea, and how it can nicely be coupled with Redirector, I tend to agree. Thanks for finding that out @einaregilsson :). I'm using that now and I'm pretty satisfied. Feel free to close this, unless you'd consider @Gitoffthelawn's idea.

**Comment by einaregilsson** [comment]
Great, happy the workaround works for you. 🙂
