### ISSUE TITLE
[bug] [regression] Unreasonably restrictive rule editor checks

### ISSUE THREAD

**Issue by VitRom** [einaregilsson/Redirector#196]
Redirector 3.5.2 from AMO, Waterfox Classic 2020.03.1 (i.e. FF56.3+WE~58)

Impossible to set up any target protocol except http(s). In any of both (wildcard/regexp) modes. Editor dialog shows a red warning text and "Save" button is disabled.

**[regression]** The [example from #53](https://github.com/einaregilsson/Redirector/issues/53#issuecomment-220875217) doesn't work.

**[bug]** A bunch of protocols (telnet, ftp, tg for Telegram, moz-extension etc.) that understood by browser itself are unusable.

**[proposal]** Do not disable saving.

**Comment by einaregilsson** [comment]
I'll remove this restriction in the next version. Not sure when that will be though.

**Comment by VitRom** [comment]
10x, I'll wait with impatience. But with hope You'll just push out a kind of "hotfix" release.

**Comment by einaregilsson** [comment]
Looked into it and the changes had actually already been made by @Gitoffthelawn ! So I just bumped the version and published, if you're using Firefox you should be able to get 3.5.3 now. On Chrome it's pending review and they say it might take several business days.

**Comment by Gitoffthelawn** [comment]
Confirmed v3.5.3 now on AMO.  Confirmed changes work.
