### ISSUE TITLE
Please submit this extension to new Microsoft Edge too

### ISSUE THREAD

**Issue by John0King** [einaregilsson/Redirector#199]
People in China really need this extension, and  we can not access to almost any  google.com service.
the Firefox is the only one I can use now, but now I use new Edge in most time, I hope I can install this extension in Edge too. or there is a chrome extension I install manually

**Comment by einaregilsson** [comment]
I'll look into it the next time I make a release. But you can install the Chrome extension in the new Edge, see https://www.groovypost.com/howto/install-extensions-on-chromium-based-edge-on-windows-10/

**Comment by John0King** [comment]
I download the source code , and  be surprise that the source code can be install as the extension :P

> But you can install the Chrome extension in the new Edge

That is actually the biggest problem , People in China **can not access** almost any  google.com service including the extension store, the only service can be access is  https://www.google.cn/chrome/index.html  which is the URL for download chrome.

That is also why people in China need this plugin,  many website (including stackoverflow) use google's CDN for static assets  like `jquery.min.js` , so with this plugin I can redirect the google's CDN to microsoft asp.net CDN  or the jquery CDN

![image](https://user-images.githubusercontent.com/13639146/78215486-2f1fbd80-74ea-11ea-9d82-70057e18883c.png)

**Comment by einaregilsson** [comment]
I'll try to publish the next version on the Edge store :)

**Comment by John0King** [comment]
@einaregilsson  Do you have any trouble to publish this extension to Edge store ?   
today I use this extension with develop setting ,but  every time I open the edge, a warning popup show up, it's kind of annoying

**Comment by einaregilsson** [comment]
Just haven't gotten around to it yet.

**Comment by John0King** [comment]
https://microsoftedge.microsoft.com/addons/detail/redirector/jdhdjbcalnfbmfdpfggcogaegfcjdcfp 
@einaregilsson  is this the official publiish ?

**Comment by John0King** [comment]
@einaregilsson  thanks

**Comment by einaregilsson** [comment]
@John0King Yes, that's the offical version 🙂

**Comment by grahamperrin** [comment]
https://einaregilsson.com/redirector/#edge

![image](https://user-images.githubusercontent.com/192271/106607575-62dcd100-655b-11eb-8074-0bc54a00c5df.png)

👍
