### ISSUE TITLE
Redirector reportedly not working in multi-process Firefox

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#20]
According to a May 29, 2015 review on AMO by tzchen:
"Redirector not work on e10s,i use firefox 40a2 developer edition x64!"

I truly hope this isn't the end of Redirector and that someone can make it work!

**Comment by Phyxion** [comment]
Currently running Firefox 40 and it's not working anymore.

**Comment by Gitoffthelawn** [comment]
@Phyxion Firefox 40 is not multi-process!  ;)

So that's not the issue you are experiencing.  I tested Redirector on Firefox 40, and I did not find any new issues.  Try creating a new Firefox profile, and see if Redirector works as expected in it.  If not, you can create a new thread for your issue.

**Comment by Phyxion** [comment]
Ah, it stopped working here with Firefox 40 (64-bit) as none of my redirects are working. I'll check it out with a new profile.

**Comment by einaregilsson** [comment]
Redirector is upgraded to the new WebExtensions API in https://github.com/einaregilsson/Redirector/issues/30 and should continue working in multiprocess Firefox.
