### ISSUE TITLE
Sync option unchecked even when sync is enabled

### ISSUE THREAD

**Issue by FranklinYu** [einaregilsson/Redirector#201]
To reproduce, make sure that rules are few enough; I have only two short ones. Just check the “Enable Storage Sync” and see the notification “Sync is enabled!” now refresh the page. The checkbox become un-checked again.

Issue is at

https://github.com/einaregilsson/Redirector/blob/0772e5987336c3c469a8ec849ac3f54aab81bf33/js/redirectorpage.js#L46

It is checking `#storage-sync-option`, which is a label, not an `input`; see

https://github.com/einaregilsson/Redirector/blob/0772e5987336c3c469a8ec849ac3f54aab81bf33/redirector.html#L198

I guess simply appending `input` to the selector would work.

**Comment by einaregilsson** [comment]
Ah, you're right. I'll fix it for the next version, thanks!

**Comment by arrmo** [comment]
Same issue here - appreciate you fixing this, thanks! How to know when it is updated (Github is easy, but Chrome?).

**Comment by FranklinYu** [comment]
@arrmo I don’t think we have any notification for extension update. Best way so far is to check version daily after this issue is closed.

**Comment by arrmo** [comment]
No worries, completely understand. I'll keep an eye on this item - when it closes, then will check the extension (every few days).

Thanks!!

**Comment by arrmo** [comment]
Hi,

Not seeing this one "pushed" to a formal release - or am I just missing it? Would be helpful, just so sync status shows correctly.

Thanks!

**Comment by einaregilsson** [comment]
I just haven't made a release yet 🙂. I'll try to get one out soon.

**Comment by arrmo** [comment]
No worries, fully understand. Appreciate it!

**Comment by arrmo** [comment]
Sorry, just checking back in 😆. Thanks!!!

**Comment by arrmo** [comment]
Hi,

Looks like there is a PR to address this now?

Thanks!

**Comment by Gitoffthelawn** [comment]
@arro Yes, there is!

There are some things going on that have delayed pull requests being integrated.  Hopefully they can be integrated soon.

**Comment by arrmo** [comment]
Sounds great, thanks!

**Comment by g-a-c** [comment]
> There are some things going on that have delayed pull requests being integrated.

I'm curious, @Gitoffthelawn do you have access to merge PRs?

**Comment by Gitoffthelawn** [comment]
@g-a-c  Not at the moment, but we are working to make that happen.

**Comment by g-a-c** [comment]
Cool, I wasn't sure what a state this repository was in after the events of this year. There will need to be an issue addressed with the extension manifests, because this extension still uses manifest v2, and v2 will be phased out in Jan 2023. But I wasn't sure whether it was better to open an issue in here or to fork the project and take a look into fixing it myself. If it's possible for someone other than the original author to have merge permissions then addressing it here makes much more sense though to benefit everyone.

**Comment by Gitoffthelawn** [comment]
@g-a-c Sounds good. I was just going to create an issue regarding manifest v2 and v3, but I see you just created one: #316.  Thanks! Let's continue our discussion on manifests there.

**Comment by arrmo** [comment]
Hi,

Checking back in 😆. Any luck getting this one "pushed out"?

Thanks!

**Comment by arrmo** [comment]
Thanks! Does this need to be pushed, to show up in Google Chrome?

**Comment by Gitoffthelawn** [comment]
@armo You're welcome!

Yes, I'm just waiting for full access so we can proceed.

Please see https://github.com/einaregilsson/Redirector/issues/329 and https://github.com/Gitoffthelawn/Contact-Gitoffthelawn/issues/8.
