### ISSUE TITLE
Redirects are Unreliable

### ISSUE THREAD

**Issue by hl2guide** [einaregilsson/Redirector#205]
For me rules only actually redirect 30% of the time, it's weird.

_A rule I created:_

imagecurl.com
Redirect:	https://imagecurl.com/viewer.php?file=*.jpg
to:	https://cdn.imagecurl.com/images/$1.jpg
Example:	https://imagecurl.com/viewer.php?file=46117141609594652108.png → https://cdn.imagecurl.com/images/46117141609594652108.png
Applies to:	Main window (address bar)

I'm using version 3.5.3.

**Comment by einaregilsson** [comment]
Can you give me an example of an url where the redirect didn't work?

**Comment by Gitoffthelawn** [comment]
What OS and browser?  What version of each?

**Comment by hl2guide** [comment]
Browser: Vivaldi 2.11.1811.52 (Stable channel) (64-bit)
OS: Windows 10 OS Version 1909 (Build 18363.778)
Example URL: https://imagecurl.com/viewer.php?file=46117141609594652108.png

**Comment by einaregilsson** [comment]
Your include pattern ends with *.jpg but your example url ends with .png.

**Comment by hl2guide** [comment]
I'll test that out.

**Comment by hl2guide** [comment]
Even after fixing it to:

imagecurl.com
Redirect:	https://imagecurl.com/viewer.php?file=*.*
to:	https://cdn.imagecurl.com/images/$1.$2

I get the first page load not redirecting, it requires me to refresh the page to actually redirect properly.

**Comment by einaregilsson** [comment]
Ok, so if there's a link to that url somewhere, you click the link then it doesn't redirect, only after you're on the page and press refresh? But this doesn't happen every time?

**Comment by mpfaff** [comment]
I'm noticing the same behaviour, except it happens every time for me.
