### ISSUE TITLE
Conditional Rule

### ISSUE THREAD

**Issue by jflattery** [einaregilsson/Redirector#209]
I have two seperate rules for zoom meeting links and I'm wondering if there is a way to combilne them into one. 

```
Zoom Meeting (Start)
   Redirect: (?:http[s]?:\/\/)?([\w]+.)?zoom.us\/s\/(.*)$
   to: https://$1zoom.us/wc/start/$2
```
and 
```
Zoom Meeting (Join)
   Redirect: (?:http[s]?:\/\/)?([\w]+.)?zoom.us\/j\/(.*)$
   to: https://$1zoom.us/wc/join/$2
```

So I guess my question is, is there a way to make a capture group for (j|s) and if the capture group is **j** than replace with **join** and if **s** than replace with **start**?

**Comment by einaregilsson** [comment]
No, I don't think you can really do that. You can't really put two different things in the redirect url unless it's somewhere in the original url.
