### ISSUE TITLE
[Question] Is there a way to perform Search and Replace on the URL?

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#21]
Using Redirector, is there a way to perform a Search and Replace on the URL?

For example, let's say the user wants to replace all occurrences of the string 'no' to 'yes'.

i.e.:
Redirect `http://example.com/no-no-abc-no-def-no`
to: `http://example.com/yes-yes-abc-yes-def-yes`

**Comment by einaregilsson** [comment]
No, that's not possible for an arbitrary amount of "no", if you know the number you can hardcode a pattern for it, but no way to do generic search-replace.

**Comment by Gitoffthelawn** [comment]
Thanks for you reply!

If you know there will be 1-5 occurrences, is it possible, or do you need to know the exact number ahead of time (e.g. exactly 4).

**Comment by einaregilsson** [comment]
You could probably do 1-5 by having lots of optional ? captures, but it would be an ugly and complex pattern. Why, is there a specific case you're thinking of?

**Comment by Gitoffthelawn** [comment]
Thanks.  The specific case is to be able to convert all CR/LF sequences (%0D%0A) to commas.

If more details help, I'm happy to provide them.
