### ISSUE TITLE
Using $ doesn't work past 10

### ISSUE THREAD

**Issue by Cybo1927** [einaregilsson/Redirector#210]
It sees $11 as $1 with an extra 1 at the end of its original value

I found this while messing around with it and trying to rewrite Google Video URLs

![image](https://user-images.githubusercontent.com/39284087/85935202-aa242480-b8dd-11ea-93ea-3de6d2d2c0fc.png)

**Comment by monoblaine** [comment]
My two cents:

https://github.com/einaregilsson/Redirector/blob/23c9814df907e595c8d8f3bfd31d47fa599d6f8e/js/redirect.js#L273-L288

If this loop is executed in the reverse order this problem will be fixed.
