### ISSUE TITLE
https:// -> file:// not working

### ISSUE THREAD

**Issue by Derek-Jones** [einaregilsson/Redirector#213]
I have created a pattern to redirect from source on Github to a local copy.

None of the examples involve mapping a http request to a file request.  Is this functionality available?

The redirect is as follows:

```
Access local ESEUR pages
Redirect: https://github.com/Derek-Jones/ESEUR-code-data/blob/master/*
to: file:///home/derek/ESEUR-code-data/$1
Example:https://github.com/Derek-Jones/ESEUR-code-data/blob/master/group-compare/SW-check.R →
file:///home/derek/ESEUR-code-data/group-compare/SW-check.R
Applies to: Main window (address bar)
```

**Comment by einaregilsson** [comment]
No, sorry, that functionality is not available. The API we use to handle redirects doesn't support it.

**Comment by Derek-Jones** [comment]
Ok, thanks.

A shame, it would have been so neat.
