### ISSUE TITLE
Set up notifications for rules individually ❓

### ISSUE THREAD

**Issue by dnknn** [einaregilsson/Redirector#216]
👆It can be realized: e.g.&ensp; **global** ☑🔔 by **default**,
### **However**, there are **individual** Redirect-rules that do not require 🔔(🔕) at all.

in other words: 
## can be set 🔔/🔕 separately instead of following `global 🔔/🔕 by default`

&ensp;
see 👇

![Pic-200724_217](https://user-images.githubusercontent.com/10995302/88322928-0438ce00-cd54-11ea-8781-19ea23927bfc.png)

**Comment by einaregilsson** [comment]
Thanks for the suggestion. I'm not really adding new features to Redirector for now, but I'll keep this in mind if I ever start working on it again.

**Comment by dnknn** [comment]
Thank you for your reply. It is useful to notify separately,
Because not every redirect requires notification, but not all are not notified.
