### ISSUE TITLE
[Question] Which is faster, regex or wildcards?

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#22]
For Redirector, which is faster, regex or wildcard redirects?

**Comment by Gitoffthelawn** [comment]
From reading the code, it looks like Redirector converts all wildcard redirects to regex, so regex would be a touch faster because it doesn't have to perform the conversion.

@einaregilsson Does Redirector perform that conversion (1) only once when the rule is created, (2) only every time Firefox is started, (3) every time a URL is requested by the browser, or (4) something else?

**Comment by einaregilsson** [comment]
The conversion from wildcards to regex is trivial. The wildcard regular expressions are pretty simple as far as regular expressions go so they should be fast. But it's always possible to manually create a really complex regular expression that might not perform well. But given that the strings we're matching, urls, are relatively short none of this should matter. I haven't heard that performance has been an issue at least.

As for the conversion, it's done when Firefox is starting up, and when a new rules is created. In the Redirector.rjson file the patterns are stored as the user entered them, so on startup they have to be converted again.

**Comment by Gitoffthelawn** [comment]
Thanks Einar, for the description of when the conversion from wildcard to regex is performed.

I noticed that the code converts `*` to `(.*?)`.  Why the question mark after the asterisk?  In what cases is the greediness of the question mark needed (I assume that's why you included it).  I converted a bunch of wildcards to regex, but didn't find any that needed a question mark... but perhaps you can provide some examples where it is needed.

**Comment by einaregilsson** [comment]
I could probably have used both. I just thought it seemed natural to let the * match as little as possible. In 99% of cases it won't change anything.

**Comment by Gitoffthelawn** [comment]
Thanks.  What does `(.*?)` match that `(.*)` doesn't?
