### ISSUE TITLE
Request to increase UrlEncode Conversion/Redirect ❓

### ISSUE THREAD

**Issue by dnknn** [einaregilsson/Redirector#221]
Most most  web pages are `UTF-8` encoded pages, this is no problem. But also have some 👇
![207_31105338](https://user-images.githubusercontent.com/10995302/88994975-22866700-d31c-11ea-9ebd-1ef76fe7eee2.png)

#### In other words, this character part will be displayed as garbled.👇
![207_31111711](https://user-images.githubusercontent.com/10995302/88996274-67f86380-d31f-11ea-8219-d435399ed1f0.png)

---
# So, can `UrlEncode` Conversion/Redirect be supported ❓
#### `https://⋯⋯.com/search.php?mod=for&search=%d6%d0%ce%c4`

![207_31111156](https://user-images.githubusercontent.com/10995302/88995996-a7728000-d31e-11ea-9eed-fba0da05a151.png)

-----
Related examples, 👇 because it can `UrlEncode` Conversion/Redirect
Selection Search https://chrome.google.com/webstore/detail/gipnlpdeieaidmmeaichnddnmjmcakoe
https://github.com/Pitmairen/selection-search
![207_31112203](https://user-images.githubusercontent.com/10995302/88996538-13a1b380-d320-11ea-9c6b-13c7e11cc2b2.png)

search2   https://chrome.google.com/webstore/detail/godjlopkhiadfppdjhbekbppchinkmpi
https://github.com/wurenny/search2
![207_31113635](https://user-images.githubusercontent.com/10995302/88997369-18676700-d322-11ea-8776-67f9d59b0694.png)

![207_31114137](https://user-images.githubusercontent.com/10995302/88997686-cffc7900-d322-11ea-965e-89ee508643e7.png)

**Comment by einaregilsson** [comment]
If this issue gets enough upvotes I'll consider this. Sorry, but I have to prioritize what I work on :)

**Comment by dnknn** [comment]
Yes, I can understand.Thanks again for your reply.
