### ISSUE TITLE
Chromium: blurry "Create Redirect" menu

### ISSUE THREAD

**Issue by ueberchild** [einaregilsson/Redirector#222]
When the extension page doesn't fit the whole window (there's 2+ rules or 3+ rules in fullscreen), the menu font gets blurry.  
Blur goes away after clicking "Show advanced options..."
Expected behaviour (Firefox):
![Screenshot from 2020-07-31 09-30-40](https://user-images.githubusercontent.com/51470390/89007424-645de000-d311-11ea-9cc5-345832329709.png)
Ungoogled Chromium behaviour (feels like astigmatism):
![Screenshot from 2020-07-31 09-31-21](https://user-images.githubusercontent.com/51470390/89007428-6627a380-d311-11ea-880b-fe97f57b2678.png)
After clicking "Show advanced options...":
![Screenshot from 2020-07-31 09-40-24](https://user-images.githubusercontent.com/51470390/89007675-e0f0be80-d311-11ea-98f0-18134b5fda0e.png)

**Comment by einaregilsson** [comment]
Hmm. Which operating system?

**Comment by ueberchild** [comment]
Debian stable; Ungoogled Chromium taken from [OBS](https://software.opensuse.org/download/package?package=ungoogled-chromium&project=home:ungoogled_chromium)
And when tested on Devuan Beowulf VM, only a part is blurred:
![](https://user-images.githubusercontent.com/51470390/89550223-06019780-d812-11ea-8a6c-29b9befe19fa.png)
When tested on Android 6.0.1 (UC taken from [F-Droid repo](https://uc.droidware.info/fdroid.html)): no blurring, but starting from 4 rule header looks really big (redirecting works though).
<img src="https://user-images.githubusercontent.com/51470390/89550802-c7b8a800-d812-11ea-91b2-0db5e48db05e.png" width=30% height=30% />

**Comment by Gitoffthelawn** [comment]
Is this still an issue?
