### ISSUE TITLE
🍸Can support lazy-matching  of RegExp❓

### ISSUE THREAD

**Issue by dnknn** [einaregilsson/Redirector#223]
![208_07071029](https://user-images.githubusercontent.com/10995302/89591574-1ac74500-d87d-11ea-8be9-a70b29759e47.png)

- ## 💥Current issues:  Can not lazy-matching  of RegExp, like　　 `.*?`

Current, `Redirector` is ignore the `?` of `.*?` in the `RegExp`.
So not flexible enough, it is difficult to achieve accurate matching, and it is easy to have wrong killing (overmatching).

Normally, for most URL matching patterns, all support `.*?` /`.+?`  of RegExp

- ## ❥ Expected behavior:   do not ignore the `?`  in `.*?` in the `RegExp`.
Please support it,  For details, see at: 　　 https://regex101.com/r/YXD65w/3
![208_07055705](https://user-images.githubusercontent.com/10995302/89586731-d46ce880-d872-11ea-83c8-ad58f2163213.png)

**Comment by GitSparTV** [comment]
# 👋👋 Hi, 🅳🅽🅺🅽🅽 🤓💼🤝🙂

❗ **Your `issue` doesn't have enough emojis** 😲😲😲
🚨This is not enough for a request. 🔍👮🔦 🛑🚧

# **💞But don't worry 🚁😇👌! !**

***I fixed 🛠 your `request` to make it more 🆄🅽🅳🅴🆁🆂🆃🅰🅽🅳🅰🅱🅻🅴😄🤘***

# Check it 👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇
![image](https://user-images.githubusercontent.com/5685050/94999414-f5775e80-05c1-11eb-9e66-d8ca4b3c4851.png)
Haha, you missed it 🤣🤣🤣, it's ☝☝☝☝☝☝☝☝☝☝☝☝☝☝☝☝

**Comment by MyNameIsTimb** [comment]
i have herpes

**Comment by dnknn** [comment]
Haha, this is crazy.....

**Comment by nedarta** [comment]
I need autism asap.

**Comment by powerprompt** [comment]
Not enough, add more emojis.

**Comment by powerprompt** [comment]
crispy jpeg time

![deepfried_1601867941307](https://user-images.githubusercontent.com/62524115/95037141-a26bdd00-068f-11eb-9cf8-cc101dcec7b1.png)

**Comment by graingert** [comment]
a JPEG is not a very efficient format, I've created a vector version to support resizing on different screents

![image](https://gist.githubusercontent.com/graingert/d60e18edb980e517bb5307c2a7d1701c/raw/9081c457d542c4e8fe39d3acdcca2792ba137b17/regex-issue.svg)

can I get a t-shirt now?

**Comment by Nefomemes** [comment]
> a JPEG is not a very efficient format, I've created a vector version to support resizing on different screents
> 
> ![image](https://gist.githubusercontent.com/graingert/d60e18edb980e517bb5307c2a7d1701c/raw/9081c457d542c4e8fe39d3acdcca2792ba137b17/regex-issue.svg)
> 
> can I get a t-shirt now?

Congratulations! Here's your [t-shirt](https://twitter.com/shitoberfest/status/1313051065994997761?s=20).

**Comment by devenblake** [comment]
how do i use emiji i wanna b cool like the people who spam open source projects with PRs 

pls halp

**Comment by Nefomemes** [comment]
GitHub - Social Media for Developers

**Comment by codenoid** [comment]
COME HERE TO LAUGH 😂😂😂👌👌👌

**Comment by configurator** [comment]
You misunderstand something about lazy matching of regexes - even if `?` isn't ignored, processing will not stop on the first `foo` it finds, it will stop on the first thing which matches the entire pattern, including the `$`.

The regex `(. *)foo$`, for example, WILL match a string like `afoobfoo`; after trying `a` for the first group and failing to match the regex, it will try `afoob` and succeed in matching the entire regex.

Hope this helps.

**Comment by dnknn** [comment]
Hi~ @configurator ! It is indeed my fault, thank you very much, I understand this new knowledge of regularity. Thanks again



![2010_05190208](https://user-images.githubusercontent.com/10995302/95072118-4eb7cd00-073d-11eb-85c3-fccc02c8202b.png)
https://regex101.com/r/aaYv3j/1
