### ISSUE TITLE
embedded videos don't work when ublock is enabled

### ISSUE THREAD

**Issue by crabtreee** [einaregilsson/Redirector#225]
I cannot force redirector to work with embedded videos. When I disable ublock everything is OK. Should I whitelist or change something?

**Comment by atomGit** [comment]
a couple tips for submitting a proper bug report...

1. PROVIDE EXAMPLES (links, screen-caps, etc.)
2. what "don't work"? DESCRIBE THE PROBLEM in relevant detail
3. what uBlock setting/filter/list is interfering? you can troubleshoot this yourself

**Comment by Gitoffthelawn** [comment]
Is this still an issue?

Closing for now.  If this is still an issue, please provide additional details.  Thanks!
