### ISSUE TITLE
[Help] A universal redirection for Google's CSE

### ISSUE THREAD

**Issue by ghost** [einaregilsson/Redirector#228]
Hi,

I'm running flawlessly _Redirector_ 3.5.3 / _Firefox_ 79.0 with several redirections, all written the easy way (regular Expression).
I'm currently searching for a redirection scheme which could apply to all sites performing their search via Google's CSE.

I managed to create a specific rule for majorgeeks which redirects its CSE searches to DuckDuckGo (as an example):

```
Example URL: https://www.majorgeeks.com/content/page/mg_search.html?DATA1&q=TEST&DATA2
Include pattern: https://www.majorgeeks.com/content/page/mg_search.html?*&q=*&*
Redirect to: https://duckduckgo.com/?q=site:majorgeeks.com+$2
Pattern type: Regular Expression
```
I simplified here the example URL's long in-betweens with DATA1 and DATA2.
This rule works perfectly, but I'd love to know a rule which could apply to any site using Google's CSE, even if I'm not even sure this is feasible given i'm not sure all sites address Google's CSE with the same pattern.

Thanks for your help/advice.

**Comment by einaregilsson** [comment]
That looks like a wildcard, not regular expression. Are you sure you have it set to regex?

You could do something like:

Include pattern: `https?://(www\.)?([a-z0-9.])/.*/page/mg_search.html\?.*?&q=(.*)`
Redirect to: `https://duckduckgo.com/?q=site:$1+$2`

Something like that :)

**Comment by Cade66** [comment]
_Wildcard_ indeed, sorry. I must correct as well my statement about writing rules the _easy way_ when that means with _wildcards_, not with _regular expressions_ (I reversed).
Regular expressions is unfortunately not my friend.

A new rule, Regex, with your pattern and redirect when applied to `Example URL: https://www.majorgeeks.com/content/page/mg_search.html?DATA1&q=TEST&DATA2` unfortunately shows `Example Result: The include pattern does not match the example url.`

![CSE2DDGjpg](https://user-images.githubusercontent.com/65161029/90621284-cd02f300-e213-11ea-8c81-c6da11101893.jpg)


I have to deliver this to you in a very assisted way given I'm totally blind to regex construction...
Thanks again!

**Comment by einaregilsson** [comment]
![Screenshot 2020-08-19 at 10 13 22](https://user-images.githubusercontent.com/557149/90622466-a38e9b00-e204-11ea-88ab-a3d29b84508e.png)

Something like this works for the example but not sure if it would work for all cases of "is there DATA before the &q", "is there data after the q=" etc etc. Also, not sure if you want the www. included in the redirect pattern, the way it's set up it will remove any www.

**Comment by Cade66** [comment]
OK for
```
Include pattern: https?://(www\.)?([^/]*)/.*/page/mg_search.html\?.*?&q=([^&]*)
Redirect to: https://duckduckgo.com/?q=site:$2+$3
```

> Something like this works for the example but not sure if it would work for all cases of "is there DATA before the &q", "is there data after the q=" etc etc

I get it, I'll keep that in mind when encountering Google CSE on other sites than majorgeeks. Not many sites refer to Google CSE but when they do it's bothering (I block `cse.google.com `system-wide)

> Also, not sure if you want the www. included in the redirect pattern, the way it's set up it will remove any www.

Not necessary for entire domain search which is what I use the most. Of course if a page such as one.example.com called Google CSE for a search on its subdomain it could be a slight handicap depending on the site's volume, i.e.reddit (which doesn't use Google's CSE anyway).

Thanks. I'll use this new Google CSE to DDG in place of my former rule restricted to magorgeeks and see how things get along.
Side-note : I admire those of us who get to understand Regular Expressions, I mean I _really_ do!

**Comment by einaregilsson** [comment]
> : I admire those of us who get to understand Regular Expressions, I mean I really do!

No one understands regex, we just mess around till it kinda works ;)
