### ISSUE TITLE
Bug with Chrome inspector after Chrome update

### ISSUE THREAD

**Issue by samazko** [einaregilsson/Redirector#229]
## Bug with Chrome inspector after Chrome update

Hi,

I'm using Redirector extension for Chrome for almost two years and everything was working fine until last Chrome update, but I have now an issue with Chrome inspector when Redirector is `on` (enabled) : 
- **css properties just "disappear" from the inspector when one is unchecked** : 
  ![image](https://user-images.githubusercontent.com/33315914/92224167-ba3e1e80-eea1-11ea-99b7-4b7194829110.png)

  for instance if I uncheck `text-align` property it just disappears from the list, and I loose the reference to the stylesheet and the line of it.
This behaviour _only_ concerns stylesheets that have been _redirected_ by Redirector.

- **the redirected stylesheets are _minified_ in the inspector** (not always, but often after unchecking a css property).

I find it a very strange issue and I don't know how and why it concerns Redirector extension, but when the Redirector is `off`, there's no more problems like described above.

### Chrome version

If you'd like to reproduce the bug, here is the version : 
- Chrome : 85.0.4183.83 (Build officiel) (64 bits)
- Redirector : 3.5.3

I had no problem with last Chrome version : 
- Chrome: 84.0.4147.135 (Build officiel) (64 bits)
- Redirector : 3.5.3

Thanks for your help/advice :slightly_smiling_face:

**Comment by einaregilsson** [comment]
Sounds like the Chrome inspector uses some request mechanism that doesn't go through Redirector, so it doesn't find the stylesheet that was redirected. Sorry, I don't think that's gonna be something that can be fixed in Redirector itself.

**Comment by samazko** [comment]
Thanks @einaregilsson for your answer.

Since I found no solution (same problem with Chrome beta versions), I have opened an issue in Chrome bugs tracker : 
https://bugs.chromium.org/p/chromium/issues/detail?id=1128360 

I'll update this issue if any solution is provided :)

**Comment by einaregilsson** [comment]
Nice, that sounds like a good idea :)

**Comment by samazko** [comment]
For anyone facing the same problem, the Chromium team has solved the linked issue : 
https://bugs.chromium.org/p/chromium/issues/detail?id=1128360#c8 

I have tried it on Chrome dev version (87.0.4270.0) and it now works perfectly as before 🎉 
https://www.google.com/chrome/canary/ 

Thanks again @einaregilsson for this very useful extension :)

**Comment by einaregilsson** [comment]
They fixed it? Great! :)
