### ISSUE TITLE
[Bug] When a rule is disabled, test will always fail

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#23]
When a Redirector rule is disabled, the associated 'Test' button will always result in a fail, even if the test string matches the rule.

**Comment by einaregilsson** [comment]
Will try to clean this up whenever I next get around to doing any work on Redirector, should be trivial to fix.

**Comment by Gitoffthelawn** [comment]
Sounds great!  Thanks!

**Comment by einaregilsson** [comment]
Fixed in https://github.com/einaregilsson/Redirector/issues/30
