### ISSUE TITLE
the old.reddit.com sample rule breaks galleries

### ISSUE THREAD

**Issue by 07416** [einaregilsson/Redirector#233]
https://github.com/einaregilsson/Redirector#old-reddit

[Reddit announcement](https://www.reddit.com/r/announcements/comments/hrrh23/now_you_can_make_posts_with_multiple_images/)

[example gallery](https://www.reddit.com/gallery/hrrh23), loads an error page when being redirected to `https://old.reddit.com/gallery/hrrh23`

**Comment by ariel-co** [comment]
Galleries don't seem to work in old Reddit. Either:

* use an Exclude pattern like `^(?:https?://)(?:www)?\.reddit\.com/gallery`, or 
* insert a negative lookahead in the Include regex: `^(?:https?://)(?:www)?\.reddit\.com(?!/gallery/)(/.*)`

**Comment by einaregilsson** [comment]
Ok, I've removed the example. It was contributed by someone else, I'm not familiar with how it should work.
