### ISSUE TITLE
[Question] - Quora redirection with ?share=1

### ISSUE THREAD

**Issue by shivasagarrao** [einaregilsson/Redirector#234]
To redirect any quora link such that ?share=1 is added the end of every a Quora link, I wrote following rule
Include pattern: https://www.quora.com/*
Redirect to: https://www.quora.com/$1?share=1

With the above rule I have following issue, 
When URL is https://www.quora.com/How-do-I-read-more-books?share=1 it is redirecting to https://www.quora.com/How-do-I-read-more-books?share=1?share=1

How to write a rule such that, 
Case 1: When there is no ?share=1 at the end of URL it should redirect to URL with ?share=1. 
Example: https://www.quora.com/How-do-I-read-more-books should be redirected to https://www.quora.com/How-do-I-read-more-books?share=1 

Case 2:  When there is ?share=1 at the end of URL it should be redirected to same URL.
Example: https://www.quora.com/How-do-I-read-more-books?share=1 should be redirected to https://www.quora.com/How-do-I-read-more-books?share=1 

For people who don't know regarding ?share=1: Adding ?share=1 at the end of Quora URL helps in removing annoying popup of signin/signup.

**Comment by einaregilsson** [comment]
Hi.

You add an exclude pattern like: `https://quora.com/*share=1` . Then any links that already have share=1 will be excluded from the redirect.

best regards,
Einar

**Comment by shivasagarrao** [comment]
Thanks @einaregilsson. It's working perfectly as per my requirement.
