### ISSUE TITLE
[bug] Limitation due to Manifest V3 starting from Chromium 88?

### ISSUE THREAD

**Issue by walrus543** [einaregilsson/Redirector#239]
Hello,
I use Vivaldi Stable and Snapshot on my computers.
Boh have the same version of Redirector. However its behaviour is not the same.

As discussed in the [forum of Vivaldi](https://forum.vivaldi.net/topic/54575/redirector-extension-with-vivaldi-snapshot/3), the Snapshot version is based on Chromium 88.

I have to reload the web page to get the redirection.
Do you also think that it's caused by this new version of Chromium? Is there a solution?
Thank you.

EDIT 18/12/2020: Thanks to @Gwen-Dragon (Moderator on Vivaldi's forum) the bug is confirmed and also present on Chromium 87 (so not related to Manifest V3).

**Comment by Gitoffthelawn** [comment]
Is this still an issue?  If not, I would like to close this issue report.  Thanks!

**Comment by walrus543** [comment]
I no longer use Vivaldi. I guess we can close. Other users will open a new issue if they need.
