### ISSUE TITLE
[Bugs] Should we report them?

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#24]
Hi Einar.  I've found a few more bugs... nothing critical, but one that can cause a rule to be disabled.

Since you're not officially working on Redirector, yet are very generous with your time by keeping it updated, would you like me to post the bugs here.

No expectations on my end that they will get fixed... but since it takes time to post bugs, I want to confirm that posting them is welcomed and a reasonable use of my time.

**Comment by einaregilsson** [comment]
Posting them is fine, but is it a good use of your time? Probably not, since I probably won't fix them. But it does open the possibility that other people will fix them.

**Comment by Gitoffthelawn** [comment]
Sounds good... I'll post them if time permits.

**Comment by einaregilsson** [comment]
Bugs for https://github.com/einaregilsson/Redirector/issues/30 are welcome :)
