### ISSUE TITLE
redirect isn't applied even though example works

### ISSUE THREAD

**Issue by gingerlime** [einaregilsson/Redirector#243]
Thanks for Redirector! It's super-useful.

I'm trying to set up a rule to avoid some link trackers, but I'm having trouble at the moment... 

![CleanShot 2020-12-30 at 09 35 06](https://user-images.githubusercontent.com/524274/103339688-54922580-4a82-11eb-921c-3e561a23fe16.png)

I'm setting a rule for urls that look like `https://click.pstmrk.it/2m/some.website.com%2Freceipt%2F18214770-83948221%2F6831526A-chre7e04233afa4-47c230da48/y0tPIA8/7cQ/OSfrX-hTZo/aW50cm9fcmVjZWlwdB` or `https://click.pstmrk.it/2sm/www.website.com%2Fsubscription%2Fmanage%3Fuser%3D93849211%26subscription%3D462AC50%26hash%3Da2fa5866357ef4db77278726ce006ff4f32ce213ba5efdc14fb8ac6127e06fe4/zEtPIA8/7cQ/Rzw1Nm5KhQ/aW50cm9fcmVjZWlwdA`

The rule / example seem to work, but somehow when I visit the page, it doesn't redirect...

![CleanShot 2020-12-30 at 09 36 38](https://user-images.githubusercontent.com/524274/103339800-b2267200-4a82-11eb-891a-c7ed3bd77705.png)

Any tips / clues ?

EDIT: I'm using the Firefox extension with Firefox 84.0.1 on MacOS Mojave

**Comment by einaregilsson** [comment]
Try making the redirect url a full url, including the http/https. E.g. try `Redirect to: https://$2`.

**Comment by gingerlime** [comment]
Thanks @einaregilsson ! This seems to work. 👍
