### ISSUE TITLE
De-localise link(s) to AMO

### ISSUE THREAD

**Issue by grahamperrin** [einaregilsson/Redirector#249]
Hi

The link at https://einaregilsson.com/redirector/#firefox

* refers to https://addons.mozilla.org/en-US/firefox/addon/5064
* could better refer to https://addons.mozilla.org/addon/redirector/

Thanks

**Comment by Gitoffthelawn** [comment]
This is now fixed.  Thank you for the report.

**Comment by grahamperrin** [comment]
Likewise, thank you.
