### ISSUE TITLE
Redirector does not redirect AJAX queries inside my page

### ISSUE THREAD

**Issue by socomajor** [einaregilsson/Redirector#25]
Hello !

I'd like to use redirector to redirect some AJAX calls into my page.
It seems Redirector does not see those requests but only the requests I make using the browsing bar of firefox. 

I don't know anything about Firefox Addon programming, but I repport that in hope some devlopper would be interrested.

Cheers !

**Comment by einaregilsson** [comment]
The way that Redirector is built makes it impossible to redirect AJAX requests without a total rewrite of the redirection mechanism. Since I don't actively work on Redirector anymore this issue will never be fixed by me, but others are welcome to contribute.

**Comment by einaregilsson** [comment]
Fixed in https://github.com/einaregilsson/Redirector/issues/30
