### ISSUE TITLE
youtube wildcard works for video links, but not home page url (youtube.com)

### ISSUE THREAD

**Issue by AndoOfTheWoods** [einaregilsson/Redirector#250]
So I've made a few simple wildcard reditrect rules, which all work as intended. However, the youtube rule I made seems to only work on youtube pages that have parameters (videos), or subpaths (e.g. channels) in the url. The home page "youtube.com" is not redirected.

The setups I have tried are as follows:

![image](https://user-images.githubusercontent.com/9784578/106915257-eb28c500-6759-11eb-85f5-3b670362a26e.png)
![image](https://user-images.githubusercontent.com/9784578/106915300-f7148700-6759-11eb-9fc2-f0be880afe8b.png)

Is there anything I'm missing?

**Comment by AndoOfTheWoods** [comment]
I've found a temporary solution, but I have a hunch youtube suppresses redirects on the home page guessing from the number of search results that show malware redirecting people to dubious websites from youtube.

**Comment by einaregilsson** [comment]
Weird, because I see if I log the redirects that Redirector is trying to redirect the homepage but it's just not happening for some reason!

**Comment by einaregilsson** [comment]
Ok, it does work in Firefox which may mean that Chrome just blocks this for malware reasons like you suggested.

**Comment by AndoOfTheWoods** [comment]
Ah that's interesting! Thanks for letting me know.
