### ISSUE TITLE
The 'de-mobilizer' rule breaks some URLs containing dots

### ISSUE THREAD

**Issue by 07416** [einaregilsson/Redirector#255]
https://github.com/einaregilsson/Redirector#de-mobilizer

> `^(https?://)(.*\.)m(?:obile)?\.(.*)`

For instance, the page `https://en.wikipedia.org/wiki/R.A.M.O.N.E.S.` gets redirected to `https://en.wikipedia.org/wiki/R.A.O.N.E.S.`

**Comment by einaregilsson** [comment]
Ok, have changed the include pattern to `^(https?://)([a-z0-9-]*\.)m(?:obile)?\.(.*)` instead. Although I generally am not a fan of patterns this broad, I'd probably make as seperate mobile rule for each website I wanted to redirect. Rules this broad are bound to run into issues in some cases, this example was contributed by someone else.

**Comment by 07416** [comment]
>I'd probably make as seperate mobile rule for each website I wanted to redirect. Rules this broad are bound to run into issues in some cases, this example was contributed by someone else.

Sure, of major websites which use the mobi URL I can only recall Youtube and [Wikimedia websites](https://meta.m.wikimedia.org/wiki/Complete_list_of_Wikimedia_projects) (+ maybe Mediawiki wikis in general).

**Comment by rmlrml** [comment]
mind if I necro-ask, what would be the rule for a wikipedia "mobilizer" redirect, to go from desktop version to mobile?
