### ISSUE TITLE
[Query] Can this extension be used to bypass ad links?

### ISSUE THREAD

**Issue by blazesprings** [einaregilsson/Redirector#257]
Dear developer/users

Please let me know if this extension can be used to bypass ad links?

**Comment by einaregilsson** [comment]
Depends on what kind of ad links you mean. Do you have an example?

**Comment by blazesprings** [comment]
Yes i do have. Here's the link : https://go.leechpremium.link/shrtfly/?id=3040ceb21c11b1616411777
This domian appears 2-3 times till user finally gets download link and every time there's a timer of 10 secs. 
I need to bypass this domain. Is there any way to do it? Thanks btw for your reply :)

**Comment by einaregilsson** [comment]
Sorry, no, that url has no information about what the actual destination is, so I can't redirect from it to the correct destination. Unless the url you ultimately end up at has the id 3040ceb21c11b1616411777 in it somewhere?
