### ISSUE TITLE
Can I redirect some HTTP Post requests to my local web server?

### ISSUE THREAD

**Issue by zydjohnHotmail** [einaregilsson/Redirector#258]
Hello:
I setup a local http server, it is listening on port 8000.
I want to know if I can use your extension to redirect some HTTP post requests to my local web server.
http://localhost:8000/
I can't find any useful information.
I can use webRequest.onBeforeRequest.addListener to show the URLs for HTTP requests, but I have no idea how I can redirect the underlying HTTP requests to my local web server.
Please advise!

**Comment by einaregilsson** [comment]
The extension only handles GET requests. You could easily modify the extension to support POST as well, but the reason for not supporting it is that POST is used for a lot of sensitive information, passwords and things like that, and a simple  misconfiguration of a rule could end up with you sending your sensitive information to the wrong website.

**Comment by Gitoffthelawn** [comment]
If anyone decides to add POST functionality, I am willing to perform some testing of that feature.  If you do, I think it's best to make it an option that is disabled by default, because as Einar mentioned, POSTs are more likely than GETs to be an issue if accidentally triggered.

**Comment by andreasonny83** [comment]
I just opened a PR to allow redirects to be applied to POST requests as well: https://github.com/einaregilsson/Redirector/pull/408
