### ISSUE TITLE
How to redirect a non HTTP protocol link to HTTPs?

### ISSUE THREAD

**Issue by babeslooker** [einaregilsson/Redirector#263]
I want to redirect a **non HTTP protocol** link to HTTPs. For example, redirect `tg://resolve?domain=kavitabhabhi3` → `https://web.telegram.org/#/im?p=@kavitabhabhi3` but web browser always ask me to open this link in Telegram app rather than open it directly.

Can this extension redirect a non HTTP protocol link to a normal HTTPs? Are there other ways or extensions to do this kind of redirect? Any suggestions will be highly appreciated. Thanks in advance!

**Comment by einaregilsson** [comment]
Sorry, the browser API we use to redirect only forwards http and https requests to us, we can't redirect other protocols.
