### ISSUE TITLE
Redirector ins't working with Firefox 39

### ISSUE THREAD

**Issue by BostAxola** [einaregilsson/Redirector#27]
I recently discovered that Redirctor does not work with the latest Firefox stable version. My "redirects" have been deleted and I can't create new ones. I have tried reinstalling it, with no luck.

Thanks for your job Eina.

**Comment by Gitoffthelawn** [comment]
I can successfully use Redirector with the same version.

First try deleting redirector.rjson in your profile folder to see if that fixes the issue.

If it doesn't, I recommend creating a new Firefox profile and installing Redirector in that fresh profile.  If it works, try adding your other extensions in one at a time.

I'm guessing you have an extension conflict, problems in the prefs.js file within your profile, or a corrupt redirector.rjson.

**Comment by BostAxola** [comment]
Thank you. Deleting the redirector.rjson  did the trick.

**Comment by Gitoffthelawn** [comment]
It's not a solution, but as a workaround, can you view redirects.json in a text editor and manually extract the data?

**Comment by StephenBrown2** [comment]
I can view redirector.rjson (maybe that's the file you meant) and copy the file out once I've added some redirects back via the gui, but I can't seem to import it either. Copying and pasting from the file to the gui works fine, aside from unescaping json escapes... (for things like question marks)

**Comment by einaregilsson** [comment]
Sound weird, since an update of Firefox shouldn't do anything to a random file in your profile folder. But I have had reports of similar things before, not sure what is causing it.

**Comment by StephenBrown2** [comment]
I agree. I'm betting it might have to do with some security features screwing up the stream somewhere... It looks like you're not using the File/IO API. I found it corrupted after I did something else seemingly unrelated (Like restarting the browser), I'll see if I can't replicate it again over the weekend.

**Comment by einaregilsson** [comment]
Yeah, I'm using pretty old XPCOM apis for everything, this is an old extension :) But actually I've finally started working on it again, v3.0 will be a ground-up rewrite using the new webextensions apis, and will also be released for chrome. Will have a better UI, ability to block any type of request and will not store the redirects in a file anymore.

**Comment by StephenBrown2** [comment]
Sweet! Except for not storing in a file... Unless I can still export/import them... I'd like to have a backup in case something like this happens again (even though it shouldn't. horror of horrors ;-) )

**Comment by einaregilsson** [comment]
The import/export will still be there :) But yeah, given that this is happening it's probably a good idea to do backups every once in a while.

**Comment by Gitoffthelawn** [comment]
I think I've had minor redirector.rjson corruption once or twice... I remember cutting and pasting using a text editor (and fixing escaping/unescaping) to fix it.  I didn't realize others had experienced the same thing.  Glad @StephenBrown2 was able to piece his hard work back together!

@einaregilsson Excited to hear you are writing a new version!  I was afraid we were going to lose Redirector when e10s is finalized.  If you post alphas/betas, I can hopefully find time to provide feedback on the UI/UX, as that is my area of expertise.

**Comment by einaregilsson** [comment]
@Gitoffthelawn Will do. The webextensions (chrome) api is still only in Firefox Nightly, so it will be a while until I can release 3.0. Right now I'm just creating the new extension as a chrome extension, and will then adapt as necessary for Firefox. The idea is that you can use pretty much the same extension in both, but I'm sure there will be some quirks and unsupported stuff to work around.
