### ISSUE TITLE
Dynamic Redirect

### ISSUE THREAD

**Issue by linuxlad** [einaregilsson/Redirector#270]
I'm trying to use regular expressions and/or wildcard, how to redirect when the seven digit numbers (#######) are dynamic and could be any set of numbers such as 8429553 or 6632794, etc.

So if I want to redirect this:  https://www.sitename.com/title/tt#######/

To this:     https://www.sitename.com/title/tt#######/reference

What is the best method to make this work?

**Comment by einaregilsson** [comment]
If it's definitely numbers I'd probably do

Include pattern: https://www.sitename.com/title/tt*/
Redirect to: https://www.sitename.com/title/tt$1/reference
Exclude pattern: https://www.sitename.com/title/tt*/reference
Redirect type: Wildcard

Although this is just off the top of my head and I haven't tested it :)

**Comment by linuxlad** [comment]
yes its working now with

tt(\d{7})
tt$1/reference
