### ISSUE TITLE
[request] sample rule for archive.org (Wayback Machine)

### ISSUE THREAD

**Issue by 07416** [einaregilsson/Redirector#271]
How to create a rule which follows this pattern? (add the `https://web.archive.org/web/` prefix):

* `https://www.washingtonpost.com/` → `https://web.archive.org/web/https://www.washingtonpost.com/`
* `https://www.npr.org/` → `https://web.archive.org/web/https://npr.org/`

Please create a pull request to add a new [example rule](https://github.com/einaregilsson/Redirector#examples). 

Feel free to use the websites above as examples, both appear to block access for EU citizens unless they accept tracking.

**Comment by einaregilsson** [comment]
I'd probably do something like:

Include: https://www.washingtonpost.com/*
Redirect to: https://web.archive.org/web/https://www.washingtonpost.com/$1
Pattern type: Wildcard

Same type of redirect for npr.
