### ISSUE TITLE
[Feature request] Have multiple redirect targets

### ISSUE THREAD

**Issue by Huy-Ngo** [einaregilsson/Redirector#272]
## Context

A use case for Redirector is to use alternative frontends for some websites.
For example, I want to use an invidious instance to watch YouTube. 

However, I'd like to use several instances instead of just one, so as to balance load between servers.
 As far as I'm aware, there is no possible way to do this currently.

## Requested feature

There can be a list of redirect target for one pattern. For example:

youtube.com → [yewtu.be, ytb.trom.tf, ytprivate.com]

The chosen target can be decided by a random function.

**Comment by einaregilsson** [comment]
Sorry, I feel like that is a very niche request that not many people are going to use, so I'm gonna have to say no to this one.

**Comment by ghjardim** [comment]
Personally, I would use it.

**Comment by stephenhawk8054** [comment]
I also really need this feature.

**Comment by Huy-Ngo** [comment]
Fwiw, for the use case I said above, there is another addon, Privacy Redirect and its fork LibreDirect.

**Comment by tauin** [comment]
I would too, its quite useful especially if a redirect is down for whatever reason
