### ISSUE TITLE
Help for excludePattern when the pattern is the question mark itself

### ISSUE THREAD

**Issue by ghost** [einaregilsson/Redirector#275]
Hi,

Regular expressions can be tough to elaborate. I'm getting along yet I face a difficulty when trying to set a question mark as the excludePattern.

My filter:
```

"description": "### WIKIMEDIA timeless STYLE ###",
"exampleUrl": "https://en.wikipedia.org/wiki/Ambiguity",
"exampleResult": "https://en.wikipedia.org/wiki/Ambiguity?useskin=timeless",
"error": null,
"includePattern": "(.*//.*)(mediawiki.org|wikibooks.org|wikidata.org|wikimedia.org|wikinews.org|wikipedia.org|wikiquote.org|wikisource.org|wikispecies.org|wikitravel.org|wikiversity.org|wikivoyage.org|wiktionary.org)/(.*)",
"excludePattern": "(.*//.*)(mediawiki.org|wikibooks.org|wikidata.org|wikimedia.org|wikinews.org|wikipedia.org|wikiquote.org|wikisource.org|wikispecies.org|wikitravel.org|wikiversity.org|wikivoyage.org|wiktionary.org)/(.*)?useskin|search",
"patternDesc": "",
"redirectUrl": "$1$2/$3?useskin=timeless",
"patternType": "R",
"processMatches": "noProcessing",
"disabled": false,
"grouped": false,
"appliesTo": [
"main_frame"
]
```

Setting `?useskin|search` works, but I'd like the exclusion to consider `?` followed by anything. Just can't figure it out!

I'm aware this is not an issue regarding _Redirector_, but if you, developer, or any talented user has the answer, then many thanks!

**Comment by einaregilsson** [comment]
What about the exclude pattern as just:

```.*\?.*```

That escapes the ? and should match anything with a ? in it anywhere. The include pattern is applied first, so the exclude pattern is only applied to things that have already matched the include pattern, so the exclude pattern doesn't need to list out all the host names and all that stuff.

**Comment by Cade66** [comment]
That does it! Many thanks @einaregilsson  :=)

> The include pattern is applied first, so the exclude pattern is only applied to things that have already matched the include pattern

I ignored that as well. Regular expressions are so powerful and handy, but soooo... tough to understand, tougher even to integrate, I mean to find the equation that will integrate all filters into one, so to say. There's plenty of documentation on the Web but seems to me as explaining quantics to a first-grader!

**Comment by einaregilsson** [comment]
Yeah, regular expressions are a pain, but so powerful! Always feel like a genius when I manage to come up with a good one, but coming back to it later you can never remember wtf it was doing!

**Comment by Cade66** [comment]
I do as well! Ego is a good trigger for succeeding. _yes, we can!_ 

I've modified other REDIRECT filters now that I realize that "_The include pattern is applied first, so the exclude pattern is only applied to things that have already matched the include pattern_" That's a major point for me, so besides an immediate solution your answer contributes to a wider understanding of the RegEx.

Taking this opportunity to point out how helpful the REDIRECT is. When it comes to redirecting an url userscripts just won't make it as nicely as REDIRECT given they load the site first to then apply the redirection, which is problematic when privacy is engaged, and speed : the REDIRECT filter of mine, mentioned above, was built on the basis of a userscript which therefor would open the site before modifying if applicable its url. The result is of course much faster to appear with a redirection which captures the url before it lands. Lasso!  

So, yes, I'm one of the many most grateful users. Not to mention how easy, intuitive, wel carried-out REDIRECT definitely is.

**Comment by einaregilsson** [comment]
I'm glad you can use it 🙂
