### ISSUE TITLE
Twitter redirect doesn't work on Brave

### ISSUE THREAD

**Issue by dschuessler** [einaregilsson/Redirector#277]
First of all: Thank you for your great extension. I recently switched to Brave and the following redirection does not work (although others work and this one works on Firefox and Chrome):

Redirect:	https://\*twitter.com/\*
to: https://nitter.kavin.rocks/$2
Example:	https://\*twitter.com/\* → https://nitter.kavin.rocks/*
Applies to: Main window (address bar)

Since you do not officially support Brave, I guess this is to be expected. I open this issue anyways just in case I find the time to fix this myself and open a PR. 🙂

**Comment by einaregilsson** [comment]
Twitter does a lot of weird stuff, they don't always load pages normally. But have you tried to check both "Main frame" and "History State" in the "Applies to" list?

**Comment by dschuessler** [comment]
I hadn't. There is no checkbox "Main frame" in the "Apply to" list, only "Main window" which was already checked. I checked "History State" as well but had no luck.

**Comment by xtrahigh** [comment]
No way. Even if all the boxes are checked, `twitter.com/nick` will not be redirected, but `twitter.com/nick?lang=en` will.

**Comment by einaregilsson** [comment]
Yeah, sorry, no idea why that is.

**Comment by 12Boti** [comment]
Thank you, with "History State" it works, although it first loads Twitter, then redirects. It would be better if it redirected before trying to load, but I understand if that's not possible because of the service workers.

**Comment by 12Boti** [comment]
Found the solution! In chrome, it is possible to disable the service worker in devtools -> application. First disable the rule, then go to twitter, click "unregister" in the service workers menu, then enable the rule, then reload.

**Comment by Gitoffthelawn** [comment]
> Found the solution! In chrome, it is possible to disable the service worker in devtools -> application. First disable the rule, then go to twitter, click "unregister" in the service workers menu, then enable the rule, then reload.

Interesting.  Does this still work after restarting Chrome?  Or is it just working for the current session?

**Comment by 12Boti** [comment]
It works after restarting too. I think twitter starts the worker when you load their page, so if Redirector redirects it beforehand, it can't start again.

**Comment by Gitoffthelawn** [comment]
> It works after restarting too. I think twitter starts the worker when you load their page, so if Redirector redirects it beforehand, it can't start again.

Thanks.  I must be missing something, because I would think once you restart the browser and go back to twitter, the service worker would be created again.  Or are you leaving the twitter tab open when you close the browser?

**Comment by 12Boti** [comment]
When I go back to twitter, it redirects (before loading the original), so the service worker never gets started again. No need to leave anything open.

**Comment by Gitoffthelawn** [comment]
> When I go back to twitter, it redirects (before loading the original), so the service worker never gets started again. No need to leave anything open.

Ah, I see.  So the change you made in devtools must be non-volatile.  That's surprising, but explains what you are experiencing.  Good job on that workaround.  Note that if you clear Chrome's caches & storage, it's possible you'll have to implement your workaround again.

**Comment by jadedgnome** [comment]
> 

thanks!

this helped me sanitize this url after I ticked the "history state" box.

https://twitter.com/AnimalsAsia/status/1450776726309638145?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1572285705883353089%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=

to 

https://twitter.com/AnimalsAsia/status/1450776726309638145

https?://(.*?\\.)?twitter.com/(.*)/status/(.*)\?ref_src(.*)&ref_url=(.*)
https://twitter.com/$2/status/$3

**Comment by dschuessler** [comment]
I am not experiencing any problems anymore. Therefore, I'm closing this issue. Feel free to reopen if anyone else is still affected.
