### ISSUE TITLE
Doesn't work at all in Edge

### ISSUE THREAD

**Issue by Rudde** [einaregilsson/Redirector#292]
I downloaded this extension so I could redirect myself from twitter to the nitter, very trivial pattern `https://twitter.com/*` to `https://nitter.net/$1`

I was surprised when nothing happens, especially since example showed exactly what I wanted. Tried to restart Edge, and after restarting my computer too, still nothing, enabled notification and logging, that didn't do anything, and I have no idea where the logs are supposed to end up. 

installed the extension on Firefox to see if it was edge that was the problem. Made the same rule there and it worked flawlessly.

**Comment by einaregilsson** [comment]
Hi

Twitter uses service workers on WebKit based browsers, and they mess with the redirection. Try checking the "History State" option under "Applies to", that should work.

**Comment by idontusenumbers** [comment]
I have the same issue; doesn't seem to work in Edge at all. I even tried the built-in pattern for example.com and went to example.com/test and it didn't redirect to google.

**Comment by Rudde** [comment]
Ops. I should probably have closed this issue since @einaregilsson solution worked for me. But I'll keep it open since @idontusenumbers have the problem. Please let me know if I can close it. I don't know about recent Edge version since I don't use Edge anymore.

**Comment by Gitoffthelawn** [comment]
@idontusenumbers Hi Charlie.  Do you still have this issue, or did you get Redirector working on Edge?
