### ISSUE TITLE
Upgrade Redirector to use new WebExtensions api for v3.0

### ISSUE THREAD

**Issue by einaregilsson** [einaregilsson/Redirector#30]
According to Mozilla the future of Firefox addons is the [WebExtensions API](https://wiki.mozilla.org/WebExtensions) which is in large parts the same as the one in Chrome and Opera. Redirector 3.0 will be completely rewritten to use this API, and at the same time released for Chrome and Opera as well as Firefox. 

The rewrite is happening in the [webextensions branch](https://github.com/einaregilsson/Redirector/tree/webextensions). It is mostly finished, it works fine on both Chrome and Opera, but WebExtensions is still only in Firefox Nightly, and very very buggy still, so it's not ready to be released yet. AMO also needs to start accepting WebExtensions addons before the release is possible.

The major new features in 3.0 are:
- Completely new UI for editing redirects
- Browser support for Firefox, Chrome and Opera
- The ability to redirect ANY kind of request, scripts, images, anything. 

If anyone wants to help with this, then please check out the [webextensions branch](https://github.com/einaregilsson/Redirector/tree/webextensions) and try it. For now it mostly makes sense to test in Chrome or Opera, because Firefox has major issues with reading the redirects again after writing them to chrome.storage. @Gitoffthelawn , maybe you could try this out?

**Comment by Gitoffthelawn** [comment]
I wish I had the time to check this out right now, but my time is overbooked.

If I get some free time, I will be happy to try it and provide feedback.

BTW, do you know the order Mozilla now plans on releasing WebExtensions, e10s, and 64-bit?

If e10s renders Redirector useless (not sure if it will or won't), I'm hoping WebExtensions will be released so there is no gap in availability of Redirector on that platform.

**Comment by einaregilsson** [comment]
No idea about order of release, but I know WebExtensions is only in Nightly so it's probably at least 3*6 weeks away, so over 4 months. So this version isn't coming out anytime soon. I'll probably release the Chrome version as soon as I can though, since that's almost ready.

**Comment by einaregilsson** [comment]
Basically done, except right now FF version uses a massive WE polyfill. Will keep this issue open until we can ship a WebExtensions only version of Redirector.

**Comment by KrasnayaPloshchad** [comment]
Mozilla announced they intended to start supporting WebExtensions on 48.0, and they published the road map on their wiki.

**Comment by einaregilsson** [comment]
They say they support some of the apis I need now, but they still don't work properly, so I'm not sure when I'll be able to fully use WebExtensions :/

**Comment by Gitoffthelawn** [comment]
It will be interesting to see if WebExtensions results in worse or better performance.

**Comment by KrasnayaPloshchad** [comment]
>They say they support some of the apis I need now, but they still don't work properly, so I'm not sure when I'll be able to fully use WebExtensions :/

> It will be interesting to see if WebExtensions results in worse or better performance.

In this case you have to tracking their bugs, maybe you can also report to them. They also put their bugzilla pages on wiki site.

**Comment by einaregilsson** [comment]
Finished a long time ago.

**Comment by Gitoffthelawn** [comment]
In a galaxy far, far away...
