### ISSUE TITLE
Storage Sync Check Box Having Opposite Effect

### ISSUE THREAD

**Issue by psy-guy** [einaregilsson/Redirector#303]
Checking "Enable Storage Sync" actually disables sync instead of enabling it, and unchecking the box enables it. I encountered this in Chrome for both MacOS and Windows.

![image](https://user-images.githubusercontent.com/28989849/159031872-a801cf82-293a-418b-ad5c-3601053efd06.png)

**Comment by Victor4X** [comment]
In my experience this is caused by the checkbox always toggling storage sync, but not being pre-checked when already having it enabled, thus putting it out of sync.
