### ISSUE TITLE
Migrate Redirector.rjson to chrome.storage when upgrading to 3.0

### ISSUE THREAD

**Issue by einaregilsson** [einaregilsson/Redirector#31]
As of now there is no way with the new WebExtensions API to read a file from the filesystem. This will cause problems for those upgrading from an older version of Redirector. What is needed is to figure out if there's any way to read the Redirector.rjson file from the user's profile folder and put it into chrome.storage on startup.

If there's absolutely no way to do that, then a link should be added to the main Redirector page saying something like:

**Are you upgrading from an older version of Redirector and all your redirects are gone? Click here for more info.**

The link would only be shown if it is Firefox, and there are 0 redirects. Then it would link to an explanation saying why the redirects couldn't be migrated automatically, explaining the most common place for the profile folder on Windows, OSX and Linux, and telling the user to use the Import button to find his old Redirector.rjson file and import that.

**Comment by Gitoffthelawn** [comment]
I haven't had time to review WebExtensions API yet, but I know the uBlock extension is cross-platform and cross-browser, and creates a sqlite database as a separate file in the filesystem.  I don't know if it uses WebExtensions API or not, but if it does, then you can see how they did it.  If it doesn't... nevermind. :-)

**Comment by einaregilsson** [comment]
No addons use the WE api yet, as AMO doesn't accept addons using it yet. But we'll see what's possible when it ships in FF stable :)

**Comment by einaregilsson** [comment]
This issue fixed by releasing an intermediate version of Redirector based on the AddOn SDK, which migrated the file to the right place for WebExtensions.
