### ISSUE TITLE
Using a wildcard..part missing.

### ISSUE THREAD

**Issue by harryray33** [einaregilsson/Redirector#310]
A site, voe.sx, keeps changing it's name. At the moment it's https://voe-un-block.com. 
The voe and the .com is always there, but the middle part changes.

I want to redirect it to 9xbuddy.org and change the name to voe.sx

For example, I want to redirect https://voe-un-block.com/swjoq1hwfnft

I've tried this:
Example URL: https://voe*.*/*
Include pattern: https://voe*.*/*
Redirect to: https://9xbuddy.org/process?url=https://voe.sx/$1?

This redirects to the correct site, but the result is 
https://9xbuddy.org/process?url=https://voe.sx/? 

Instead of 
https://9xbuddy.org/process?url=https://voe.sx/swjoq1hwfnft

Any ideas please?

![Image 001](https://user-images.githubusercontent.com/42322725/174762715-9fac914f-eae2-4025-938e-621bfb062730.jpg)

![Image 002](https://user-images.githubusercontent.com/42322725/174762758-be6b8e1b-78b5-427c-ace7-cb3254d16168.jpg)

**Comment by Gitoffthelawn** [comment]
I'm not familiar with those sites, so I didn't confirm this will work, but all you should need to do is change `$1` to `$3` in the `Redirect to` string.  This should work because you desire to use the third wildcard captured.  Personally, I prefer to use regex patterns, as they give you complete control, but wildcards will work just fine for simpler tasks like this one.

**Comment by harryray33** [comment]
Thanks so much, I'll give it a try.
I'm afraid I haven't yet quite got my head around regex yet..what would the regex alternative be?

**Comment by Gitoffthelawn** [comment]
You're quite welcome.  There aren't too many well known alternatives to regex except for wildcards (which is what you're using).  Wildcards are like an extremely limited form of regex.  Fortunately, Redirector supports both regex and wildcards in the UI.

I great regex tutorial website is RexEgg: https://www.rexegg.com (and it has little dinosaurs to keep you smiling!).

**Comment by harryray33** [comment]
Thanks again, I've tried writing a regex to redirect voe but can't quite get it right. Any idea what it would be?

I (hopefully) could then use the regex written for this particular problem as a template for other sites that change name.

**Comment by Gitoffthelawn** [comment]
I'm glad I could help.

Don't fret much about regular expressions, no one learns them overnight, and you have to use them somewhat regularly to not forget all their nuances... and they have *many* nuances!  Being an expert with regex is like being an expert at chess... there is always something more to learn... it's part of their "charm".

**Comment by harryray33** [comment]
I think I have it (at last) **:0)**

Example URL: https://voe.*\..*/(.*)
Include pattern: https://voe.*\..*/(.*)
Redirect to: https://9xbuddy.org/process?url=https://voe.sx/$1?

I'm not sure that I yet understand it but the learning curve continues (albeit very slowly) **:0)**
