### ISSUE TITLE
I've been trying to redirect all instagram urls into dark mode

### ISSUE THREAD

**Issue by pityalvarez** [einaregilsson/Redirector#311]
just by adding /?theme=dark at the end of everything = instagram.com/* It should always stay in dark mode. I can't get it to work, what am I doing wrong?

**Comment by Gitoffthelawn** [comment]
First mistake you're making is using instagram!  ;) ;) ;)

All joking aside, if you post your Redirector rule (as text inside a post), I would be happy to look at it and do my best to tell you why it's not working, and how to fix it.

**Comment by pityalvarez** [comment]
The pattern it's okay, i know it works, now i just want that everything it "redirects to" is the same link only with the added /?theme=dark
Include pattern: https://www.instagram.com/*

**Comment by Gitoffthelawn** [comment]
To do what you are specifying, the Redirect pattern will be: `http://www.instagram.com/$1/?theme=dark`

**Comment by pityalvarez** [comment]
AHHHHH
It was only because i didnt add https. Thank you, i partly understood wildcards

**Comment by Gitoffthelawn** [comment]
You're welcome.  Glad I could help you.
