### ISSUE TITLE
Listen for URL changes made by the History API and redirect

### ISSUE THREAD

**Issue by fiatjaf** [einaregilsson/Redirector#32]
I'm trying to redirect Youtube video URLs (https://youtube.com/watch?v=eqksy-991sI) to Toogles video URLs (http://toogl.es/#/view/eqksy-991sI), which doesn't show video (withabad music!) ads in the middle of the music videos I'm listening to.

It works, but not if I click on a video inside the Youtube search, because Youtube does some AJAX magic and changes the URL of the page, probably with `window.history.pushState` (but I'm not sure).

Is it possible to listen for these URL changes and redirect based on them? Is it easy?

**Comment by einaregilsson** [comment]
I've looked into it a bit, and it looks like I might be able to use https://developer.chrome.com/extensions/webNavigation#event-onHistoryStateUpdated to do something. I'll see what I can do.

**Comment by einaregilsson** [comment]
Not planning to support this, keeping Redirector focused only on normal http redirects. Closing this.
