### ISSUE TITLE
Accent in URL

### ISSUE THREAD

**Issue by akred** [einaregilsson/Redirector#322]
Hello everyone,

I spotted an issue and I don't know if it's due to a misconfiguration or a bug.
I try to access to some youtube channels directly into the videos tabs.
I have setup this kind of pattern with regexp option : 
- Include pattern : `https:\/\/www\.youtube\.com\/(c|channel|user)\/([\w\d\-\/_]+)(?!.*\/.*)
- Redirect to : https://www.youtube.com/$1/$2/videos`

Meaning that if I try to access to this URL : 
https://www.youtube.com/c/abc4-_45
I will be redirect to this one : 
https://www.youtube.com/c/abc4-_45/videos

However, I have noticed that it's not working with URL containing accents.
Example, with this URL : https://www.youtube.com/c/Stéphane/videos
I will be redirect to this : 
https://www.youtube.com/c/St/videos

Any idea on how to avoid this issue ?
Thank you

**Comment by Gitoffthelawn** [comment]
A quick thought... Is it possible that `\w` in your browser's JavaScript's regex engine does not match accented letters?

**Comment by akred** [comment]
Maybe, do you know by which pattern I should replace to test it please ?

**Comment by Gitoffthelawn** [comment]
I am writing these off the cuff, and don't have time to test them right now, but I think they are what you want.  Will something like the following work for you?

- Include pattern: https://www\.youtube\.com/(c|channel|user)/([^/]+)
- Redirect to: https://www.youtube.com/$1/$2/videos

Or if you like to optimize for performance and memory efficiency, as I often like to do, you can use something like:

- Include pattern: https://www\.youtube\.com/((?:c(?:hannel)?|user)/[^/]+)
- Redirect to: https://www.youtube.com/$1/videos

**Comment by akred** [comment]
I thought it was due the extension, but in fact, my regex didn't catch accents as you said
I tested your suggestion, and works perfectly, thank you 🙏🏽
