### ISSUE TITLE
[HELP REQUESTED] I'm stuck on how to use wildcard variables.

### ISSUE THREAD

**Issue by gaveitatry2** [einaregilsson/Redirector#326]
Nevermind.  I think that I resolved it with this:
![firefox_vyveik7Rm6](https://user-images.githubusercontent.com/75463665/197229248-03ad4a8b-d709-46ee-ad43-fd669fee646b.png)

I want to make it so that:
https://www.instagram.com/THEPERSONSUSERNAME/

Will always redirect to:
https://www.instagram.com/THEPERSONSUSERNAME/reels/

I have the Redirect to as:
https://www.instagram.com/$1/reels/

But I have no idea what to set the Example URL and Include Pattern to:
https://www.instagram.com/NOIDEAWHATTOPUTHERE/

**Comment by Gitoffthelawn** [comment]
What you created looks good, except you may only need to apply it to the main window.  You can test this by unchecking all items in the "Apply to" section except "Main window (address bar)" and see if it still works as you desire.

**Comment by gaveitatry2** [comment]
Thanks. For some reason it didn't work the first time, so I thought that I had to add the IFrames option. But I tested it just now for Main Window only, and that worked. So I went ahead and unchecked it.

**Comment by Gitoffthelawn** [comment]
You're welcome.  Glad to help.
