### ISSUE TITLE
pass the old site  link to the redirected link as a parameter

### ISSUE THREAD

**Issue by Hardcore-fs** [einaregilsson/Redirector#327]
Have the possibility to pass the link into the redirection.

There may be cases where we have a a clicked link & we need the parameters from that link passed to the new site

**Comment by Hardcore-fs** [comment]
roughly  something like this:

source site
https:somesite.com/->redirect
http://somesite.com/getbackenddata.do?xyz=123456&method=insecureseckey&getthis=1234567

The params might change,  sometimes 3 sometimes 4... same link
maybe grab everything after the "?"

but basically:
mydest site
http://localhost/extract&passed=????????????



cannot posti  an actual link,it it blows open a well known vendors  cloud back end via insecure http.. & incrementing param, there would be hell to pay becasue they supply cloud services to some major businesses...

yep.. a vendor who logs you in using https.
then uses redirects on the back end to send you to http:, 
to get data from their backend database using code called with parameters... over http
the "service" key never changes, only need manipulation of the reference keys for the data extraction.

**Comment by Gitoffthelawn** [comment]
@Hardcore-fs I'm going through some older issues and cleaning things up... do you still need help with this?  If so, just let me know.

**Comment by Hardcore-fs** [comment]
nope... it's all ok... you can close this if you want.

**Comment by Gitoffthelawn** [comment]
Glad to here all is good.
