### ISSUE TITLE
Not working in Firefox nightly.

### ISSUE THREAD

**Issue by UdongeinChan** [einaregilsson/Redirector#33]
After 2015-10-08 rv: 266895 addon not working. In the settings there is one empty rule. Add / Remove rules not working.

**Comment by einaregilsson** [comment]
Hi

Are you using 2.9.3? Because I've already made a new version, 3.0.3 which should work in Nightly. It's awaiting review but you can still download it at AMO.

**Comment by UdongeinChan** [comment]
3.0.3 work, ok.
