### ISSUE TITLE
Does not redirect URL provided as command line argument

### ISSUE THREAD

**Issue by rieje** [einaregilsson/Redirector#335]
URL provided as command line argument does not redirect until a subsequent refresh after the page has been loaded. Latest version of Firefox.

**Comment by Gitoffthelawn** [comment]
Firefox 108.0.2 was current version when this issue was reported.

**Comment by GeekPatrolMiller** [comment]
I am not certin how the OP is considering command line argument but I am not having trouble with an actual CLI action like this on my Ubuntu with the Snap Firefox 110.0b6 : 

        firefox  https://example.com/u/x/z?u=abc&b=asdf

What I am having trouble with is a link within an email. I am specifically using Outlook on Win10 and Firefox 109.0 (64-bit) is set in Windows as the default browser. The link opens directly and bypasses the Redirector.

**Comment by GeekPatrolMiller** [comment]
Same as Firefox on Windows. Bypassed the Add-In and went straight to the original domain site.

Here is the json exported so you can see what I have, incase that has some missing config item:

```
        {
            "description": "",
            "exampleUrl": "https://example.com/u/x/y?u=https://example.com",
            "exampleResult": "https://new-example.com/u/x/y?u=https://example.com",
            "error": null,
            "includePattern": "https://example.com/*",
            "excludePattern": "",
            "patternDesc": "",
            "redirectUrl": "https://new-domain.com/$1",
            "patternType": "W",
            "processMatches": "noProcessing",
            "disabled": false,
            "grouped": false,
            "appliesTo": [
                "main_frame"
            ]
        }
```

**Comment by Gitoffthelawn** [comment]
@GeekPatrolMiller Thanks.  What's interesting is that it works correctly in Ubuntu (at least with the Snap version of Firefox), but not in Windows 10.

As a test, try changing the `includePattern` to `"\"https://example\.com/.*"` and the `patternType` to `"R"`.  This will test if Windows is enclosing the URL parameter in double-quotes.

Besides Redirector, are there any other extensions installed in that Firefox profile in your Ubuntu or Windows 10 installations?  If so, would you mind creating a new Firefox profile with Redirector as the only extension and perform the tests again?

BTW, did you edit the exported JSON by hand at all?  I noticed that the `exampleResult` does not match the `redirectUrl`.

**Comment by GeekPatrolMiller** [comment]
You are right, I did not do anything in Linux other than launch firefox from a shell console and yes, that did work. I use Evolution for Mail and if I click a link in an email, I get the same results as I see in Windows where it does not redirect. I will add to this and say that it only fails if Firefox is not already running. If I start Firefox before I click the link in email, the redirector does exactly what is expected. 

I tried changing the "W" to "R" for the type and this only changed the results when the Redirector worked and I got a 404 error which would have been expected. I did not try to formulate a regular expression for this as I think this result is what you were after.

I created a new profile and loaded only the Redirector add on but there were no changes in behaviours.

I did manually edit the json for privacy. I am happy to share the actual json privately if you need it. I just did not want to invite the world to my tiny server.

**Comment by Gitoffthelawn** [comment]
> You are right, I did not do anything in Linux other than launch firefox from a shell console and yes, that did work. I use Evolution for Mail and if I click a link in an email, I get the same results as I see in Windows where it does not redirect. I will add to this and say that it only fails if Firefox is not already running. If I start Firefox before I click the link in email, the redirector does exactly what is expected.

I've noticed some similar oddities with Firefox command line parameters working as expected when Firefox is already running, but not working as expected when it is started cold.  In the past, I haven't had time time to isolate the issue to see if Redirector is involved with this issue or if it's purely a Firefox issue.  Just to ensure I'm understanding you 100%, you can confirm that this issue happens in Ubuntu and Windows ***only*** when Redirector is being used, correct?

> I tried changing the "W" to "R" for the type and this only changed the results when the Redirector worked and I got a 404 error which would have been expected. I did not try to formulate a regular expression for this as I think this result is what you were after.

Actually, for testing purposes, you'll need to change the `includePattern` to `"\"https://example\.com/.*"` as well.

> I created a new profile and loaded only the Redirector add on but there were no changes in behaviours.

Thank you.  That's very helpful.

> I did manually edit the json for privacy. I am happy to share the actual json privately if you need it. I just did not want to invite the world to my tiny server.

That's what I thought (and was hoping).  Nope, I don't need the verbatim JSON.  I just wanted to make sure there wasn't a bug that I didn't know about.  BTW, you're always welcome to just use the string `REDACTED`... I'll know what you mean.  One of the many nice things about Redirector exports is that they are easy to read and edit by hand.

**Comment by GeekPatrolMiller** [comment]
I did a little research on this to satisfy my own curiosities and I think that you may not be able to resolve this at all.
This is a 6 yr old bug report which has many opinions on whether this functionality should be allowed or not.
https://bugzilla.mozilla.org/show_bug.cgi?id=1378459
This article ultimately led me to this one:
https://bugzilla.mozilla.org/show_bug.cgi?id=1653237

I think these describe what is happening but this is only my guess.

Yes, On both Linux and Windows, If Firefox is running prior to clicking a link in an email, the Redirector add on performs as expected. If Firefox in not yet running, it would appear the page content is gathered from the actual URL thus bypassing the Redirector add on. A refresh of that same page will be successfully processed through the Redirector.

**Comment by Gitoffthelawn** [comment]
Thank you for the research and for reporting back.  I quickly skimmed both the Bugzilla reports, and added them to my reading list to mentally process all the juicy details.

**Comment by rieje** [comment]
> Firefox 108.0.2 was current release version when this issue was reported. Is that the version with which you have this issue?

There has been Firefox updates since then and it seems I don't have this problem anymore, closing.
