### ISSUE TITLE
[github] enable repository discussions

### ISSUE THREAD

**Issue by seanpm2001** [einaregilsson/Redirector#337]
Discussions are a useful GitHub feature, and it would be nice for this project to use them. It is a single checkbox to enable, and it would greatly strengthen this projects community.

For more info, see [:octocat: The GitHub Docs](https://docs.github.com/en/discussions/)

**Comment by Gitoffthelawn** [comment]
Discussions are now open!!!

https://github.com/einaregilsson/Redirector/discussions
