### ISSUE TITLE
supporting redirects for non standard format of url

### ISSUE THREAD

**Issue by rezad1393** [einaregilsson/Redirector#34]
hi
first thanks for a great addon.

second : 
I have a request for supporting redirects for non standard format of URL.
for example for freenet software that has webpage addressees in this format
'USK@e3myoFyp5avg6WYN16ImHri6J7Nj8980Fm~aQe4EX1U,QvbWT0ImE0TwLODTl7EoJx2NBnwDxTbLTE6zkB-eGPs,AQACAAE/bombe/116/page.1.html' 
to be redirected to the desired proxy ,in this case :
'http://127.0.0.1:8888/freenet:USK@e3myoFyp5avg6WYN16ImHri6J7Nj8980Fm~aQe4EX1U,QvbWT0ImE0TwLODTl7EoJx2NBnwDxTbLTE6zkB-eGPs,AQACAAE/bombe/116/page.1.html'

is this possible?

i tried different formats but they don't work because of different reasons.
1- firefox seems to change the domain part of URL to lowercase automatically .
2- if I type a url with the format USK@.....   firefox adds a http in front of it even if I use your addon to catch that address .

**Comment by einaregilsson** [comment]
Have you tried it on version 3.0.3? It's awaiting review but you can still download it on AMO. Try that one, if it doesn't work there I'll look more closely at it.

**Comment by rezad1393** [comment]
I use version 3.0.4

**Comment by einaregilsson** [comment]
When I create an include pattern that is just *@USK* and tell it to redirect to your localhost address it works for me. Can you post the include pattern, example url and redirect url you are using in your rule?

**Comment by rezad1393** [comment]
not '@USK' but USK@
like this 
'USK@CjdrIg9kZn0mzmKTPuofupZmsdvB5Ruas7wyZrekRmM,uhrRUrkJ18IOGtTraf4wVQ1LSlweOXcipZ9BNwv4Kgw,AQACAAE/cypher/17/'
i want to be able to type this in firefox and click enter and be redirected to 
'http://127.0.0.1:8888/USK@CjdrIg9kZn0mzmKTPuofupZmsdvB5Ruas7wyZrekRmM,uhrRUrkJ18IOGtTraf4wVQ1LSlweOXcipZ9BNwv4Kgw,AQACAAE/cypher/17/'

is this possible?

when i check foxyproxy logs I see that 'USK@CjdrIg9kZn0mzmKTPuofupZmsdvB5Ruas7wyZrekRmM,uhrRUrkJ18IOGtTraf4wVQ1LSlweOXcipZ9BNwv4Kgw,AQACAAE/cypher/17/' get redirected to 'http://USK@cjdrig9kzn0mzmktpuofupzmsdvb5ruas7wyzrekrmm,uhrrurkj18iogttraf4wvq1lslweoxcipz9bnwv4kgw,aqacaae/cypher/17/'

**Comment by einaregilsson** [comment]
Well, I can't seem to catch it even if I try to add http:// in front in the pattern. When I enter the url directly in the url bar I can see that the url that gets checked in Redirector is

https://www.google.com/search?q=USK%40asdf&ie=utf-8&oe=utf-8"

So, one idea might be to just catch that url and redirect it. E.g.
![screen shot 2015-10-16 at 15 21 19](https://cloud.githubusercontent.com/assets/557149/10545703/994129dc-7419-11e5-8758-98d96b1941f4.png)

That works for the case where you enter the url in url bar at least, don't know if there's a link from another webpage. It does depend on that there's never a & in the weird url you have though.

Might also make a general one that catches any url that has a USK@ in it any url, e.g. .*USK(@|%40)(.*), it depends a bit on which characters are allowed in these weird urls.

**Comment by rezad1393** [comment]
one big problem is this that firefox changes the domain name to lowercase and this messes with this protocol.
so your addon doesn't catch the url before firefox changes it to lowercase and messes it up
if your addon did that there may have been hope but right now firefox lower cases all the letters and pass it on to your addon and even it I could redirect it i get the wrong address.

the weird part is that the first time that I copy and paste and then click enter for the address firefox tries this and immediately stops
'http://USK@cjdrig9kzn0mzmktpuofupzmsdvb5ruas7wyzrekrmm,uhrrurkj18iogttraf4wvq1lslweoxcipz9bnwv4kgw,aqacaae/cypher/17/'
but the second enter uses the search (google , duckduckgo) and so on to search for 'USK@cjdrig9kzn0mzmktpuofupzmsdvb5ruas7wyzrekrmm,uhrrurkj18iogttraf4wvq1lslweoxcipz9bnwv4kgw,aqacaae/cypher/17/' not 'http://USK@cjdrig9kzn0mzmktpuofupzmsdvb5ruas7wyzrekrmm,uhrrurkj18iogttraf4wvq1lslweoxcipz9bnwv4kgw,aqacaae/cypher/17/'

**Comment by einaregilsson** [comment]
Yeah, I can't really do anything about the lowercasing. Sorry, I don't think this is going to work out. I think you'd need an addon that interacts directly with the url bar or something like that, not just intercept the requests after the url is normalized.

**Comment by rezad1393** [comment]
is this possible? ("an addon that interacts directly with the url bar"
i thought your addon acted earlier in the process chain.
can your addon be moved to earlier stages of url process or is it impossible?

**Comment by einaregilsson** [comment]
My addon interacts with http requests, it doesn't care whether the request originates from the address bar, or if it's a request for an image or script or whatever. You can also interact with the addressbar directly, handle when text is changed in it or something like that.

It's not something I'm interested in doing for this extension though. Also, the Firefox extension apis are going through a big change right now, there are essentially three different ways to create Firefox extensions, it's a bit of a mess. But maybe you can create your own extension, or find someone who can, that specifically listens for urls of the type USK@* being entered into the address bar and redirects those.

**Comment by einaregilsson** [comment]
5
