### ISSUE TITLE
Too much recursion

### ISSUE THREAD

**Issue by lugoues** [einaregilsson/Redirector#341]
Upon authenticating with the gcloud console client you are presented with a URL you must navigate to in a browser to generate an oauth token. When enabled, Redirector causes the browser to freeze up for a good 30 seconds when opening the gcloud link even though all rules have been disabled. I've provided a screenshot of the log dump from Redirector when this occurs.

![image](https://user-images.githubusercontent.com/372610/222476321-7da0c919-347a-4c73-81ec-8beddf83b714.png)

**Comment by Gitoffthelawn** [comment]
Thanks for your report.  Can you please provide the following:

1. Operating system.
2. Browser name and version number.
3. Redirector version number.
4. Discrete steps to reproduce.
