### ISSUE TITLE
Display Wikipedia articles in a specific language

### ISSUE THREAD

**Issue by ghost** [einaregilsson/Redirector#346]
I try to display Wikipedia articles in a specific language.
I asked on https://www.reddit.com/r/firefox/comments/z4984k/is_there_a_way_to_always_redirect_nonenglish/, but did not find a solution.
How can I achieve this?

**Comment by KamiyaMinoru** [comment]
> I try to display Wikipedia articles in a specific language. I asked on https://www.reddit.com/r/firefox/comments/z4984k/is_there_a_way_to_always_redirect_nonenglish/, but did not find a solution. How can I achieve this?

I don't think this is how wikipedia works; for your case, 
I will suggest you build search engine instead of using google.

**Comment by NyeUsr** [comment]
If I'm understanding the request right, all you would need to do it replace the `it.` part with `en.` which can be done easily with Redirector. For example to change all non-English Wikipedia urls to English you could use something like:

Example URL: `https://it.wikipedia.org/wiki/Mozilla_Firefox`
Include Pattern: `https://*.wikipedia.org/*`
Redirect To: `https://en.wikipedia.org/$2`
Pattern Type: `Wildcard`
Exclude Pattern: `https://en.wikipedia.org/*`
