### ISSUE TITLE
Redirect bing alt searches (images, shopping etc.) to google counterparts.

### ISSUE THREAD

**Issue by zabarocky** [einaregilsson/Redirector#348]
I've managed to do it with bing maps to google maps, but I'm unsure how to go about it with for example images as google doesn't have a URL prefix for images, or at least I think so.

![image](https://user-images.githubusercontent.com/85898484/230067781-e6dc1df2-4560-4c1b-b3da-48acce58c5bf.png)

**Comment by NyeUsr** [comment]
In Google it seems to be determined by `&tbm=`

Examples:

For Bing Images to Google Images:
Example URL: `https://www.bing.com/images/search?q=test&form=HDRSC3&first=1`
Include Pattern: `https://www.bing.com/images/search?q=*&*`
Redirect To: `https://www.google.com/search?q=$1&tbm=isch`
Pattern Type: `Wildcard`

For Bing Videos to Google Videos:
Example URL: ``
Include Pattern: ``
Redirect To: ``
Pattern Type: `Wildcard`




Example URL: ``
Include Pattern: ``
Redirect To: ``
Pattern Type: `Wildcard`
Example URL: ``
Include Pattern: ``
Redirect To: ``
Pattern Type: `Wildcard`
Example URL: ``
Include Pattern: ``
Redirect To: ``
Pattern Type: `Wildcard`
