### ISSUE TITLE
css color

### ISSUE THREAD

**Issue by MurkBRA** [einaregilsson/Redirector#35]
I have change the default text color on firefox so my text is white.
Can you add this css line on body "color: #2B2626;" on help page (resource://redirector-at-einaregilsson-dot-com/help.html) like you did on edit redirects page?

**Comment by einaregilsson** [comment]
Have added it to the source. Will probably do a small release in a few days when I've gotten some more bugs reported.

**Comment by MurkBRA** [comment]
Thank you.
