### ISSUE TITLE
old.reddit.com "nice hat" issue

### ISSUE THREAD

**Issue by Gooberpatrol66** [einaregilsson/Redirector#363]
I've been experiencing this problem 
https://old.reddit.com/r/help/comments/15kwhgy/why_is_every_image_link_i_click_on_directing_me/
This is the rule I'm using:
Redirect: https://www.reddit.com/*
to: https://old.reddit.com/$1 
Does anyone know how to fix it?

**Comment by Gooberpatrol66** [comment]
figured it out:
Exclude pattern: https://www.reddit.com/media*|https://www.reddit.com/rpoll*|https://www.reddit.com/rpan*|https://www.reddit.com/settings*|https://www.reddit.com/topics*|https://www.reddit.com/community-points*

**Comment by realAzazello** [comment]
> figured it out: Exclude pattern: [https://www.reddit.com/media*|https://www.reddit.com/rpoll*|https://www.reddit.com/rpan*|https://www.reddit.com/settings*|https://www.reddit.com/topics*|https://www.reddit.com/community-points](https://www.reddit.com/media*%7Chttps://www.reddit.com/rpoll*%7Chttps://www.reddit.com/rpan*%7Chttps://www.reddit.com/settings*%7Chttps://www.reddit.com/topics*%7Chttps://www.reddit.com/community-points)*

I suggest also adding `https://www.reddit.com/gallery/*`
