### ISSUE TITLE
[Question] Where are the logs ?

### ISSUE THREAD

**Issue by KaKi87** [einaregilsson/Redirector#364]
Hello,

Where are the logs from the "enable logging" option ?

Thanks

**Comment by Gitoffthelawn** [comment]
They are located in the browser console.  In Firefox, to access the browser console, press Ctrl+Shift+J.

I hope this helps you.

**Comment by climbTheStairs** [comment]
Just to add, for anyone also looking for this, logs are only visible when Browser Console Mode is set to "Multiprocess".

<img width="743" height="113" src="https://github.com/user-attachments/assets/85096924-5517-4257-9e92-ba4e0cb534aa" />
