### ISSUE TITLE
How to redirector http(s)://localhost/faramita to https://localhost1111/faramita

### ISSUE THREAD

**Issue by Faramitas** [einaregilsson/Redirector#366]
I don't want to change or delete "*/faramita",just redirector THE HEAD URL.

**Comment by Anonymous3-a** [comment]
I'd use wildcard mode with `http*://localhost/faramita/` --> `http$1://localhost:1111/faramita/`, but that method lets you enter stuff such as `httpsajkdlsajgklr://localhost/faramita/`. If you want ONLY `http://` or `https://` to redirect, using the Regex `http(s)?://localhost/faramita/` --> `http$1://localhost:1111/faramita/` should work.

TL;DR: Regex is the best way for what you want, use `http(s)?://localhost/faramita/` --> `http$1://localhost:1111/faramita/`

**Comment by Gitoffthelawn** [comment]
@Faramitas Did the solution provided by @Anonymous3-a work for you?  If so, you can close this issue report.  Thanks!

(To ensure the request is resolved, I'll wait a bit for the OP to respond before closing it myself.)
