### ISSUE TITLE
Not working in Firefox 119.0

### ISSUE THREAD

**Issue by Sopor** [einaregilsson/Redirector#370]
It seems that Redirector doesn't work in Firefox 119.0.

I hope that someone will take over this project 😊

**Comment by gforien** [comment]
Works fine for me in Firefox 119.0 - macOS Venture 13.6.1

Can you provide screenshots and provide the export of a simple non-working rule ?

**Comment by Sopor** [comment]
I use this when i want to find information about an IP address.

```
        {
            "description": "bgp.he.net",
            "exampleUrl": "http://w255.255.255.255/",
            "exampleResult": "https://bgp.he.net/ip/255.255.255.255",
            "error": null,
            "includePattern": "^https?://w(\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3})/$",
            "excludePattern": "",
            "patternDesc": "",
            "redirectUrl": "https://bgp.he.net/ip/$1",
            "patternType": "R",
            "processMatches": "noProcessing",
            "disabled": false,
            "grouped": false,
            "appliesTo": [
                "main_frame"
            ]
        },
```

In the web browser i type `w216.58.211.14` and press enter and it will take me to the page, but now i only get an error message

![image](https://github.com/einaregilsson/Redirector/assets/5789283/ac2847d5-c9ff-487d-9411-42696fa95d6b)

After doing some more testing, it seems that it is only these kinds of redirect that fails were i use a letter an then an IP address.

**Comment by Rhys-T** [comment]
I'm guessing you have `keyword.enabled` set to `false`. On my machine, trying to go to `w192.0.2.123` sends me to a Google search, even if I explicitly add `http://` to the beginning, but turning off `keyword.enabled` gives the result you're seeing. In either case, that Redirector rule never triggers.

It looks to me like the new version of Firefox is going:

- The first part contains a letter, so this can't be an IP address…
- But the last part is numeric, and TLDs can't be numbers, so this can't be a domain either…

…and deciding it can't be a valid URL at all (possibly to make it less likely to interfere with attempts to do searches using the URL bar) long before it ever thinks to ask Redirector about that URL.

A couple of alternatives:
- The Redirector approach works if you move the `w` to the end, like `192.0.2.123w` or `192.0.2.123.w` (and edit the rule to match) - Firefox still considers it a potential domain name in that case.
- If you're okay with putting a space after the `w`, you can actually do this without involving Redirector at all:
	- Go to Bookmarks > Manage Bookmarks.
	- Create a bookmark with a URL of `https://bgp.he.net/%s`.
	- Set its keyword to `w`.
	- Now Firefox should recognize the syntax `w 192.0.2.123` in the URL bar, and send you to `https://bgp.he.net/192.0.2.123`.

**Comment by Sopor** [comment]
Yes, i now use `w 192.0.2.123`, but i have been using the other way now for several years, so it will take some time until i get used to adding a space. 😊

So, there is nothing more to do than adapt.

Thanks for the info @Rhys-T
