### ISSUE TITLE
Rules without examples have red text

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#38]
When there is no example, bright red text indicates "No example URL".  Since there is not really an error, I recommend not using red text for this.

**Comment by einaregilsson** [comment]
As of version 3.0 the example url is required. Migrated redirects from earlier versions that don't have example urls will still work, but if you edit them you'll have to put it in so you can save the redirect.

Main reason for this is it helps me detect problems with the redirects earlier, and it helps users actually make the redirects to what they want them to do.
