### ISSUE TITLE
[site] Redirector is not rewriting address using regex on Edge

### ISSUE THREAD

**Issue by cengbrecht** [einaregilsson/Redirector#384]
Being new to Redirector, I am not sure if Edge is supported any longer, I did see that there is a Chrome version so I may have to try that. 
However, the installed version from the Edge Store seems to be broken, as it will not re-write using regex (Didn't try the wildcard method).
I did double check my regex with https://regexr.com/

My capture expression:
(?:https\:\/\/)([W]{3})(?:\.reddit\.com\/)([\w\W]{2,})

My test URL:
[https://www.reddit.com/r/uBlockOrigin/comments/b9tdky/rule_for_redirecting_urls_to_cleaner_ones/](https://www.reddit.com/r/uBlockOrigin/comments/b9tdky/rule_for_redirecting_urls_to_cleaner_ones/)

My Re-Write output:
https://old.reddit.com/$2

Expected output:
https://old.reddit.com/r/uBlockOrigin/comments/b9tdky/rule_for_redirecting_urls_to_cleaner_ones/

Unchanged output seen in address bar:
https://www.reddit.com/r/uBlockOrigin/comments/b9tdky/rule_for_redirecting_urls_to_cleaner_ones/

To Reproduce:
Run Edge, install from the Edge Store, enter my code above in Redirector, and go to the address listed above for example. 
(I used a template to be clearer, I hope it helps.)

**Comment by cengbrecht** [comment]
I apologize, the \n was from my testing.

**Comment by jadedgnome** [comment]
try `https://(www\.)?reddit\.com/(.*)`

**Comment by Gitoffthelawn** [comment]
@cengbrecht Were you able to get it working?

**Comment by cengbrecht** [comment]
Hello, 

I've not tested it since then but I did check my regex, and the code you provided looks similar to what I can remember. 
I don't plan on reinstalling but that's for keeping up with it.
