### ISSUE TITLE
Add "Options" button to the Firefox Add-ons Manager

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#39]
The Add-ons Manager entry for Redirector should include an "Options" button to open the rules. Currently, the only way to access them is to use the toolbar button, but Firefox extension developers add an extra button to the Add-ons Manager, so that users can access them if they hide the toolbar icon.

**Comment by Gitoffthelawn** [comment]
+1

**Comment by einaregilsson** [comment]
When the Firefox WebExtensions API is ready this will  probably come back in some form. For now your best option is probably to just add a normal bookmark for the Edit Redirects page.

**Comment by KrasnayaPloshchad** [comment]
This button would be useful if you use this addon on Firefox for Android.

**Comment by anewuser** [comment]
Fixed as of Redirector 3.1.0.
