### ISSUE TITLE
Compatibility with pseudo-protocols (like private:) from other extensions

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#40]
The [Private Tab](https://addons.mozilla.org/firefox/addon/private-tab/) Firefox extension lets users open private tabs in the same window as normal tabs.

If you type `private:https://www.example.com/` into the address bar or use it as a bookmark, the tab will automatically be converted to a private one, and the `private:` preffix will be dropped during the process.

I'm trying to create Redirector rules to add `private:` before some URLs automatically (along with an extra string to prevent loops), but can't get it to work. This is what I have so far:

![untitled-2](https://cloud.githubusercontent.com/assets/6733770/10715995/7e8b946c-7b10-11e5-9ac9-1bfae5a8f4b6.png)

Is there a way to make it work with the current version of Redirector? Maybe you can fix it by taking a look at the [Private Tab API](https://github.com/Infocatcher/Private_Tab#api-for-other-extensions).

**Comment by Gitoffthelawn** [comment]
+1 I think it's a fascinating idea.

I gave it a try without Private Tab by just adding *test:* as a prefixed protocol, and it would not work for that either.

**Comment by einaregilsson** [comment]
It's a nice idea, but not something I'm interested in adding to Redirector. I think this might be a better feature request for the PrivateTab extension itself, to have a list of regexes for urls that should always open in private tabs.

**Comment by anewuser** [comment]
Unfortunately, the PrivateTab developer isn't going to add it either. 

[He closed that request](https://addons.mozilla.org/firefox/addon/auto-private/) because of some third-party extension that is laggy, doesn't have a GUI and hasn't been updated to work with the latest Firefox changes.

**Comment by einaregilsson** [comment]
Still think that his extension would be the place to put that. Or develop a new extension that does just that. I don't want to add interaction with other extensions to Redirector. It's complicated enough to explain it to people as it is.

**Comment by anewuser** [comment]
Maybe my mistake was to mention his APIs and make it sound more complicated. As you can see in my original post, I even tried to add an extra URL string to prevent loops by myself (without you having to add the necessary code to check the private status with your own extension).

My request was about supporting addresses that start with `foo:` in general, not specifically Private Tab.

**Comment by einaregilsson** [comment]
Fair enough. I would add support for anything:// if it was supported by the api that I have access to. However, as someone told me, in the new version of Redirector the pre-redirect url is added to the history, so it wouldn't really make sense to redirect to a private:// url, it would already be in your history and would just give you a false sense of privacy.

**Comment by anewuser** [comment]
Thank you for your replies. I'm sorry if I sounded  demanding. I just wanted to make my request clear, but I now I see that what I wanted is not possible. I actually use private tabs to keep my history clean of entries I know I won't access again (or can quickly find again if I need) and for other things like logging on to the same site with two accounts at the same time.

As a longtime fan of the concept, I'm glad that Redirector has been updated and now support other kinds of requests.

**Comment by einaregilsson** [comment]
You didn't sound demanding at all, don't worry about it :) It's also good for me to understand what people are actually using Redirector for.

**Comment by anewuser** [comment]
@Gitoffthelawn Now there's a way to always automatically open specific domains in private tabs/containers: https://addons.mozilla.org/addon/temporary-containers/ (disable the "automatic mode" setting).

There's also an extension to keep your history clean of unwanted URL patterns: https://addons.mozilla.org/addon/historia/ . It accepts simple expressions and regex rules like these:

```
/(\/?|\/|\&)search/
/\/?q=/
^*://t.co/
^moz-extension
example
google.com
```
