### ISSUE TITLE
[fr] Add the possibility of putting notes next to a redirection module.

### ISSUE THREAD

**Issue by STVGecko** [einaregilsson/Redirector#400]
Add the possibility of putting notes next to a redirection module. I've created a module that redirects to an instance of wikiless. In order to remember the different instances, a note would allow me to efficiently find information related to this redirection module. In this case, here's the note I'd use :"https://github.com/Nangjing/wikiless/blob/main/instances.json"

Voici un exemple d'integration de cette solution :
![{EA251F30-36BF-4A59-8EAC-BE2E9F62668E}](https://github.com/user-attachments/assets/7b31bda5-ac77-4bf0-8904-1ae46c3a43cc)

**Comment by Gitoffthelawn** [comment]
Will the `Pattern Description` field work for this purpose?  That's what I largely use it for.

**Comment by STVGecko** [comment]
Oh...yeah, thanks. An oversight on my part, I used it as well. 🤦‍♂️

**Comment by Gitoffthelawn** [comment]
You're welcome.
