### ISSUE TITLE
Gibberish if you open the rules editor on a Firefox private tab

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#41]
This is what I get if open the options for Redirector on a Firefox 42 private tab:

![untitled-1](https://cloud.githubusercontent.com/assets/6733770/10789190/05e1b762-7d63-11e5-852d-f17465078cc8.png)

The [uBlock Origin](https://addons.mozilla.org/firefox/addon/ublock-origin/) and [Menu Wizard](https://addons.mozilla.org/firefox/addon/s3menu-wizard/) dashboards work normally on private tabs, so this isn't a limitation of private browsing.

**Comment by einaregilsson** [comment]
Addons using the addon-sdk must opt into private browsing:

https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/private-browsing

Redirector is now using the Addon-sdk, and I prefer not to request the private browsing permission.

**Comment by anewuser** [comment]
Ah. This problem is specific to the options page though. Redirects work normally.

**Comment by anewuser** [comment]
The new text displayed on private tabs is misleading, since redirections do work in private mode. It should say that the settings page doesn't work.

**Comment by einaregilsson** [comment]
Yeah, I actually think that's extremely weird that the page scripts don't work but the background  ones do work. I'll look into it for the next version.
