### ISSUE TITLE
No longer working with redirects to javascript

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#43]
Redirector v3.0.4 no longer works with all the redirects to javascript functions (or the syntax has changed!).

For example, the following redirect no longer works:
FROM: http://www\.http\.com/(.*)
TO: javascript:'You likely meant: $1'

Similarly, this redirect no longer works:
FROM: http://domains\.googlesyndication\.com/apps/domainpark/
TO: javascript:'Domain is parked.'

I use about a dozen Redirector rules that redirect to inline javascript.

This issue may be related to #40

**Comment by einaregilsson** [comment]
Sorry, that's never going to work again. I'm restricted by the chrome.webRequest API and what it allows. I want to keep this extension cross-browser and stick with well-supported APIs, and they only support redirecting to http and https.

**Comment by Gitoffthelawn** [comment]
Thanks for the info.  That really too bad that the chrome.webRequest API is so limited.

Redirecting to inline javascript is so useful and flexible.
