### ISSUE TITLE
xkcd to explainxkcd not working

### ISSUE THREAD

**Issue by 1593574628** [einaregilsson/Redirector#44]
I suspected it had something to do with HTTPS, so I turned off HTTPS-Everywhere and it still did not work. 

Am I doing something wrong?
![xkcd](https://cloud.githubusercontent.com/assets/12498661/10872810/f51f9c3c-80f0-11e5-9ba0-be7f3675b438.png)

**Comment by 1593574628** [comment]
By the way, I'm using Firefox 41.0.2

**Comment by Gitoffthelawn** [comment]
Try changing the ***Redirect to*** to this: `https://www.explainxkcd.com/$1`

**Comment by 1593574628** [comment]
So obvious... Thank you so much!

**Comment by Gitoffthelawn** [comment]
You're welcome.  Often the most obvious things are what stump us all!  :-)
