### ISSUE TITLE
Add check in rule editor to ensure valid result

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#45]
Einar, I wonder if Redirector needs to include a quick check in the rule-editing interface to ensue that the result begins with `http://` or `https://`.  I can see issues like #44 being commonplace and perhaps causing people to think Redirector does not work.

The check could just be performed during rule-editing, and therefore would not impact performance while Redirector is performing its redirection duties.

What do you think?

**Comment by einaregilsson** [comment]
Like it. Relative urls did work in the old version, e.g. redirect from http://example.com/folder/foo.php to index.php and it would resolve to http://example.com/folder/index.php, but I didn't like it.

So yes, I'll try to add something for the next version. I've got a few things now, so I'll probably do a bugfix release in the next few weeks.

**Comment by Gitoffthelawn** [comment]
Sounds great Einar. :-)

**Comment by einaregilsson** [comment]
This is implemented in version 3.5, won't allow you to make redirect that doesn't result in a http?s:// url.
