### ISSUE TITLE
Is it possible to exclude multiple patterns?

### ISSUE THREAD

**Issue by krikmo** [einaregilsson/Redirector#47]
I tried commas and semi-colons but it did not work.

I've been trying to figure out how [these](https://github.com/einaregilsson/Redirector/blob/master/redirector.html#L84) [lines](https://github.com/einaregilsson/Redirector/blob/master/redirector.html#L145) store the excludes, but unsuccessfully. 

Can someone give me some light?

**Comment by Gitoffthelawn** [comment]
Excluding multiple patterns is not explicitly supported (the user has to create a new rule), but you can use regex (regular expressions) to match multiple patterns.

**Comment by krikmo** [comment]
Creating a new rule was enough. I'm looking into regex as well.

Thanks! :smiley:
