### ISSUE TITLE
Redirect to file:// url doesn't work in 3.0.4

### ISSUE THREAD

**Issue by yarnweaver** [einaregilsson/Redirector#48]
I've noticed that redirect to file:// url doesn't seem to work in 3.0.4 in Firefox. It works in 2.9.3 though. Redirect to http:// and https:// seems to work okay in 3.0.4.

Some of the redirects I had set up on 2.9.3 redirected to a local javascript file, which then used its query string parameters to calculate new values, which were then used as parameters in a redirection to another public web page. I don't think it's possible to do that with Redirector just by itself, without also using locally stored scripts.

Course, you can get around the fact that file:// doesn't work in 3.0.4 by configuring Apache to serve your local javascript file on your machine instead - but personally I'd prefer to use version 2.9.3 instead.

I've only tried it on one machine so far.

**Comment by einaregilsson** [comment]
Unfortunately file:/// will not be supported in Redirector again. I'm using a newer API to do the redirecting, and it doesn't allow redirects to file:///. So your best bet is running a local server, or just dump your scripts to a free web server somewhere if they're not too private, e.g. github pages.

**Comment by yarnweaver** [comment]
Thanks for the quick response.

Like you suggest, using a web server is probably the simplest solution, because it will allow me to use the script files that worked with Redirector 2.9.3 unchanged with Redirector 3.0.4.

Alternatively, I guess I could use Greasemonkey.

**Comment by heroboy** [comment]
Use a local file is convenient in test and debug. So is it possible to read the file content and convert it to a data URL, and redirect to it?

**Comment by einaregilsson** [comment]
Sorry, no, I have no plans to support any kind of file:/// urls in Redirector anymore. Your best bet is just running a simple httpserver in your directory. E.g. if you have python installed you can just use

python -m SimpleHTTPServer
