### ISSUE TITLE
Option to remove & or ? at the end of a URL

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#49]
I have some rules to sanitize URLs that leave ampersands or question marks behind depending on the number or position of the parameters in the URLs. Because of the loop protection, I can't create another rule to remove them.

Coud you add an option to remove such characters from a URL after a redirect is performed?

**Comment by einaregilsson** [comment]
Can you give me an example? I'm thinking if it's possible to do something smart with regular expressions to handle this case. I probably won't be adding a lot of features to this extension, it's pretty much in maintenance mode now.

**Comment by anewuser** [comment]
Redirect: `(.*?)(?:sid|ref_?)=\w+&?(.*)`
To: `$1$2`

Test URLs:

* http://forums.mozillazine.org/viewtopic.php?sid=6fa91cda58212e7e869dc2022b9e6217&f=48&t=1920191
* http://forums.mozillazine.org/viewtopic.php?f=48&sid=6fa91cda58212e7e869dc2022b9e6217&t=1920191
* http://forums.mozillazine.org/viewtopic.php?f=48&t=1920191&sid=6fa91cda58212e7e869dc2022b9e6217
* http://forums.mozillazine.org/?sid=6fa91cda58212e7e869dc2022b9e6217

The first two examples work perfectly, but the last two have the problem I mentioned. The only solution I've found is to create different rules depending on whether the string I want to remove is the first parameter or not.

**Comment by einaregilsson** [comment]
Well, you could probably get it all in one regex, but you'd have to just join three different cases together with a pipe |, so it wouldn't be any simpler than just creating multiple rules. But are the trailing ? and & actually causing problems?

**Comment by anewuser** [comment]
Those trailing characters don't break anything since web servers simply ignore them in those contexts. An ampersand could break a page without any previous URL arguments, but that's not the case.

Anyway, since I still wanted to get the cleanest possible URLs, I followed your suggestion and came up with this: `(.*?)(?:(?:sid|ref_?|src)=.*?&(.*)|\?(?:sid|ref_?|src)=[\w\-]+$|&(?:sid|ref_?|src)=[\w\-]+$)`

Here's a cool visualization of it provided by [Regexper](https://github.com/javallone/regexper-static#regexper):

![regex illustration](https://cloud.githubusercontent.com/assets/6733770/11314832/c20b6a44-8fd0-11e5-876e-7266b7d1a7ae.png)

**Comment by anewuser** [comment]
I was focused on the number 3 and didn't even think of this simpler solution: `(.*?)(?:(?:sid|ref_?|src)=.*?&(.*)|(?:\?|&)(?:sid|ref_?|src)=[\w\-]+$)`

![regex illustration](https://cloud.githubusercontent.com/assets/6733770/11315112/326fe6fe-8fd4-11e5-9f45-6c8dff950118.png)

**Comment by einaregilsson** [comment]
Nice job :) Thanks for sharing the solution!
