### ISSUE TITLE
Create toolbar button to enable/disable

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#5]
Currently, Redirector uses the deprecated statusbar to display its status and toggle the extension on/off.  If someone can make it a standard toolbar button instead, that would be wonderfully appreciated!

This way, a toggle (which also acts as a visual cue of the on/off state) can be added to the Navigation Bar and the new Menu Panel.

**Comment by Gitoffthelawn** [comment]
Einer fixed all of the major toolbar button issues in https://github.com/einaregilsson/Redirector/commit/4d9993f230c59f8a97767599b1d81eeeac3d35ec

Thank you SO MUCH Einar!

You can left-click on the button to toggle Redirector, or right-click on it to open the configuration tab!  Fantastic!

In the Firefox Menu Panel, the toolbar button is still a low resolution image, expanded to fit.  It doesn't look great, but is very functional.  If anyone wants to submit images, I'm sure Einar will include them.  If I get the time, I can create some images for the button, but unfortunately I don't have enough time right now.

Can anyone recommend a tool to create the button images?  We need to have them for enabled and disabled, as well as for different sizes.

**Comment by einaregilsson** [comment]
There is a new toolbar button with a better image in https://github.com/einaregilsson/Redirector/issues/30
