### ISSUE TITLE
Improve toolbar button

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#51]
When pressed, the Redirector toolbar/panel button brings up another menu in which the user has to select an option.

Here is a project with a similar initial UI requirement (user has a choice to enable/disable or perform another function), but handles it in a more elegant manner: https://github.com/muzuiget/user_agent_overrider

**Comment by einaregilsson** [comment]
Sorry, here I'm constrained by keeping compatibility with the other browsers. Maybe there will be a better way when the WebExtensions API is ready, for now I'm not changing this.

**Comment by Gitoffthelawn** [comment]
I had a hunch that was the reason behind the design choice... no problem.  :)
