### ISSUE TITLE
Base64 Decoding

### ISSUE THREAD

**Issue by Shem13** [einaregilsson/Redirector#52]
Is it possible to add a function to decode base64 urls e.g.

http://example.com/aHR0cDovL2dvb2dsZS5jb20=/

aHR0cDovL2dvb2dsZS5jb20= is http://google.com

thanks.

**Comment by einaregilsson** [comment]
Sorry, I don't want to add more options to this addon. It's complicated enough as is, with the escape/unescape options. This seems like a niche feature, so I won't be adding it.
