### ISSUE TITLE
Redirecting to a message

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#53]
In previous versions of Redirector, it was trivial to use javascript to display a message instead of redirecting to another URL.

For example, if a known website was incompatible with the browser, you could use javascript to display the message "Website Incompatible" instead of having the site fail.

Due to changes we have discussed that were necessary for the current version of Redirector, that is no longer possible.

What is the best way to accomplish this goal in the current version?

I thought perhaps `about:about Message` or `about:null Message` would at least be hacks show the message in the urlbar, but neither works.

The best I've come up with is `http://localhost/display: Message`.  This shows the message in the urlbar, but you have to wait for the localhost resolver to fail.

Is there a better way to do this?

**Comment by einaregilsson** [comment]
I don't think there's any great way to do this anymore, sorry. You could make a simple page somewhere that just displays a message from the url bar and redirect to that. E.g. if you had gitoffthelawn.github.io/message/?message=some-message and on that page you had some javascript to show the message you want.

**Comment by Gitoffthelawn** [comment]
Thanks.  I couldn't figure out a way to do it anymore either!

If I tried redirecting to a page, could it be a local one?

BTW, if anyone else has ideas, please don't hesitate to chime in!

**Comment by einaregilsson** [comment]
Local should be fine, anything that's on http.

**Comment by dieeisenefaust** [comment]
Can the 'to' redirect be updated to be able to direct it to a local file that you aren't hosting? I.E. I have a trivial little html file I want to redirect it to (file:///C:/index.html), so I don't want to have to be running a server just to host it.

**Comment by einaregilsson** [comment]
Sorry, the API I'm using now to redirect, which should continue to work in new Firefox versions, doesn't allow redirecting to anything other than http. I don't want to have a lot of Firefox specific code in this addon anymore, so file:/// won't be supported. Easiest for you is probably to just dump your file on github pages or some other free server you can use, given that your file isn't sensitive.

**Comment by Gitoffthelawn** [comment]
Einar, can you set up a page or two on GitHub to show example(s) of what you are talking about doing?

**Comment by einaregilsson** [comment]
See https://www.thinkful.com/learn/a-guide-to-using-github-pages/ for example, or just google Github Pages, they have some explanations. Basically just create a repo, create a branch called gh-pages in it and add an index.html file to that. E.g. my username is einaregilsson, if I create a repo called foobar and push a gh-pages branch to it, then my index file will be at http://einaregilsson.github.io/foobar/index.html

**Comment by Gitoffthelawn** [comment]
Thanks Einar!

**Comment by berrythesoftwarecodeprogrammar** [comment]
what about a data: uri? or do they have to be http urls

**Comment by einaregilsson** [comment]
I think they have to be http, but you can try a data uri and see if it works. I doubt it though.

**Comment by Gitoffthelawn** [comment]
@berrythesoftwarecodeprogrammar If you try it, let us know!  Thanks!

**Comment by berrythesoftwarecodeprogrammar** [comment]
yeah it works. i made a redirect for:
`(https?://.*)`
to
`data:text/html,<h1>Incompatible URL: $1</h1>`
and any url i entered showed that html instead

**Comment by berrythesoftwarecodeprogrammar** [comment]
read up about data: uris here https://en.wikipedia.org/wiki/Data_URI_scheme and you could use this tool to easily convert some html page you write into a data uri http://dopiaza.org/tools/datauri/index.php
probably better to choose the base64 option too as it will look cleaner and maybe use less space

**Comment by berrythesoftwarecodeprogrammar** [comment]
though i guess if you base64 encode the data beforehand you wont be able to use any of the parts of the regex if you need to (like i did with $1 in my example)

**Comment by Gitoffthelawn** [comment]
@berrythesoftwarecodeprogrammar You're a genius!  Thanks so much for those details and the example.  That's very clever.

**Comment by einaregilsson** [comment]
Nice job! And even cooler that you can use the $1 in the source of the page. Am closing this issue now, since this is a nice way to redirect to a message.

**Comment by Gitoffthelawn** [comment]
@berrythesoftwarecodeprogrammar Are you still able to use the data: uri trick?  I am unable to get it working in Firefox.

**Comment by berrythesoftwarecodeprogrammar** [comment]
@Gitoffthelawn  No. It tries to redirect and fails. Shows a blank page with this in the console:
`Navigation to toplevel data: URI not allowed (Blocked loading of: “data:text/html,<h1>Incompatible URL: http://google...”)`

Firefox has changed a lot. I'm on 68.9.0

Seems to be because of the FF preference `security.data_uri.block_toplevel_data_uri_navigations`. You can set it to false and it works again but I'm sure that would be bad for security.

**Comment by berrythesoftwarecodeprogrammar** [comment]
Redirecting to a local `file:///` URL doesn't work either. Only thing I can think of is running a local webserver and redirecting to that, but seems like overkill

**Comment by Gitoffthelawn** [comment]
@berrythesoftwarecodeprogrammar Your experiences and results are identical to mine.

I also tried a few "hacky" experiments, but none of them proved successful.

I thought of the local webserver idea too (overworked minds think alike), and I came to the same conclusion as you (overkill).

Currently, I'm using the address bar to deliver messages, but obviously that's far from ideal.

@einaregilsson Can you re-open this issue, so we can figure out a good solution?  Also, can we all come stay with you in Iceland during this pandemic?  I'll cook for everyone and maybe Berry can do the dishes. ;)
