### ISSUE TITLE
Verifying Redirector rules are correct and Redirector is functioning as expected

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#54]
For URLs that are loaded on the same tab, you can use Firefox's Network Monitor to verify that Redirector intercepts the URL and modifies it according to the appropriate rule.

But for URLs that are loaded into another tab, I can't get the Network Monitor to give me useful data.  The data in it seems to be tab-specific, and it does not start monitoring when the tab is initially loaded.

Is there a way to verify that Redirector rules are correctly working when links open new tabs?

**Comment by einaregilsson** [comment]
Not sure. There is plenty of logging in Redirector, if you turn it on maybe you can see it in the new tab.

**Comment by Gitoffthelawn** [comment]
Thanks.

The best I have found so far is the [HttpFox extension](https://addons.mozilla.org/firefox/addon/httpfox/).  It works great for this task, but it has not been updated recently and has some issues.

If anyone else knows how to get Firefox's Network Monitor to work across tabs, or knows of a more up to date extension, please post.

**Comment by anewuser** [comment]
@einaregilsson How to enable the logger?

**Comment by einaregilsson** [comment]
There's no good way to do that, unless you change the code. I turned the logging off after getting comments about it from the reviewer on AMO.

**Comment by anewuser** [comment]
Ah. I thought there was a way to enable it from the console.

**Comment by einaregilsson** [comment]
Closing this, logging should be enough for this.

**Comment by Gitoffthelawn** [comment]
If anyone's interested, this extension can help: https://addons.mozilla.org/firefox/addon/open-not-in-new-tab/

One limit, however, is that I doubt it works on JavaScript links.
