### ISSUE TITLE
Add the functionality to redirect bulk URL

### ISSUE THREAD

**Issue by musman2015** [einaregilsson/Redirector#57]
I suggest that redirector ad-on should have a functionality to redirect all URLs in a text file or from clipboard, should be changed(redirected) according to rules.

thanks in advance.

**Comment by einaregilsson** [comment]
Thanks for the suggestion, but Redirector is pretty much feature complete at this point. I have no plans to add new features to it, I'm just maintaining it so it works on new versions of Firefox.
