### ISSUE TITLE
Does not save settings in latest Nigthly

### ISSUE THREAD

**Issue by charlesmilette** [einaregilsson/Redirector#60]
![gif](https://cloud.githubusercontent.com/assets/6440374/15457106/4fd13f5a-2051-11e6-8689-39c20a7c830e.gif)
When you see the rule dissapear, it is because I pressed F5 to trigger a refresh. Exporting the rule to JSON and importing them gives the same result.

**Comment by Gitoffthelawn** [comment]
Thanks for reporting this issue.  What screen capture tool are you using?  It's very well compressed.

**Comment by charlesmilette** [comment]
I use [GifCam](http://blog.bahraniapps.com/gifcam/)

**Comment by Gitoffthelawn** [comment]
@charlesmilette Thanks!  And now back your issue...

**Comment by dogancelik** [comment]
It doesn't remember last state/settings also you can't disable/enable after clicking "Disable Redirector" once.

![animation 2](https://cloud.githubusercontent.com/assets/486818/15584389/1797aebe-2383-11e6-9d60-319611c9b1fe.gif)

**Comment by gregist** [comment]
same here, please fix.

**Comment by einaregilsson** [comment]
I'll try to get to this soon.

**Comment by Gitoffthelawn** [comment]
Also, when disabled, the toolbar button is not changing from the active to inactive image.

**Comment by Gitoffthelawn** [comment]
BTW, the nightly in which it was broken went to full mainstream release on August 2nd, so it's now broken in the Firefox release channel.

**Comment by einaregilsson** [comment]
I'll try to get the actual WebExtensions version out sometime this week, that should work now.

**Comment by Gitoffthelawn** [comment]
Thanks so much Einar.  Any idea of performance differences between the WebExtensions version and the current one?

BTW, just discovered that Mozilla hasn't added *WebExtensions* to their spelling dictionary... LOL.

Wow, now learned that *LOL* isn't in their spelling dictionary either.  Seriously.

**Comment by einaregilsson** [comment]
Well, I just uploaded version 3.1, which is the WebExtensions update. Hopefully it will be reviewed and approved soon. You can go to version history and try to install it already, but it didn't work for me, something about unsigned something. 

https://addons.mozilla.org/en-US/firefox/addon/redirector/versions/

Also, they complain that I'm using Angular 1, it might get banned soon, so I'm going to have to rewrite the Angular parts which is a pain in the ass :(

https://github.com/mozilla/addons-linter/issues/842

**Comment by Gitoffthelawn** [comment]
It got approved.

Have you had time to study http://www.slideshare.net/x00mario/an-abusive-relationship-with-angularjs ?

It's interesting that Mozilla approved Redirector v3.0.6, which used Angular v1.4.4, especially given https://github.com/mozilla/addons-linter/blob/master/docs/third-party-libraries.md

It sounds like you will have to move away from Angular, or at least update to 2.x within a few weeks, according to https://github.com/mozilla/addons-linter/issues/842#issuecomment-235610075 .

**Comment by einaregilsson** [comment]
Yeah, I can see that there could be some issues using Angular. I guess I'm just going to rewrite it in vanilla javascript, no framework. It's not really a lot of code, shouldn't be that hard. That will be my main project for v3.2 along with some minor Firefox tweaks.
