### ISSUE TITLE
Not working for right clicking links for "copy link address"

### ISSUE THREAD

**Issue by cyberbeat** [einaregilsson/Redirector#61]
It would be very useful for example for copying links from google-search-results

**Comment by einaregilsson** [comment]
Thanks for the feature request. I think it would be confusing if copying the link address would give the redirected address directly, and I don't have access to that menu item anyway. But if someone wants to add a custom right-click menu item, Copy redirected link address, or something like that, then I might consider adding that. It's not something I have time to do myself, but I would welcome a pull request with that feature.

**Comment by cyberbeat** [comment]
I meant: modifying the page, changing the anchors href values, no new pop-menu.

**Comment by einaregilsson** [comment]
Ok, now I see. Sorry, I don't want to add that feature. I prefer that it's extremely clear and simple what the addon does: it redirects pages based on patterns, it doesn't modify the pages themselves, or anything else.
