### ISSUE TITLE
[Feature Request] Add browser context menuitem to allow copying redirected link

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#62]
It would be useful to add a context menuitem to allow copying a link _after_ it has been processed by Redirector rules.

For example, a user may have a Redirector rule to redirect `http://foo.com/?*` to `http://$1`.  With this feature, if there was a link in a page to `http://foo.com/?bar.com`, this proposed additional context menuitem would allow the user to right-click on the link and copy `http://bar.com` to the clipboard.

It appeared like this was proposed in https://github.com/einaregilsson/Redirector/issues/61, but apparently that issue was for a different request.

In https://github.com/einaregilsson/Redirector/issues/61#issuecomment-223520590, Einar stated that he does not have the time right now to work on the feature requested in _this_ GitHub issue, but would **welcome a pull request from someone else** who does.

**Comment by einaregilsson** [comment]
No plans for this, we don't work at the UI layer.
