### ISSUE TITLE
Addon icon doesn't show options fully

### ISSUE THREAD

**Issue by grenzor** [einaregilsson/Redirector#64]
In Firefox latest version, the redirector icon on the tool bar only shows 'Disable Redirector' but cannot be scrolled down to show the 'Edit Redirects' option. May be something to do HiDPI that it is not showing all maybe not, please allow to scroll down to see all options.

Edit: But dragging is possible, so close if that is ok

**Comment by Gitoffthelawn** [comment]
Which operating system(s)?

**Comment by einaregilsson** [comment]
I can't reproduce this one, on a MacBook Pro Retina screen. I also have very little control over scrollbar in that popup, I just supply a html file and Firefox is supposed to take care of the sizing part.

**Comment by grenzor** [comment]
That's fine, I am guessing it is to do with HiDPI being used but since dragging is still possible I'll close this.
