### ISSUE TITLE
Add POST requests support

### ISSUE THREAD

**Issue by grenzor** [einaregilsson/Redirector#65]
Currently, Redirector can only redirect GET requests. Any chance for it to redirect parameters in POST requests?

**Comment by Gitoffthelawn** [comment]
Do you have any examples you can share?

**Comment by einaregilsson** [comment]
Closing this one. I have no plans to add POST support. For one thing it's not supported by the webRequest API that we are using. But I also just don't want to do it. POST requests can contain very sensitive information, passwords etc, and I don't want people to accidentally redirect them to the wrong site. I realize people should be careful, but but my experience tells me that they aren't, at all, so I'd rather just not venture into the sensitive information area... :)

**Comment by grenzor** [comment]
I see. I would think POST requests are more safe to redirect since unlike GET even if they are redirected to a different site for most sites POST requests won't get logged anywhere so there is no exposure of sensitive information.

**Comment by einaregilsson** [comment]
Well, GET requests shouldn't really have sensitive information in the url. Just out of curiosity, what's the use case for redirecting a POST request? You're posting to one site but really want it to go to another site?

**Comment by grenzor** [comment]
Sometimes there are parameters in POST which contain information that can be stripped out for privacy/usability sake and still work (e.g. geo timezone/country, referrer, screen size, remove params that set unnecessary cookies, change redirect after login link etc. etc.) . These use cases are just for within a single site (but I guess they work the same way when sites redirect using POST).

**Comment by vguna** [comment]
I would love such a feature as well :)!

My usecase is, that I would use it during development using angular. That would allow me to simply switch e.g. calls to the backend, to my local developer machine just with redirects - which is pretty cool. It works transparently with GETs already. But POSTs etc. go to the original site :(.

Regarding security, maybe it's an idea to make it a hidden option. Disabled per default. And @grenzor is right, GETs are logged by webservers, POSTs normally not. The chance, that a user sends sensitive information to the wrong side is very small I guess. If so, it's not the fault of the extension IMHO.

**Comment by einaregilsson** [comment]
Well, the first point still stands, I don't think the webRequest API supports redirecting POST requests, not with the POST data at least. I think it would just send a 302 and the request would be changed to a GET request. 

In any case, I don't have time to spend on adding new features to Redirector. But if someone were to add this feature, as an optional thing for each redirect then I'd accept the pull request.

**Comment by vguna** [comment]
I never implemented an extension - I guess I won't be much helper then :).

But meanwhile I took a look at https://chrome.google.com/webstore/detail/switcheroo-redirector-plu/eneklinboooejmebmgibifnhdnehgdja. It supports the POSTs, but has another problem with loosing content-types on redirect. I gave it a testdrive together with another extension which can set headers, which I use to re-add the missing header :). All in all it seems to work - but with Chrome only though.

What I want to say is, it seems possible somehow - at least with chrome. So in the end it would be an optional feature, that might be only available for chrome. Is that somehow possible with redirector? I mean, are there already functions that only work for specific browsers? Are there parts that can be done browser specific in redirector?

**Comment by einaregilsson** [comment]
Well, in Firefox I switched to the WebExtensions API, which is basically just copied from Chrome. But that means I can't access all the old Firefox API which allowed you to do pretty much whatever you wanted, which is why Firefox extensions were so powerful. They're deprecating the old way of writing extension, and will in the future only allow safe, sandboxed extensions that use the designated extension APIs.

There is probably a way to do this, but again, it won't be implemented by me. So, unless someone steps up and wants to do this I think you're out of luck.

**Comment by vguna** [comment]
Never mind. Thanks for your effort and providing such a nice extension!

**Comment by Gitoffthelawn** [comment]
If anyone is ever interested in implementing POST functionality, I would find it useful as well.

Perhaps as Firefox's WebExtensions API matures and gets more functionality, it will be easy.

**Comment by einaregilsson** [comment]
Closing this. Still think that POST redirects are a bad idea.

**Comment by Gitoffthelawn** [comment]
@einaregilsson If I'm reading this correctly, the WebExtensions API now supports POST requests:  
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/onBeforeRequest

Am I reading it correctly?

If so, would it be reasonably easy to finally add POST request functionality to Redirector?

I certainly understand and appreciate your hesitancy, but I keep coming across more and more web servers that will *not* accept GET requests for useful functions (and *do* accept POST requests).  From the comments in this issue report as well as some other issues, it appears to be a common request.

Although I don't really think it's required, enabling Redirector's POST functionality could be behind a toggle with a default of `disabled` and could even have a warning message (although that seems a bit excessive).  Another popular extension with advanced functionality, uBlock Origin (uBO), has a simple checkbox to enable all of its advanced functionality.  That technique seems to work well.

**Comment by andreasonny83** [comment]
I just opened a PR to allow redirects to be applied to POST requests as well: https://github.com/einaregilsson/Redirector/pull/408
