### ISSUE TITLE
Lost all redirects in upgrade to 3.0 (or Firefox ESR 45)

### ISSUE THREAD

**Issue by timmc** [einaregilsson/Redirector#66]
I recently upgraded Firefox ESR from 38 to 45, and at the same time received an upgrade for Redirector (I think from 2.x to 3.x). Now all my redirects are gone!

Are they still somewhere I can retrieve, or will I have to recreate all of them? Where would the old settings be?

**Comment by timmc** [comment]
OK, looks like the old settings are in redirector.rjson in my Firefox profile...

**Comment by einaregilsson** [comment]
Glad you found the old redirects. There was supposed to be an automated upgrade but that must have failed for some reason.
