### ISSUE TITLE
[Feature Request] Re-enable when browser starts option

### ISSUE THREAD

**Issue by PrototypeNM1** [einaregilsson/Redirector#67]
I normally use this plugin as a way to prevent me from becoming distracted when trying to be productive. Unfortunately, I also normally forget to re-enable it after having disabled it.

The most logical time I can think of having the app auto re-enable is when Firefox has been restarted.

**Comment by PrototypeNM1** [comment]
I'd be open to investigating this if it's a feature you'd consider adding to the plugin.

**Comment by einaregilsson** [comment]
Thanks for the suggestion, but I'm afraid I'm going to turn it down. I don't think it's normal behaviour to re-re-enable something that the user has explicitly disabled. There is an icon in the toolbar that shows that the addon is disabled, I think that's the most natural way to show the user the state of the addon.

**Comment by Gitoffthelawn** [comment]
Many users probably put the toolbar icon inside the app menu (aka hamburger menu), and thus the Redirector state is not visible unless the user opens that menu.

**Comment by einaregilsson** [comment]
Even so, I don't think it's normal behaviour to automatically re-enable something the user has explicitly disabled.

**Comment by Gitoffthelawn** [comment]
I agree.  But it would make a useful option.  Occasionally, I forget that I turned off Redirector and wonder why nothing is working correctly.

**Comment by einaregilsson** [comment]
I don't like having too many options. Every option is an extra thing that needs to be tested before every release. At the minimum this issue would need a bunch of +1s for me to consider including it.

**Comment by Gitoffthelawn** [comment]
+1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1  +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1 +1
    :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by Gitoffthelawn** [comment]
Minimum requirement met, I believe.  :-)

Just couldn't resist. ;-)

**Comment by einaregilsson** [comment]
:)

**Comment by Gitoffthelawn** [comment]
I was thinking that a workaround could be as simple as adding a `user.js` item to enable Redirector.

That would have been easy in the old version.  Where is Redirector currently saving its enabled/disabled state?

**Comment by einaregilsson** [comment]
It's stored in a storage.json file in a browser-extension-data in the profile folder. That's where WebExtensions keep their storage stuff.

**Comment by Gitoffthelawn** [comment]
LOL... I found it.  You used the word *disabled* for individual rules and the entire extension!

When I used a formatter to match up all the braces and brackets, I found the extra *disabled* at the end.

Well, if an *enabled* pref is added to `prefs.js`, it could be forced via `user.js`.  It looks like Redirector still stored some prefs in `prefs.js`.  Or are all those orphans at this point?

**Comment by einaregilsson** [comment]
Those are all orphans, everything should now be stored in the extension storage area.

**Comment by Gitoffthelawn** [comment]
Thanks Einar.  Before I purge all of them, I want to verify with you that every one of these is an orphan:

> extensions.redirector.showContextMenu
  extensions.redirector.showStatusBarIcon 
  extensions.redirector@einaregilsson.com.sdk.baseURI 
  extensions.redirector@einaregilsson.com.sdk.domain
  extensions.redirector@einaregilsson.com.sdk.load.reason
  extensions.redirector@einaregilsson.com.sdk.rootURI
  extensions.redirector@einaregilsson.com.sdk.version

**Comment by einaregilsson** [comment]
No, those are internal Firefox stuff, not something that Redirector uses directly. Something to do with extension installation I guess. Don't delete those.

**Comment by Gitoffthelawn** [comment]
That's what I thought.  But the first two are orphans, right?

**Comment by einaregilsson** [comment]
Ah, yes, didn't notice them because they didn't get highlighted. Yes, those are orphans, you can delete them.

**Comment by Gitoffthelawn** [comment]
Thanks Einar.  GitHub apparently doesn't do enough validating when highlighting what looks like email addresses! :-)
