### ISSUE TITLE
Alternative button for dark themes

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#68]
I'm using a dark theme on Firefox, and it's hard to see your extension button with it (especially at low brightness). Please consider providing a toggle to use a light icon instead of the default one.

![screenshot_20160702](https://cloud.githubusercontent.com/assets/6733770/16543490/b2eb1a8a-40ad-11e6-83b2-2984235eb32c.png)

I usually leave the Redirector button on the main menu. If I put it back there, it is basically invisible with the current theme:

![screenshot_20160702-3](https://cloud.githubusercontent.com/assets/6733770/16543539/66201b90-40af-11e6-89ae-8a27cf13f2f4.png)

**Comment by einaregilsson** [comment]
Sorry, I probably won't do this one myself, but I'll leave it open if someone wants to do the graphics work and contribute a pull request.

**Comment by anewuser** [comment]
You don't need to create different images. This can be done by using CSS filters. I created these rules and added them to my userChrome.css:

    toolbarbutton[label="Redirector"][image*="active"]{filter:invert(100%) brightness(600%);}
    toolbarbutton[label="Redirector"][image*="disabled"]{filter:invert(100%) brightness(250%);}

Anyway, it seems that you'd really have to create different images and a toggle to achieve that the current restartless APIs.  I can't expect that from all developers since Mozilla developers themselves care about advanced personalizations anymore.

https://bugzilla.mozilla.org/show_bug.cgi?id=990477

**Comment by einaregilsson** [comment]
That's a nice hack :) But yeah, this extension is also switching over to the WebExtensions API and I don't think there's any way to detect this there anyway.
