### ISSUE TITLE
Make popup slightly larger (popup shows scrollbars)

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#69]
I'm using KDE Plasma 5.6.5 with the dark variation of the default theme. The popup windows of all extensions are displayed correctly at my screen resolution, except for Redirector.

![screenshot_20160702-1](https://cloud.githubusercontent.com/assets/6733770/16543530/ea931fd6-40ae-11e6-98b0-0902b8b764f4.png)

**Comment by einaregilsson** [comment]
That's weird. You don't really size the popup explicitly, Firefox is supposed to figure this out itself. I'll try to look into this before the next release, but I have no specific date for that yet, I basically work on Redirector once every few months :)

**Comment by Gitoffthelawn** [comment]
I wonder if it could possibly be a DPI issue.

**Comment by anewuser** [comment]
@Gitoffthelawn The matter is that similar popups have the correct size:

![screenshot_20160703](https://cloud.githubusercontent.com/assets/6733770/16548413/66f02ffa-4164-11e6-8284-398f350f03b7.png)

After forcing it to 96 DPI (at 1366x768):

![screenshot_20160703-1](https://cloud.githubusercontent.com/assets/6733770/16548416/78cec9a2-4164-11e6-9a76-5ed0f68ab05a.png)

**Comment by anewuser** [comment]
DUPLICATE: #58 

Somehow I missed this.
