### ISSUE TITLE
Visual feedback when rule is applied

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#72]
There needs to be a way for users to know when requests have been manipulated. Since there's no feedback about applied rules, we need to figure out by ourselves when and which of our rules is breaking  something. That can be a burden when you have other add-ons more likely to cause problems.

For example, you could add a small icon over the extension button if a request has affected the current tab.

Ideally, there would also be a logger similar to the one on uBlock Origin for us to see a history of redirections. It works only when you explicitly  open them, so https://github.com/einaregilsson/Redirector/issues/54#issuecomment-215402317 wouldn't be an issue.

**Comment by einaregilsson** [comment]
A logger sounds like a good idea, I might well implement that when I work on Redirector next. Maybe just keep the last 1000 redirects around to look at or something like that.

I did try the number overlay on the toolbar icon at one point, but it caused some issues in Chrome, I had to throttle it I think, I don't remember exactly. Might look into it again at some point.

**Comment by anewuser** [comment]
Thank you. For reference when/if you get back to it: 

* http://stackoverflow.com/a/19839880
* https://developer.chrome.com/extensions/browserAction#method-setBadgeText

**Comment by Gitoffthelawn** [comment]
I like all these ideas.  At the same time, please keep speed and efficiency as a top priority!

**Comment by einaregilsson** [comment]
Cool. As you've noticed, Redirector isn't really a priority for me. I like to go back to it once in a while, but it's essentially in maintenance mode and has been for years now.  Glad you found something that works for you :)

**Comment by Gitoffthelawn** [comment]
@anewuser Out of curiosity, do you experience any *performance* (not functionality) differences between Redirector and Request Control?

**Comment by Gitoffthelawn** [comment]
@gkrishnaks Thank would be fantastic!
