### ISSUE TITLE
Redirect to another web browser?

### ISSUE THREAD

**Issue by Sopor-** [einaregilsson/Redirector#73]
I was trying to find a redirect that could redirect domain/pages to another web browser but i didn't manage to do that in your Redirector. Maybe it is not possible to do it? If so, it would be very nice if you could add this feature :)

**Comment by Gitoffthelawn** [comment]
One way to accomplish this is to define another protocol in the OS, and have it load all URI's for that protocol in another browser.  That browser will then have to use a redirector to convert that arbitrary protocol back into something the browser recognizes.

**Comment by einaregilsson** [comment]
Thanks for the suggestion, but I'm gonna have to say no. This would be a complicated feature, different on different operating systems, and I just think it's outside the scope of Redirector.
