### ISSUE TITLE
Using small toolbar images in panel

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#74]
Redirector is using `icon-active-19.png` and `icon-disabled-19.png` (instead of the larger versions) in the Firefox menu panel, causing the icons to be blurry.

**Comment by einaregilsson** [comment]
That's weird. Maybe Firefox wants different sizes? Anyone know?

**Comment by anewuser** [comment]
The blurry icon:

![screenshot](https://cloud.githubusercontent.com/assets/6733770/17550884/8cfc5e90-5ecd-11e6-9a97-de3c039c8273.png)

**Comment by einaregilsson** [comment]
Thanks, I'll try to figure out what sizes they want.

**Comment by einaregilsson** [comment]
Should work now.
