### ISSUE TITLE
Add enabled/disabled attribute to toolbar button

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#75]
When implementing custom CSS for the Redirector toolbar button, to detect whether or not Redirector is enabled or disabled, the CSS has to look at the source of the button's image.  Would you mind adding a simple `attribute` to the button to make it simpler to detect the enabled/disabled state of the extension?

**Comment by einaregilsson** [comment]
What, like a data-attribute? Is this css something I could just do in the extension itself?

**Comment by Gitoffthelawn** [comment]
Correct.  For example, the button currently has a `tooltiptext` attribute of "Redirector".

Regarding doing the CSS in the extension itself, absolutely.  One of the enhancements you would probably want to include by default, and the other perhaps be an option.  The intention of both items is to make it more clear when the redirect functionality within Redirector is disabled.

Here is the CSS I've been injecting:
`#redirector_einaregilsson_com-browser-action[image*="disabled"] { background-color: red !important; }`

`#redirector_einaregilsson_com-browser-action[image*="disabled"] > .toolbarbutton-multiline-text::after { content: " (Disabled) "; }`

The first declaration obviously needs to remain a CSS declaration.  The second declaration would be even better if it was included within the HTML itself.

**Comment by einaregilsson** [comment]
Can you send me a screenshot of what this looks like for you? I'm probably not going to want a red background color, but I can definitely add an attribute that would make this easier. What attribute would you like? data-disabled="1" ?

**Comment by dogancelik** [comment]
A badge would be also beneficial visually.

![off](https://cloud.githubusercontent.com/assets/486818/20211713/5d666174-a808-11e6-8390-bb948c02bd9e.png)
![on](https://cloud.githubusercontent.com/assets/486818/20211712/5d64d282-a808-11e6-8391-3912f67b849c.png)

**Comment by einaregilsson** [comment]
That looks kinda nice. I might implement that whenever I work on Redirector next (which might not be for several months :) )

**Comment by einaregilsson** [comment]
Off/on red/green bade is added in version 3.5 which will be out in a couple of days.
