### ISSUE TITLE
Delay before opening popup

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#76]
The 3.1.0 update fixed #58 for me, but the popup now takes 2 seconds to open.

Also, launching Firefox from a terminal gives the following warning, which may be related to the delay:

> addons.webextension.redirector@einaregilsson.com        WARN    Please specify whether you want browser_style or not in your browser_action options.

**Comment by einaregilsson** [comment]
I don't see this delay here, it shows up almost immediately. Do you always get the 2 second delay, or just the first time? Are you using Windows?

**Comment by anewuser** [comment]
Linux with KDE Plasma 5.7.3. The thing is that other extensions, such as uBlock Origin, draw the popup first, and then fill it with their contents. Redirector, on the other hand, preloads the popup contents before opening it, which gives the impression that it takes longer to open than other popups.

See the difference: http://s1.webmshare.com/RAqx7.webm

**Comment by einaregilsson** [comment]
I don't think that warning has anything to do with that in particular. But I am planning on changing the code a bit, removing the Angular library which they're saying won't be supported much longer, so hopefully I can speed it up a bit then. And I'll also look into the warning, I just don't think it has much to do with this particular issue.
