### ISSUE TITLE
Two ambiguous "disable" buttons on addon page

### ISSUE THREAD

**Issue by anewuser** [einaregilsson/Redirector#77]
Firefox users who open the Redirector 3.1.0 page on `about:addons` will see two "disable" buttons to disable Redirector:

![screenshot](https://cloud.githubusercontent.com/assets/6733770/17487176/162e20e6-5d6a-11e6-844a-8ded467e5397.png)

The first one just disable the rules, while the second on disable the browser extension completely. To avoid ambiguity, I suggest you to rename the "Disable Redirector"  button to "Disable redirects", which is more technically appropriate, since the extension stays active from the browser's point of view.

**Comment by einaregilsson** [comment]
Yeah, that sounds like a good compromise. I'll try to make some changes there in the next version, 3.2

**Comment by dogancelik** [comment]
Suggesting "Disable rewrites"

**Comment by einaregilsson** [comment]
Good idea, although I would probably call it Disable redirects instead of rewrites. Will try to put it into the next release.
