### ISSUE TITLE
Redirector v3.1.0 isn't working.

### ISSUE THREAD

**Issue by matreex** [einaregilsson/Redirector#78]
Redirector is not working when v3.1.0 and requestpolicy continued v1.0beta12.3 were installed on firefox v48.0 at the same time.
If requestpolicy continued is installed, v3.1.0 will not save rules, but v.3.0.6 be working. please fixed, thanks.
Regards.

**Comment by einaregilsson** [comment]
Try updating to 3.2.

**Comment by anewuser** [comment]
@matreex Use the button below the comment form to close this issue if updating the extension solved it.

**Comment by anewuser** [comment]
@einaregilsson Actually, 3.2 seems to have been removed from https://addons.mozilla.org/firefox/addon/redirector/versions/

**Comment by einaregilsson** [comment]
Sorry, I was talking about from 3.0-3.1, I was confused.  Anyway, someone (you?) just sent me this workaround:

> This isn't your problem but it may help with bug reports...
> 
> I just noticed that the new Redirector wasn't working for me in Firefox 48.  On the Redirector page the list of redirections was empty and new redirections weren't saved.  Refreshing the page cleared the list.
> 
> I eventually discovered that the RequestPolicy Continued addon was blocking Redirector's background scripts.  This wasn't entirely obvious because everything happens in the background (necessarily) so the usual RequestPolicy notification was missing.
> 
> The solution is to add an "Allow" rule to RequestPolicy Continued with the following settings:
> 
> Origin scheme: about
> Destination scheme: moz-extension
> Destination host: d5ea2b2d-5bf6-4e80-8946-4a0c3f0bc9e7
>

**Comment by Gitoffthelawn** [comment]
What's the story with 3.2?

**Comment by einaregilsson** [comment]
There was no version 3.2, I just confused the version numbers. I meant he should update to 3.1, which he was already on.

**Comment by anewuser** [comment]
@einaregilsson No, I don't use RequestPolicy.

**Comment by Gitoffthelawn** [comment]
> There was no version 3.2, I just confused the version numbers. I meant he should update to 3.1, which he was already on.

Thanks.  Though I was losing my marbles.

**Comment by einaregilsson** [comment]
Closing this since there's a workaround, which is to add rules to RequestPolicy. See my comment in the thread above.

**Comment by matreex** [comment]
I'm so sorry for closing, because I havn't login github, so #78 can't be closed, sorry again.
well...
I'm beginning to test.
<a href="http://imgur.com/x5YiSmO"><img style="max-width:100%;" src=http://i.imgur.com/x5YiSmO.png"></a>
<a href="http://imgur.com/gNUv7Am"><img style="max-width:100%;" src=http://i.imgur.com/gNUv7Am.png"></a>
<a href="http://imgur.com/AYNz8OY"><img style="max-width:100%;" src=http://i.imgur.com/AYNz8OY.png"></a>
<a href="http://imgur.com/wSxAotz"><img style="max-width:100%;" src=http://i.imgur.com/wSxAotz.png"></a>
<a href="http://imgur.com/mFICKXu"><img style="max-width:100%;" src=http://i.imgur.com/mFICKXu.png"></a>
<a href="http://imgur.com/dOr2MSW"><img style="max-width:100%;" src=http://i.imgur.com/dOr2MSW.png"></a>
1. I delete all profiles of firefox, and starts firefox (v48.0), installed noscript, ublock, umatrix, requestpolicy.
2. add allow rule to requstpolicy.
3. search keywords "moz-extension", and confirmed, the rules had be added to allowable-list.
4. restart firefox.
5. add a rule to redirector v3.1.0, and saved.
6. reload "moz-extension://b2fb3128-d26e-490e-94d6-3ddfb90cb30a/redirector.html", but the rule havn't be saved, i don't know why, so i will keep v3.0.6. :(

**Comment by matreex** [comment]
I'm so sorry for closing, because I havn't login github, so #78 can't be closed, sorry again.
Thank you so much for @einaregilsson , done. :+1:
