### ISSUE TITLE
Allow arbitrary callback for URL rewrite

### ISSUE THREAD

**Issue by lolilolicon** [einaregilsson/Redirector#79]
Just discovered Redirector today. Very nice project. Thanks.

However, Redirector seems to only support URL rewrite by way of wildcard/regexp + backref, which is a bit restrictive sometimes. This is very similar to the way [HTTPSEverywhere rulesets](https://www.eff.org/https-everywhere/rulesets) work. Redirector does have the advantage of supporting URL encoding/decoding.

But why stop there? Why not open up the interface a bit more, and let the user rewrite the URL in any way they want? For example, URLs like Google's can get really long with all the params and hashes in some random order, at which point regexp just won't cut it.

Wouldn't it be much nicer if Redirector supports arbitrary callback for URL rewrite, such as,

```
function (url) {
  var u = new URL(url);
  u.searchParams.delete('client');
  u.searchParams.append('safe', 'off');
  return u.toString();
}
```

And perhaps, just like the rewriter, the matcher can be opened up in the same way.

**Comment by einaregilsson** [comment]
It would be nice, but honestly, for the vast majority of cases the regex solution is enough. I'm not really planning to add a lot of more features at this point, this extension is pretty much in maintenance mode now.

**Comment by lolilolicon** [comment]
Sure, I understand. At least an idea to come back to should you find the interest & time in the future. I'll just leave this issue open then? Is that OK?

**Comment by einaregilsson** [comment]
Yeah, leave it open. If there is a lot of interest in it I'll reconsider, but essentially this addon is finished, I wrote it almost 10 (!!) years ago, I'm just updating it to work with newer versions now.

**Comment by byzod** [comment]
Please add this feature, as some redirection need modification that RegEx can't do.

Example:
Source URL: `SiteA.com/PostId-440.html`
Redirect to: `SiteB.com/PostIdThatIsAlwaysGreaterThanSiteA-447.html`
* Assume that the post id on site B is always 7 greater than related page on site A. (440 -> 447, 100 -> 107, etc)

This can NOT be done (at least, easily) with regular expressions

**Comment by einaregilsson** [comment]
I think if you have more complicated needs than what Redirector supports then you're probably better off writing your own extension that just does exactly what you want. I'm not even sure extensions are allowed to call `eval(code)`.

If you want to make a basic extension that just redirects a specific url and nothing else you can get it done in about 10 lines of code.

**background.js**
```
var filter = { urls:[["https://*/*", "http://*/*"], types: ["main_frame"]};
//You could even start the filtering here in urls, and add extra types in types as needed

chrome.webRequest.onBeforeRequest.addListener(function(details) {
    if (details.url ... your match logic here) {
        return { redirectUrl: 'your redirect url' };
    }
    return {}
}, filter, ["blocking"]);
````

**manifest.json**
```
{

  "manifest_version": 2,
  "name": "MyRedirector",
  "description": "bleh",
  "version": "1.0.0",
  "permissions" : ["webRequest", "webRequestBlocking", "http://*/*", "https://*/*"],
   "background": {
    "scripts": ["background.js"],
    "persistent": true
  },
}
```

**Comment by byzod** [comment]
@einaregilsson thanks for your advice, I think parse user function by `new Function(userFunctionRule)` is working too?

I know the moment you need this feature is extremely rare but I still you can add it if you can  spare some time or feels boring, because it's cool  lol

**Comment by einaregilsson** [comment]
I have basically 0 time for this extension, so I'm not planning on adding any more features. Basically just keeping it running for the people that still use it :)

**Comment by welwood08** [comment]
@lolilolicon and anyone finding this thread in the future, I believe the example in the original post can be achieved using the [Request Control](https://addons.mozilla.org/addon/requestcontrol/) addon, which I only found after subscribing to this thread while I was looking for a webext replacement for CleanLinks. It matches params for filtering individually (ordering doesn't matter) and supports applying multiple filter and redirect rules for a single URL (i.e. filter to trim "client" param followed by redirect to append "safe" param).

**Comment by Gitoffthelawn** [comment]
Einar, did you want to close this, or keep it open in case someone else wants to implement it?

**Comment by einaregilsson** [comment]
Close it, it has security implications and stuff, so I don't really want to add it, even if someone else implemented it.
