### ISSUE TITLE
Rewrites redirector.rjson during every Firefox session

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#8]
Even when no Redirector rules are changed, the file redirector.rjson is re-written during every Firefox session.  Note that the date/time changes within that file after each session.

As a small aside, the wrong version of Redirector is indicated within the header of redirector.rjson.

**Comment by einaregilsson** [comment]
Thanks for letting me know. I'm not really working on Redirector anymore. If I ever get back into it I'll try to look at this :)

**Comment by Gitoffthelawn** [comment]
Thanks Einar!  Any idea if Redirector will work with the new multi-process Firefox that is on the development train?  I haven't found any other extensions even close to the functionality of Redirector.

**Comment by einaregilsson** [comment]
No idea. But I know that Redirector uses interfaces that are used by a lot of other addons, e.g. ad blockers and the like, so I think they'll tree to keep breakage to a minimum, hopefully it'll just keep working.

**Comment by Gitoffthelawn** [comment]
Hopefully!  Thank you!

**Comment by einaregilsson** [comment]
Will be fixed in https://github.com/einaregilsson/Redirector/issues/30 , redirects will be stored in chrome.storage from now on.
