### ISSUE TITLE
Add option to automatically enable Redirector when browser starts

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#80]
Redirector for Firefox previously stored preferences in `prefs.js`.  As you know, that was recently changed.

When `prefs.js` was used, it was easy to ensure that Redirector was enabled when the browser was started.  It was as simple as adding a single line to `user.js`.

With `prefs.js` no longer being used, this technique no longer works.

Can you add the ability for Redirector to ensure it is enabled when the browser starts?

Thanks for everything you do Einar. :+1:

**Comment by einaregilsson** [comment]
Sorry, but no, that will never be a feature. I'm against reverting something that the user has done on startup. If the user has disabled Redirector then it will always be disabled until the user explicitly enables it again.

**Comment by Gitoffthelawn** [comment]
Ok... what about just an option?

**Comment by einaregilsson** [comment]
No, I don't like adding too many options. I'm sorry to say no again and again, but I am just against this feature on principle, I don't like options resetting to what I haven't chosen.

**Comment by Gitoffthelawn** [comment]
No problem... I should be able to write a script to toggle the appropriate byte within the Redirector database and then have the script run when the browser launches (or terminates).

BTW, I agree with your principle.  On the other hand, unless the Redirector button is in the toolbar (which has limited size), there is no visual cue to indicate whether it is enabled or disabled.  Sometimes I need to temporarily disable Redirector, and I think it would be useful to have it only disabled until I terminate the session.  It's a similar idea as the browser's *Keep until I close Firefox* option for cookies.

Come to think of it, that's the real option: "Disable until I close Firefox".  Then it won't be going against what you've chosen! :smile:

**Comment by einaregilsson** [comment]
Still no :)

**Comment by Gitoffthelawn** [comment]
Okay :)
