### ISSUE TITLE
Question... 

### ISSUE THREAD

**Issue by mikhoul** [einaregilsson/Redirector#81]
I found your addon when I was browsing for some addon or Userscript to redirect Javascripts (badscript.js) to another script local or external and  I found this thread: https://github.com/gorhill/uBlock/issues/1220 talking about your addon.

My question is does your addon can do that simply ?    Intercept a script before it is executed and redirect it to another script of my choice (local or on a server).

If no, do you know any addon or script that do that on Firefox ?

Best Regards 😺

**Comment by einaregilsson** [comment]
Yes, you should be able to do that. Something like this should do the trick:

<img width="687" alt="screen shot 2016-09-20 at 21 31 52" src="https://cloud.githubusercontent.com/assets/557149/18689649/c82443da-7f79-11e6-9d5d-0be27f24cba6.png">

I haven't tried it myself though, and I don't know if browsers allow scripts to be redirected, but I'd guess that it works, you'll have to try it and report back :)

**Comment by mikhoul** [comment]
Thanks a lot for the fast reply  :+1:  

I will give it a try cause it could save me lot of time with some custom scripts  😊

Do you know if it should work too with "_behind the scene_" request ?

Have a great evening !  🌛

**Comment by einaregilsson** [comment]
I'm not sure what you mean by "behind the scene" request. I'm guessing the "script" category applies to files loaded from the src="" attribute of <script> tags, but it might also be based on mimetype or something, I'm just not sure.

**Comment by mikhoul** [comment]
That's the request made by the browser itself or addons for various task like request to update addons components or the browser itself.


Have a nice day !  😺
