### ISSUE TITLE
Sync cross browser

### ISSUE THREAD

**Issue by ivysrono** [einaregilsson/Redirector#82]
Sync via onedrive/dropbox/googledrive between chromes and operas and firefoxs
For example:
Violentmonkey, Tampermonkey.

**Comment by einaregilsson** [comment]
Thanks for the suggestion. That's unlikely to happen unless someone else writes it and sends a pull request, I'm not really adding features to this extension any more. I'll leave this issue open in case anyone is interested in taking it on.
