### ISSUE TITLE
FR: Bring working with GET parameters to the next level

### ISSUE THREAD

**Issue by Drugoy** [einaregilsson/Redirector#83]
[Wiki](https://en.wikipedia.org/wiki/Uniform_Resource_Locator) says that URL consists of:
scheme:[//[user:password@]host[:port]][/]path[?query][#fragment]

Where _query_ is:
> An optional query, separated from the preceding part by a question mark (?), containing a query string of non-hierarchical data. Its syntax is not well defined, but by convention is most often a sequence of attribute–value pairs separated by a delimiter.

Query delimiter | Example
---------------- | ---------
Ampersand (&) | key1=value1&key2=value2
Semicolon (;) | key1=value1;key2=value2

I'd like to be able to work with those key-value pairs (GET parameters) via a more handy way, regex just won't help here.
If user wants to work with GET parameters in a more advanced way - he first has to show where they are in the URL and what query delimiters shall be used.

Then there should be options to:
- always forge/force values for specific parameters (by their key name, and only if they exist);
- always remove specific parameters (by their key name);
- always add specific parameters (user has to mention both key and value for each pair);

These options should be duplicable, so that a user could specify multiple sub-rules for a single redirect.

> If user wants to work with GET parameters in a more advanced way - he first has to show where they are in the URL and what query delimiters shall be used.

This actually raises another problem: generally, for regular valid URLs the position of parameters can be guessed automatically, but it can't be guessed for links like
https://iamspyingonyou.evil/https%3A//www.google.com/search%3Fq%3Dmy+google+query%26hl%3Den%26lr%3Dlang_en&non-google-url-param=still-evil
where ``search%3Fq=my+google+query%26`` part is related to the URL hidden behind the evil redirector ``iamspyingonyou.evil`` and ``&non-google-url-param=still-evil`` is the query related to the evil redirector, and not to the URL hidden by it.
Also, as you see, the inner URL needs to be decoded first (``%3F`` is [urlencoded](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) ``?``, ``%3D`` is ``=`` and ``%26`` is ``&``), before the add-on can work with them.

**Comment by Drugoy** [comment]
Why do I request this? Because I hate that sites add tracking parameters to the query in the URL.
Even just sharing with a friend a simple google search link may tell google which nodes have connection in real life or what site I was visiting when I clicked the link.
I got tired of manually removing tracking crap from URLs before I can share them with my pals. Also, the tracking / non-essential crap in the URL may make too damn long.

**Comment by einaregilsson** [comment]
Hi @Drugoy and thanks for the suggestions. However, I have to tell you that this will probably never be implemented. First of all because I'm not really working on this add-on anymore, mostly just keeping it alive for the existing users. And second, I think the interface is already complicated enough, adding the necessary UI to remove and add query parameters, specify delimiters and work with the parameters in other ways would complicate things a lot. 

If someone wants to take a stab at this, then I think the best move would be for them to fork the code and make their own add-on based on it. It might even make more sense to use Redirector as a template and just make an add-on that's only used for removing parameters from urls, not try to offer everything in one add-on.

**Comment by Drugoy** [comment]
Oh, that's a shame.

As for complexity of the current UI - I wouldn't say it's complex: I figured things out quite instantly (luckily I know PCRE well enough to make full use of regex-based rules).

I hope it's okay to leave this issue opened.

p.s.: thanks for this awesome add-on anyways!

**Comment by einaregilsson** [comment]
Sure, I'll leave it open, maybe someone else will want the same thing and offer to work on it :)

**Comment by einaregilsson** [comment]
Haven't had any more requests for this and it would complicate the UI, so am closing it.
