### ISSUE TITLE
Add option to automatically sync settings between devices

### ISSUE THREAD

**Issue by dkaksl** [einaregilsson/Redirector#86]
Related: #3

**Comment by anewuser** [comment]
https://github.com/einaregilsson/Redirector/issues/82

**Comment by Gitoffthelawn** [comment]
Hmmm... OP of #82 closed that issue, so either this one can remain, or that one should be re-opened.

**Comment by einaregilsson** [comment]
Just leave this open.

**Comment by lolalalol** [comment]
+1
it will be nice

**Comment by anewuser** [comment]
@lolalalol When you find a post on Github you agree with, please use the reaction button instead of adding pointless "+1" comments that just generate useless notifications to other people.

**Comment by Gitoffthelawn** [comment]
@anewuser Ugh... you just generated another notification to everyone with your post.

Lol... so did I.

**Comment by gkrishnaks** [comment]
@einaregilsson  Since Firefox and Chrome both support StorageArea SYNC now, I am thinking about sending a PR with chrome.storage.local --> chrome.storage.sync.

**Comment by Gitoffthelawn** [comment]
@gkrishnaks Would that be an option to sync, or a forced sync?  I'd like to see it as an option, but not a requirement.

**Comment by gkrishnaks** [comment]
Ok, I will look into this soon and try to send PR.
Good idea to default to Local, provide a switch to use Sync if one wishes.

**Comment by Gitoffthelawn** [comment]
@gkrishnaks It sounds like you have thought things out well. :)

Regrettably, I don't have time in my schedule to test it right now or during the next couple of weeks.  I'm sorry.

**Comment by einaregilsson** [comment]
@gkrishnaks Please make a pull request, then I'll try to review this next week :)
