### ISSUE TITLE
Add option to allow more include/exclude patterns

### ISSUE THREAD

**Issue by grenzor** [einaregilsson/Redirector#88]
Currently, it is possible to add 1 Include/Exclude Pattern for each redirect. 

Is it possible to add a way such as a + button next to Include/Exclude Pattern so the user can add more include/exclude patterns when needed?

**Comment by Gitoffthelawn** [comment]
You can currently accomplish this using the `or` regex operator.  It is represented by the pipe symbol.

**Comment by einaregilsson** [comment]
Sorry, I don't really want to complicate the UI any more, it's plenty complicated as is. And as @Gitoffthelawn  points out, you can achieve the effect by OR-ing regular expressions together.
