### ISSUE TITLE
I've done some significant work on Redirector!

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#9]
Hi Einar!

I've done some major work improving the GUI.

The changes substantially improve usability.  Plus, the description of each rule is finally visible!

How would you like me to get the new files to you?

BTW, if anyone would like to code a toolbar button, that would be great!

**Comment by einaregilsson** [comment]
Hi

Can you post a pull request here? Or if you don't know how to do that you can also just zip up the files and send that to me directly.

**Comment by Gitoffthelawn** [comment]
My first pulls on Github!  All done!

Thank you again for Redirector.  I can't imagine using the web without it.

**Comment by Gitoffthelawn** [comment]
Thanks again Einer!  The changes got distributed via AMO the very next day.

I added some feedback/comments/discussion in the pull/merge section for you.  I await your feedback to my feedback. :-)

**Comment by Gitoffthelawn** [comment]
I just made a pull request, with a few comments, but please note that the majority of the comments were in the previous pull requests.

**Comment by einaregilsson** [comment]
Discussion is in pull request.
