### ISSUE TITLE
how to create an icon for enable/diable redirector

### ISSUE THREAD

**Issue by sant527** [einaregilsson/Redirector#91]
I have installed redirector for firefox.

I am very happy using it. 

Can i have an icon to toggle enable/diable redirecto, because now i have to first click on the icon, then it shows the option, then i select the diable or enable redirector

**Comment by einaregilsson** [comment]
Sorry, I have no plans to add an icon only for enabling/disabling redirector. I don't want to have multiple icons on the toolbar for one extensions.

**Comment by gkrishnaks** [comment]
@sant527, and chrome/Firefox webextension API allows only one icon per extension either as page action - (like the 'pocket' icon in address bar of Firefox) or browser action (as in Redirector)

@einaregilsson, can we close out this issue?

**Comment by sant527** [comment]
yes
