### ISSUE TITLE
Completely broken on Firefox 51.0.1

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [einaregilsson/Redirector#93]
Firefox 51.0.1 (32-bit)
Redirector 3.1.0

I noticed that my redirects weren't working so I looked for the Redirector statusbar icon and couldn't find it. Went to Addons and found Redirector and this is what I get:
![image](https://cloud.githubusercontent.com/assets/6548571/24072466/4061a984-0c3b-11e7-80df-16dc19d264a1.png)
The buttons don't do anything.

**Comment by einaregilsson** [comment]
No idea what's happening there. I've used it on 51 without problems. Any errors logged in the Browser Console?

**Comment by atomGit** [comment]
i can confirm the same issue on ff 52.0.2 - my settings ui appears exactly the same as above and the buttons don't do anything

console doesn't appear helpful - clicking the buttons produces no further output

```
REDIRECTOR: Redirector starting up...  background.js:6:3
REDIRECTOR: Setting filter for listener: {"urls":["https://*/*","http://*/*"],"types":["main_frame"]}  background.js:6:3
```

**Comment by einaregilsson** [comment]
Ok, I don't see this on my 52.0.2 on OSX. Are you on Windows? Looks like Angular might be blocked for some reason. Any messages in the web console when you're on the redirects page?

**Comment by atomGit** [comment]
Linux

what's Angular?

i'd test for console messages on redirected pages, but i don't know what they are since the settings don't work :)

**Comment by einaregilsson** [comment]
Try entering moz-extension://34850dbd-bda1-b643-95cc-6e973b7866d5/redirector.html in the url bar.

**Comment by atomGit** [comment]
the 'moz-extension://' url didn't do anything by itself i don't think - i closed all tabs and restarted the browser and checked the console after using the url you provided and following is the output, minus CSS...

`Could not read chrome manifest 'file:///usr/lib/firefox/chrome.manifest'.
Warning: attempting to write 5705 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead[Learn More]  bootstrap.js:688:7
Warning: attempting to write 5705 bytes to preference extensions.bootstrappedAddons. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file. This preference will not be sent to any content processes.
1492465715677	addons.webextension.@save-url-to-wayback-machine-firefox-addon	WARN	Please specify whether you want browser_style or not in your browser_action options.
1492465715697	addons.webextension.redirector@einaregilsson.com	WARN	Please specify whether you want browser_style or not in your browser_action options.
REDIRECTOR: Redirector starting up...  background.js:6:3
REDIRECTOR: Setting filter for listener: {"urls":["https://*/*","http://*/*"],"types":["main_frame"]}  background.js:6:3
JavaScript 1.6's for-each-in loops are deprecated; consider using ES6 for-of instead[Learn More]  browser.js:52:8
xS.bootstrapScopes is undefined  browser.js:28
S4E Calling updateWindow: {6a572d6a-ccb0-4959-93b0-d4727999c870}
S4E Calling updateWindow: {6a572d6a-ccb0-4959-93b0-d4727999c870}
Key event not available on GTK2: key=“u” modifiers=“control shift” id=“resurrect-key-shortcut”  browser.xul
Key event not available on some keyboard layouts: key=“r” modifiers=“accel,alt” id=“toggleReaderMode”  browser.xul
Key event not available on some keyboard layouts: key=“i” modifiers=“accel,alt,shift” id=“key_browserToolbox”  browser.xul
XML Parsing Error: no root element found
Location: data:text/plain,
Line Number 1, Column 1:  data::1:1
1492465779381	addons.productaddons	ERROR	Request failed certificate checks: [Exception... "SSL is required and URI scheme is not https."  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 145"  data: no]  Log.jsm:753`

**Comment by einaregilsson** [comment]
Ok, don't really see anything there. Hmmmm. I won't be able to look at this for a couple of weeks. You could try on a fresh profile with no other extensions and see if that works, other than that I don't have any ideas. I will try to repro this and fix it when I have time, but I can't promise when that will be.

**Comment by berrythesoftwarecodeprogrammar** [comment]
After updating to Firefox 53.0, I found the Redirector icon moved to the Add-on bar and it is functioning properly now.

**Comment by einaregilsson** [comment]
Well that worked itself out nicely then :)

**Comment by atomGit** [comment]
doesn't work on v53 for me - result is the same as the OP - you can't edit the redirects

**Comment by einaregilsson** [comment]
Ok, re-opening this. Still don't have time to work on it yet :)

**Comment by einaregilsson** [comment]
Haven't heard more about this from anyone, so closing it.
