### ISSUE TITLE
Firefox 52: Requests (or at least headers) are sent to original urls as well

### ISSUE THREAD

**Issue by einaregilsson** [einaregilsson/Redirector#94]
Hello Einar,
 
Thank you for your great extension. It has quickly become one of my favorite addons, and I'm glad that you made it for Chrome/Opera too. However, I'm sorry to report a bug in Redirector v3.10. Suppose I want to post a link to the following page:
 
(1) https://addons.mozilla.org/en-US/firefox/addon/redirector
 
Now, if I want to keep track of how many people clicked on my link, I could make a short-link that would direct someone to the target page while counting each click.
 
(2) https://waa.ai/jbaT ---> https://addons.mozilla.org/en-US/firefox/addon/redirector
 
Whenever I wanted to check my click counts, I could go to a stats page:
 
(3) https://stats.waa.ai/jbaT
 
I could bookmark a link to the stats page. But, since each short-link has a unique stat page, if I make dozens of short-links I would have to bookmark dozens of stat pages. Redirector saves me this extra effort by automatically redirecting me to the corresponding stats page, every time I click on one of my short-links.
 
https://waa.ai/jbaT
https://waa.ai/*
https://stats.waa.ai/$1
 
And, for many months that's what I have been doing. Whenever I was browsing, if I saw one of my own links, I would click on it, and Redirector would take me directly to the stats page. Except, recently, every time I click on the short link, Redirector increases my count by one. It didn't do that before, and Redirector doesn't do that in Opera. This means that if I use Redirector to check my stat pages, I will be biasing my own statistics . Even worse, it means that my redirects can somehow be tracked. Suppose I use Redirector to eliminate a typical Google redirect.
 
http://www.google.com/url?https://en.wikipedia.org/wiki/URL_redirection
*?http*
http$2
 
The above redirector will get me to: https://en.wikipedia.org/wiki/URL_redirection, but if Google knows that I've removed their own redirect, my search won't be completely anonymous.
 
It turns out that I can solve this problem by restoring Redirector v3.06. Redirector v3.06 doesn't increase my short-link stat counts, so presumably my redirects aren't being tracked. However, v3.06 presents me with another problem. It won't let me save any new redirects. Fortunately, ones that I have previously saved still work. So, if I want to create a new redirect, I can re-install v3.10. Once the new redirect is saved, I can switch back to v3.06. In Firefox 52.01, I get the following results.
 
1) Redirector v3.06 doesn't work in FF52.
2) Redirector v3.10 does work in FF52, however, it sends a referral which allows my redirect to be tracked.
3) If I revert to v3.06, after having already installed v3.1, Redirector will work without sending a referral. However, it will no longer be possible to save any new redirects.
 
Is there anyway you can fix this bug?

**Comment by Anthony-Mal** [comment]
I was wondering if you could fix this bug just by changing the config settings. Or, at least the config settings might give you an important clue about what to do. Suppose you had an app that would automatically tabulate all of Firefox's config settings and could also make cross comparisons after you install a given addon. Let's see how this might work.

1) You install a brand new version of portable Firefox 52.01. And the config app gives you a list of all the default settings.
2) You install Redirector v3.10 and then the app shows you which config settings have been changed. 
3) You install Redirector v3.06 (overwrite v3.10). 
4) You eliminate from consideration any config setting that has not been changed by either of the two addons.
5) You eliminate any config settings that are the same for both v3.06 and v3.10. That is, any config setting that was set by v3.10 but unchanged by v3.06. 
6) You are now left with only the config settings that 1) Differ from the default settings and 2) Differ between v3.06 and v3.10.

Would this help?

**Comment by einaregilsson** [comment]
Maybe. I kinda think that Firefox changed something that will be changed back in the next version. I know they changed the API I'm using so you can now return a Promise or a BlockingResponse, so maybe something went wrong there. In any case, I will look into this, I just don't have the time for the next few days or weeks.

**Comment by Anthony-Mal** [comment]
Well, what do you know? Firefox just released a security update, and voilà!

**Comment by einaregilsson** [comment]
Hmm, I just downloaded it and still see requests to the original url.

**Comment by Anthony-Mal** [comment]
Ooops. 

(1) https://stats.waa.ai/jbaT
(2) https://waa.ai/jbaT

Evidently, it's just another one of my brain farts. I used link (1) to test the redirect instead link (2). And, of course, link (1) is really just a direct link to the stat page. Sorry. 

So, to sum it all up. I install v3.10 whenever I want to create new directs. And, after I have them saved,  I then overwrite v3.10 with v3.06 and the redirect will work without sending the referrer. And, that's what I'll have to live with until Firefox is done with their updates.

**Comment by einaregilsson** [comment]
Ok, this is a known bug in FF52: https://bugzilla.mozilla.org/show_bug.cgi?id=1345893

Not much for me to do here except wait for them to fix it. Annoying :(

**Comment by Anthony-Mal** [comment]
Just a quick update. Redirector v3.04 seems to be working in Firefox 52.02. Apparently, all you have to do is change v3.04 to version 3.11 and you're done. Except, some users may still have problems. 

I began by installing Portable Firefox 52.0. Then I installed v3.04, and it worked. Then I updated to Firefox 52.02 and Redirector began sending a referer again. So, I trashed portable Firefox and installed it again. This time I updated to 52.02 BEFORE I installed v3.04, and it worked. 

Anyhow, as long as I can use v3.04 I don't have any immediate problems.

**Comment by einaregilsson** [comment]
@Anthony-Mal Unfortunately 52.02 still hasn't fixed the underlying bug  https://bugzilla.mozilla.org/show_bug.cgi?id=1345893 , but it's good you can use 3.04 in the meantime :)

**Comment by Gitoffthelawn** [comment]
I really hope Mozilla fixes that for 53.0.

**Comment by einaregilsson** [comment]
Yeah, Redirector is pretty bad with that bug, you want to be able to be sure that nothing is sent to the original site. It seems like a pretty serious bug to me, but apparently not enough to put it in a patch :/

**Comment by einaregilsson** [comment]
<img width="263" alt="screen shot 2017-04-17 at 12 53 38" src="https://cloud.githubusercontent.com/assets/557149/25089426/e7c176a8-236c-11e7-8e03-b1d6e232361a.png">

Crap, looks like it's not out until FF 55 which is what, 3x 6 weeks away?

**Comment by Gitoffthelawn** [comment]
Oh crap.  Well, almost that bad (probably)... they got rid of Aurora channel, so it might "just" be 2x 6 weeks.  Still, waaaay too long.

**Comment by einaregilsson** [comment]
Looks like they're trying to push it in 54, so that's at least a little better.

**Comment by Gitoffthelawn** [comment]
I hope they succeed 6 weeks is better than 2-3x that long.

**Comment by Gitoffthelawn** [comment]
Anyone want to see if it's working in the new Firefox Beta?  I would, but too much stuff going on right now.

**Comment by alexolog** [comment]
So those on 53ESR are screwed?

**Comment by einaregilsson** [comment]
@alexolog Pretty much. This was not a bug I could work around.
