### ISSUE TITLE
uMatrix domain blocking takes precedence over Redirector

### ISSUE THREAD

**Issue by LeLobster** [einaregilsson/Redirector#96]
* Use [uMatrix](https://github.com/gorhill/uMatrix) to block google.com  except when coming from google.com
```
* google.com * block  
google.com google.com * inherit
```
* Create a redirect rule

```
Redirect: \.?.*google\.*
to: https://youtube.com
Example: https://accounts.google.com/accounts/SetSID?ssdc= → https://youtube.com 
```
* Go to youtube.com and attempt to sign in via your google account
* This will take you to `https://accounts.google.com/*`  
(which matches the redirect regexp but doesn't get redirected, not sure why)
* Enter email and password and try to sign in
* uMatrix will say:
```
uMatrix has prevented the following page from loading:
https://accounts.google.com/accounts/SetSID?ssdc=1&sidt....
```
---
The expected result would be me getting redirected to `https://youtube.com` instead of seeing uMatrix's block message.  
Is there a way to work around this?

**Comment by Gitoffthelawn** [comment]
A thought or two:
 1) Try uninstalling both extensions, and re-install them in this order: Redirector first, then uMatrix.
 2) If (1) doesn't work, try uninstalling both extensions, and re-install them in the opposite order.

Not sure if this will help you, but it won't hurt.

**Comment by einaregilsson** [comment]
What @Gitoffthelawn said. When two or more extensions are both intercepting requests it's really just going to come down to which extension gets to handle the request first, I can't really control that.

**Comment by LeLobster** [comment]
@Gitoffthelawn @einaregilsson I've tried both orders of install, and restarted Firefox in between uninstalls/installs. No difference.

Maybe @gorhill has some input?

**Comment by LeLobster** [comment]
Seems like I _fixed_ it by adding `google.com accounts.google.com * allow` to uMatrix. Still weird how Firefox works with regards to this issue.

**Comment by gorhill** [comment]
> When two or more extensions are both intercepting requests it's really just going to come down to which extension gets to handle the request first

With WebExtensions, this is going to be even irrelevant which one blocks first, all the extensions' listeners are called, so uMatrix would block the request regardless of the order of installation. The proper and sane fix is just to not have uMatrix block the request if it has to be handled by another extension.

**Comment by einaregilsson** [comment]
@gorhill Ok, that makes sense. Redirector is a WebExtensions addon now, so I guess it's redirecting and uMatrix is blocking the same request, and the final effect is that it's blocked.
