### ISSUE TITLE
Redirect of bare number is ignored

### ISSUE THREAD

**Issue by dhduvall** [einaregilsson/Redirector#97]
I have a redirect:

    Redirect: ^(?:http://)?(\d{8})/?$
    to: https://bug.oraclecorp.com/pls/bug/webbug_print.show?c_rptno=$1
    Example: 15834580 → https://bug.oraclecorp.com/pls/bug/webbug_print.show?c_rptno=15834580
    Applies to: Main window (address bar)

On upgrade from Firefox 45.8 (ESR) to 52.0.2 (ESR), this stopped working.  FF now interprets the number as an IP address, and redirector never seems to get its hands on it.

I tried patching in https://bugzilla.mozilla.org/show_bug.cgi?id=1345893 as suggested in issue #94, but that didn't make any difference.

**Comment by einaregilsson** [comment]
There have been big changes in Redirector between these versions. I now use the WebExtensions API and use their redirection api. If Redirector doesn't get the url passed through there then there's not much that I can do :/
