### ISSUE TITLE
Why not useful examples of actual usage in a wiki page?

### ISSUE THREAD

**Issue by rieje** [einaregilsson/Redirector#98]
I've used similar addons to this (Clean Links, PureURL) and I've noticed that lots people create issues or ask questions regarding on how to set up appropriate settings for a specific site. They are most likely not using such an addon to the maximum potential. How about a basic list of useful examples where redirecting may be desirable in the wiki? For example, most people would want to avoid advertisements on a popular site and most people would want to clean unnecessary tracking URLs if doing so is completely harmless. That can get people contributing to it and people can take a look and benefit from it without asking the same questions. At least it serves a reference to tweak it for more complicated settings (for example more difficult regex). People can share what attributes may be problematic when cleaning them and which ones are fine to clean without much issues.

I realize there's a "Redirector Help" already (which is very good), but a wiki page of actual settings that are useful can get people started effortlessly and serves as a foundation for something to build on. It will also be useful for similar addons that probably use regex too.

**Comment by einaregilsson** [comment]
That's a good idea. There is a help page that comes with the addon, but it would be easier to update a Wiki. Maybe I'll dump the help page into a Wiki here on GitHub when I do the next release. Not sure when that will be though.

**Comment by jawz101** [comment]
it would be nice if it caught redirects and allowed me to base rules on them or just created rules automatically unless I whitelist them.

**Comment by einaregilsson** [comment]
@jawz101 Sorry, that's way too complicated. I'm not really planning on adding any more features to this addon.

**Comment by grahamperrin** [comment]
To complement the sites that are suggested in `help.html`, in the absence of a wiki, I guess that https://www.reddit.com/r/regex/ might be a good place to find examples of regular expressions that are generic (not specific to Redirector). 

https://old.reddit.com/r/regex/search?q=examples&restrict_sr=on&sort=new&t=all

Shameless plug (a question from me): [Rewriting web addresses to preview, not download, .msg file content in SharePoint : regex](https://www.reddit.com/r/regex/comments/k7uqkr/rewriting_web_addresses_to_preview_not_download/)
