### ISSUE TITLE
disabling redirector messages?

### ISSUE THREAD

**Issue by rezad1393** [einaregilsson/Redirector#99]
how do I disable redirector messages from browser console?
like this:
"REDIRECTOR: Checking: image: https://avatars2.githubusercontent.com/u/557149?v=3&s=32"

**Comment by einaregilsson** [comment]
Which version of Redirector do you have? I don't think those should appear in the latest version.

**Comment by rezad1393** [comment]
3.1.0

**Comment by einaregilsson** [comment]
Ok, I see I've accidentally left it enabled in the live version. No way to disable it, unless you can find where the extension is installed, find the file background.js and on line 9 change `log.enabled = true;`to `log.enabled = false;`

I'll disable it for the next version.

**Comment by rezad1393** [comment]
sure.
thanks.

**Comment by Gitoffthelawn** [comment]
Might want to reopen this so Einar has something to use to remember this issue.

**Comment by rezad1393** [comment]
ok

**Comment by byzod** [comment]
@rezad1393 I second this, the logging is a good to to check if my rules are really working, very useful.
@einaregilsson Please add an option (or about:config entry) to toggle it

**Comment by einaregilsson** [comment]
Will try to add some kind of option for it in the next version, leaving this open.

**Comment by rezad1393** [comment]
can somebody upload a modified version that has that logging disabled?
when I modify the background.js it will become disabled in firefox because I can't sign the addon.

**Comment by anewuser** [comment]
It was supposed to be disabled by default. @einaregilsson, I think you've forgotten to toggle it again.

**Comment by rezad1393** [comment]
no .
he hasn't released an update to modify anything since 3.1.0 at Aug 5 2016.

**Comment by anewuser** [comment]
Rezad, my point is that since the beginning of the extension, logging had been disabled by default. Since it is now enabled, it was an oversight.

**Comment by rezad1393** [comment]
I know.
I just want a fix to my problem.

**Comment by Qwash** [comment]
Hello @rezad1393 
just pump the version number of angular.min.js and it will be accepted

**Comment by rezad1393** [comment]
??
no .
I meant modifying the addon installed in my Firefox profile.
do you mean creating an addon?

**Comment by Qwash** [comment]
login and upload the edited version to get it signed 
https://addons.mozilla.org/en-US/developers/addon/submit/upload-unlisted

**Comment by einaregilsson** [comment]
Hi. Sorry about the late replies. I've uploaded version 3.1.1 which has logging off by default, and an option to enable it in the popup window.

**Comment by Gitoffthelawn** [comment]
The new `Logging enabled` checkbox label is much larger than the main buttons (Enable/Disable Redirector and Edit Redirects).  Maybe just reduce the font size within <label>?  I can submit a PR if you like.

**Comment by rezad1393** [comment]
thanks

**Comment by einaregilsson** [comment]
@Gitoffthelawn Crap, I just tested in Chrome and I guess they have different defaults or something. I'll fix it for the next release, it's working now, even if ugly. Next release is all about getting rid of Angular, but I can squeeze this in there.

**Comment by Gitoffthelawn** [comment]
@einaregilsson Great!  Thanks! :)
